// Code generated by protoc-gen-go-vtproto. DO NOT EDIT.
// protoc-gen-go-vtproto version: v0.6.1-0.20250313105119-ba97887b0a25
// source: cerbos/response/v1/response.proto

package responsev1

import (
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

func (m *PlanResourcesResponse_Meta) MarshalVT() (dAtA []byte, err error) {
	_ = "STUB: not implemented"
	return nil, nil
}

func (m *PlanResourcesResponse_Meta) MarshalToVT(dAtA []byte) (int, error) {
	_ = "STUB: not implemented"
	return 0, nil
}

func (m *PlanResourcesResponse_Meta) MarshalToSizedBufferVT(dAtA []byte) (int, error) {
	_ = "STUB: not implemented"
	return 0, nil
}

func (m *PlanResourcesResponse) MarshalVT() (dAtA []byte, err error) {
	_ = "STUB: not implemented"
	return nil, nil
}

func (m *PlanResourcesResponse) MarshalToVT(dAtA []byte) (int, error) {
	_ = "STUB: not implemented"
	return 0, nil
}

func (m *PlanResourcesResponse) MarshalToSizedBufferVT(dAtA []byte) (int, error) {
	_ = "STUB: not implemented"
	return 0, nil
}

func (m *CheckResourceSetResponse_ActionEffectMap) MarshalVT() (dAtA []byte, err error) {
	_ = "STUB: not implemented"
	return nil, nil
}

func (m *CheckResourceSetResponse_ActionEffectMap) MarshalToVT(dAtA []byte) (int, error) {
	_ = "STUB: not implemented"
	return 0, nil
}

func (m *CheckResourceSetResponse_ActionEffectMap) MarshalToSizedBufferVT(dAtA []byte) (int, error) {
	_ = "STUB: not implemented"
	return 0, nil
}

func (m *CheckResourceSetResponse_Meta_EffectMeta) MarshalVT() (dAtA []byte, err error) {
	_ = "STUB: not implemented"
	return nil, nil
}

func (m *CheckResourceSetResponse_Meta_EffectMeta) MarshalToVT(dAtA []byte) (int, error) {
	_ = "STUB: not implemented"
	return 0, nil
}

func (m *CheckResourceSetResponse_Meta_EffectMeta) MarshalToSizedBufferVT(dAtA []byte) (int, error) {
	_ = "STUB: not implemented"
	return 0, nil
}

func (m *CheckResourceSetResponse_Meta_ActionMeta) MarshalVT() (dAtA []byte, err error) {
	_ = "STUB: not implemented"
	return nil, nil
}

func (m *CheckResourceSetResponse_Meta_ActionMeta) MarshalToVT(dAtA []byte) (int, error) {
	_ = "STUB: not implemented"
	return 0, nil
}

func (m *CheckResourceSetResponse_Meta_ActionMeta) MarshalToSizedBufferVT(dAtA []byte) (int, error) {
	_ = "STUB: not implemented"
	return 0, nil
}

func (m *CheckResourceSetResponse_Meta) MarshalVT() (dAtA []byte, err error) {
	_ = "STUB: not implemented"
	return nil, nil
}

func (m *CheckResourceSetResponse_Meta) MarshalToVT(dAtA []byte) (int, error) {
	_ = "STUB: not implemented"
	return 0, nil
}

func (m *CheckResourceSetResponse_Meta) MarshalToSizedBufferVT(dAtA []byte) (int, error) {
	_ = "STUB: not implemented"
	return 0, nil
}

func (m *CheckResourceSetResponse) MarshalVT() (dAtA []byte, err error) {
	_ = "STUB: not implemented"
	return nil, nil
}

func (m *CheckResourceSetResponse) MarshalToVT(dAtA []byte) (int, error) {
	_ = "STUB: not implemented"
	return 0, nil
}

func (m *CheckResourceSetResponse) MarshalToSizedBufferVT(dAtA []byte) (int, error) {
	_ = "STUB: not implemented"
	return 0, nil
}

func (m *CheckResourceBatchResponse_ActionEffectMap) MarshalVT() (dAtA []byte, err error) {
	_ = "STUB: not implemented"
	return nil, nil
}

func (m *CheckResourceBatchResponse_ActionEffectMap) MarshalToVT(dAtA []byte) (int, error) {
	_ = "STUB: not implemented"
	return 0, nil
}

func (m *CheckResourceBatchResponse_ActionEffectMap) MarshalToSizedBufferVT(dAtA []byte) (int, error) {
	_ = "STUB: not implemented"
	return 0, nil
}

func (m *CheckResourceBatchResponse) MarshalVT() (dAtA []byte, err error) {
	_ = "STUB: not implemented"
	return nil, nil
}

func (m *CheckResourceBatchResponse) MarshalToVT(dAtA []byte) (int, error) {
	_ = "STUB: not implemented"
	return 0, nil
}

func (m *CheckResourceBatchResponse) MarshalToSizedBufferVT(dAtA []byte) (int, error) {
	_ = "STUB: not implemented"
	return 0, nil
}

func (m *CheckResourcesResponse_ResultEntry_Resource) MarshalVT() (dAtA []byte, err error) {
	_ = "STUB: not implemented"
	return nil, nil
}

func (m *CheckResourcesResponse_ResultEntry_Resource) MarshalToVT(dAtA []byte) (int, error) {
	_ = "STUB: not implemented"
	return 0, nil
}

func (m *CheckResourcesResponse_ResultEntry_Resource) MarshalToSizedBufferVT(dAtA []byte) (int, error) {
	_ = "STUB: not implemented"
	return 0, nil
}

func (m *CheckResourcesResponse_ResultEntry_Meta_EffectMeta) MarshalVT() (dAtA []byte, err error) {
	_ = "STUB: not implemented"
	return nil, nil
}

func (m *CheckResourcesResponse_ResultEntry_Meta_EffectMeta) MarshalToVT(dAtA []byte) (int, error) {
	_ = "STUB: not implemented"
	return 0, nil
}

func (m *CheckResourcesResponse_ResultEntry_Meta_EffectMeta) MarshalToSizedBufferVT(dAtA []byte) (int, error) {
	_ = "STUB: not implemented"
	return 0, nil
}

func (m *CheckResourcesResponse_ResultEntry_Meta) MarshalVT() (dAtA []byte, err error) {
	_ = "STUB: not implemented"
	return nil, nil
}

func (m *CheckResourcesResponse_ResultEntry_Meta) MarshalToVT(dAtA []byte) (int, error) {
	_ = "STUB: not implemented"
	return 0, nil
}

func (m *CheckResourcesResponse_ResultEntry_Meta) MarshalToSizedBufferVT(dAtA []byte) (int, error) {
	_ = "STUB: not implemented"
	return 0, nil
}

func (m *CheckResourcesResponse_ResultEntry) MarshalVT() (dAtA []byte, err error) {
	_ = "STUB: not implemented"
	return nil, nil
}

func (m *CheckResourcesResponse_ResultEntry) MarshalToVT(dAtA []byte) (int, error) {
	_ = "STUB: not implemented"
	return 0, nil
}

func (m *CheckResourcesResponse_ResultEntry) MarshalToSizedBufferVT(dAtA []byte) (int, error) {
	_ = "STUB: not implemented"
	return 0, nil
}

func (m *CheckResourcesResponse) MarshalVT() (dAtA []byte, err error) {
	_ = "STUB: not implemented"
	return nil, nil
}

func (m *CheckResourcesResponse) MarshalToVT(dAtA []byte) (int, error) {
	_ = "STUB: not implemented"
	return 0, nil
}

func (m *CheckResourcesResponse) MarshalToSizedBufferVT(dAtA []byte) (int, error) {
	_ = "STUB: not implemented"
	return 0, nil
}

func (m *PlaygroundFailure_ErrorDetails) MarshalVT() (dAtA []byte, err error) {
	_ = "STUB: not implemented"
	return nil, nil
}

func (m *PlaygroundFailure_ErrorDetails) MarshalToVT(dAtA []byte) (int, error) {
	_ = "STUB: not implemented"
	return 0, nil
}

func (m *PlaygroundFailure_ErrorDetails) MarshalToSizedBufferVT(dAtA []byte) (int, error) {
	_ = "STUB: not implemented"
	return 0, nil
}

func (m *PlaygroundFailure_Error) MarshalVT() (dAtA []byte, err error) {
	_ = "STUB: not implemented"
	return nil, nil
}

func (m *PlaygroundFailure_Error) MarshalToVT(dAtA []byte) (int, error) {
	_ = "STUB: not implemented"
	return 0, nil
}

func (m *PlaygroundFailure_Error) MarshalToSizedBufferVT(dAtA []byte) (int, error) {
	_ = "STUB: not implemented"
	return 0, nil
}

func (m *PlaygroundFailure) MarshalVT() (dAtA []byte, err error) {
	_ = "STUB: not implemented"
	return nil, nil
}

func (m *PlaygroundFailure) MarshalToVT(dAtA []byte) (int, error) {
	_ = "STUB: not implemented"
	return 0, nil
}

func (m *PlaygroundFailure) MarshalToSizedBufferVT(dAtA []byte) (int, error) {
	_ = "STUB: not implemented"
	return 0, nil
}

func (m *PlaygroundValidateResponse) MarshalVT() (dAtA []byte, err error) {
	_ = "STUB: not implemented"
	return nil, nil
}

func (m *PlaygroundValidateResponse) MarshalToVT(dAtA []byte) (int, error) {
	_ = "STUB: not implemented"
	return 0, nil
}

func (m *PlaygroundValidateResponse) MarshalToSizedBufferVT(dAtA []byte) (int, error) {
	_ = "STUB: not implemented"
	return 0, nil
}

func (m *PlaygroundValidateResponse_Failure) MarshalToVT(dAtA []byte) (int, error) {
	_ = "STUB: not implemented"
	return 0, nil
}

func (m *PlaygroundValidateResponse_Failure) MarshalToSizedBufferVT(dAtA []byte) (int, error) {
	_ = "STUB: not implemented"
	return 0, nil
}

func (m *PlaygroundValidateResponse_Success) MarshalToVT(dAtA []byte) (int, error) {
	_ = "STUB: not implemented"
	return 0, nil
}

func (m *PlaygroundValidateResponse_Success) MarshalToSizedBufferVT(dAtA []byte) (int, error) {
	_ = "STUB: not implemented"
	return 0, nil
}

func (m *PlaygroundTestResponse_TestResults) MarshalVT() (dAtA []byte, err error) {
	_ = "STUB: not implemented"
	return nil, nil
}

func (m *PlaygroundTestResponse_TestResults) MarshalToVT(dAtA []byte) (int, error) {
	_ = "STUB: not implemented"
	return 0, nil
}

func (m *PlaygroundTestResponse_TestResults) MarshalToSizedBufferVT(dAtA []byte) (int, error) {
	_ = "STUB: not implemented"
	return 0, nil
}

func (m *PlaygroundTestResponse) MarshalVT() (dAtA []byte, err error) {
	_ = "STUB: not implemented"
	return nil, nil
}

func (m *PlaygroundTestResponse) MarshalToVT(dAtA []byte) (int, error) {
	_ = "STUB: not implemented"
	return 0, nil
}

func (m *PlaygroundTestResponse) MarshalToSizedBufferVT(dAtA []byte) (int, error) {
	_ = "STUB: not implemented"
	return 0, nil
}

func (m *PlaygroundTestResponse_Failure) MarshalToVT(dAtA []byte) (int, error) {
	_ = "STUB: not implemented"
	return 0, nil
}

func (m *PlaygroundTestResponse_Failure) MarshalToSizedBufferVT(dAtA []byte) (int, error) {
	_ = "STUB: not implemented"
	return 0, nil
}

func (m *PlaygroundTestResponse_Success) MarshalToVT(dAtA []byte) (int, error) {
	_ = "STUB: not implemented"
	return 0, nil
}

func (m *PlaygroundTestResponse_Success) MarshalToSizedBufferVT(dAtA []byte) (int, error) {
	_ = "STUB: not implemented"
	return 0, nil
}

func (m *PlaygroundEvaluateResponse_EvalResult) MarshalVT() (dAtA []byte, err error) {
	_ = "STUB: not implemented"
	return nil, nil
}

func (m *PlaygroundEvaluateResponse_EvalResult) MarshalToVT(dAtA []byte) (int, error) {
	_ = "STUB: not implemented"
	return 0, nil
}

func (m *PlaygroundEvaluateResponse_EvalResult) MarshalToSizedBufferVT(dAtA []byte) (int, error) {
	_ = "STUB: not implemented"
	return 0, nil
}

func (m *PlaygroundEvaluateResponse_EvalResultList) MarshalVT() (dAtA []byte, err error) {
	_ = "STUB: not implemented"
	return nil, nil
}

func (m *PlaygroundEvaluateResponse_EvalResultList) MarshalToVT(dAtA []byte) (int, error) {
	_ = "STUB: not implemented"
	return 0, nil
}

func (m *PlaygroundEvaluateResponse_EvalResultList) MarshalToSizedBufferVT(dAtA []byte) (int, error) {
	_ = "STUB: not implemented"
	return 0, nil
}

func (m *PlaygroundEvaluateResponse) MarshalVT() (dAtA []byte, err error) {
	_ = "STUB: not implemented"
	return nil, nil
}

func (m *PlaygroundEvaluateResponse) MarshalToVT(dAtA []byte) (int, error) {
	_ = "STUB: not implemented"
	return 0, nil
}

func (m *PlaygroundEvaluateResponse) MarshalToSizedBufferVT(dAtA []byte) (int, error) {
	_ = "STUB: not implemented"
	return 0, nil
}

func (m *PlaygroundEvaluateResponse_Failure) MarshalToVT(dAtA []byte) (int, error) {
	_ = "STUB: not implemented"
	return 0, nil
}

func (m *PlaygroundEvaluateResponse_Failure) MarshalToSizedBufferVT(dAtA []byte) (int, error) {
	_ = "STUB: not implemented"
	return 0, nil
}

func (m *PlaygroundEvaluateResponse_Success) MarshalToVT(dAtA []byte) (int, error) {
	_ = "STUB: not implemented"
	return 0, nil
}

func (m *PlaygroundEvaluateResponse_Success) MarshalToSizedBufferVT(dAtA []byte) (int, error) {
	_ = "STUB: not implemented"
	return 0, nil
}

func (m *PlaygroundProxyResponse) MarshalVT() (dAtA []byte, err error) {
	_ = "STUB: not implemented"
	return nil, nil
}

func (m *PlaygroundProxyResponse) MarshalToVT(dAtA []byte) (int, error) {
	_ = "STUB: not implemented"
	return 0, nil
}

func (m *PlaygroundProxyResponse) MarshalToSizedBufferVT(dAtA []byte) (int, error) {
	_ = "STUB: not implemented"
	return 0, nil
}

func (m *PlaygroundProxyResponse_Failure) MarshalToVT(dAtA []byte) (int, error) {
	_ = "STUB: not implemented"
	return 0, nil
}

func (m *PlaygroundProxyResponse_Failure) MarshalToSizedBufferVT(dAtA []byte) (int, error) {
	_ = "STUB: not implemented"
	return 0, nil
}

func (m *PlaygroundProxyResponse_CheckResourceSet) MarshalToVT(dAtA []byte) (int, error) {
	_ = "STUB: not implemented"
	return 0, nil
}

func (m *PlaygroundProxyResponse_CheckResourceSet) MarshalToSizedBufferVT(dAtA []byte) (int, error) {
	_ = "STUB: not implemented"
	return 0, nil
}

func (m *PlaygroundProxyResponse_CheckResourceBatch) MarshalToVT(dAtA []byte) (int, error) {
	_ = "STUB: not implemented"
	return 0, nil
}

func (m *PlaygroundProxyResponse_CheckResourceBatch) MarshalToSizedBufferVT(dAtA []byte) (int, error) {
	_ = "STUB: not implemented"
	return 0, nil
}

func (m *PlaygroundProxyResponse_PlanResources) MarshalToVT(dAtA []byte) (int, error) {
	_ = "STUB: not implemented"
	return 0, nil
}

func (m *PlaygroundProxyResponse_PlanResources) MarshalToSizedBufferVT(dAtA []byte) (int, error) {
	_ = "STUB: not implemented"
	return 0, nil
}

func (m *PlaygroundProxyResponse_CheckResources) MarshalToVT(dAtA []byte) (int, error) {
	_ = "STUB: not implemented"
	return 0, nil
}

func (m *PlaygroundProxyResponse_CheckResources) MarshalToSizedBufferVT(dAtA []byte) (int, error) {
	_ = "STUB: not implemented"
	return 0, nil
}

func (m *AddOrUpdatePolicyResponse) MarshalVT() (dAtA []byte, err error) {
	_ = "STUB: not implemented"
	return nil, nil
}

func (m *AddOrUpdatePolicyResponse) MarshalToVT(dAtA []byte) (int, error) {
	_ = "STUB: not implemented"
	return 0, nil
}

func (m *AddOrUpdatePolicyResponse) MarshalToSizedBufferVT(dAtA []byte) (int, error) {
	_ = "STUB: not implemented"
	return 0, nil
}

func (m *ListAuditLogEntriesResponse) MarshalVT() (dAtA []byte, err error) {
	_ = "STUB: not implemented"
	return nil, nil
}

func (m *ListAuditLogEntriesResponse) MarshalToVT(dAtA []byte) (int, error) {
	_ = "STUB: not implemented"
	return 0, nil
}

func (m *ListAuditLogEntriesResponse) MarshalToSizedBufferVT(dAtA []byte) (int, error) {
	_ = "STUB: not implemented"
	return 0, nil
}

func (m *ListAuditLogEntriesResponse_AccessLogEntry) MarshalToVT(dAtA []byte) (int, error) {
	_ = "STUB: not implemented"
	return 0, nil
}

func (m *ListAuditLogEntriesResponse_AccessLogEntry) MarshalToSizedBufferVT(dAtA []byte) (int, error) {
	_ = "STUB: not implemented"
	return 0, nil
}

func (m *ListAuditLogEntriesResponse_DecisionLogEntry) MarshalToVT(dAtA []byte) (int, error) {
	_ = "STUB: not implemented"
	return 0, nil
}

func (m *ListAuditLogEntriesResponse_DecisionLogEntry) MarshalToSizedBufferVT(dAtA []byte) (int, error) {
	_ = "STUB: not implemented"
	return 0, nil
}

func (m *ServerInfoResponse) MarshalVT() (dAtA []byte, err error) {
	_ = "STUB: not implemented"
	return nil, nil
}

func (m *ServerInfoResponse) MarshalToVT(dAtA []byte) (int, error) {
	_ = "STUB: not implemented"
	return 0, nil
}

func (m *ServerInfoResponse) MarshalToSizedBufferVT(dAtA []byte) (int, error) {
	_ = "STUB: not implemented"
	return 0, nil
}

func (m *ListPoliciesResponse) MarshalVT() (dAtA []byte, err error) {
	_ = "STUB: not implemented"
	return nil, nil
}

func (m *ListPoliciesResponse) MarshalToVT(dAtA []byte) (int, error) {
	_ = "STUB: not implemented"
	return 0, nil
}

func (m *ListPoliciesResponse) MarshalToSizedBufferVT(dAtA []byte) (int, error) {
	_ = "STUB: not implemented"
	return 0, nil
}

func (m *GetPolicyResponse) MarshalVT() (dAtA []byte, err error) {
	_ = "STUB: not implemented"
	return nil, nil
}

func (m *GetPolicyResponse) MarshalToVT(dAtA []byte) (int, error) {
	_ = "STUB: not implemented"
	return 0, nil
}

func (m *GetPolicyResponse) MarshalToSizedBufferVT(dAtA []byte) (int, error) {
	_ = "STUB: not implemented"
	return 0, nil
}

func (m *DeletePolicyResponse) MarshalVT() (dAtA []byte, err error) {
	_ = "STUB: not implemented"
	return nil, nil
}

func (m *DeletePolicyResponse) MarshalToVT(dAtA []byte) (int, error) {
	_ = "STUB: not implemented"
	return 0, nil
}

func (m *DeletePolicyResponse) MarshalToSizedBufferVT(dAtA []byte) (int, error) {
	_ = "STUB: not implemented"
	return 0, nil
}

func (m *DeletePolicyErrorDetails) MarshalVT() (dAtA []byte, err error) {
	_ = "STUB: not implemented"
	return nil, nil
}

func (m *DeletePolicyErrorDetails) MarshalToVT(dAtA []byte) (int, error) {
	_ = "STUB: not implemented"
	return 0, nil
}

func (m *DeletePolicyErrorDetails) MarshalToSizedBufferVT(dAtA []byte) (int, error) {
	_ = "STUB: not implemented"
	return 0, nil
}

func (m *DisablePolicyResponse) MarshalVT() (dAtA []byte, err error) {
	_ = "STUB: not implemented"
	return nil, nil
}

func (m *DisablePolicyResponse) MarshalToVT(dAtA []byte) (int, error) {
	_ = "STUB: not implemented"
	return 0, nil
}

func (m *DisablePolicyResponse) MarshalToSizedBufferVT(dAtA []byte) (int, error) {
	_ = "STUB: not implemented"
	return 0, nil
}

func (m *DisablePolicyErrorDetails) MarshalVT() (dAtA []byte, err error) {
	_ = "STUB: not implemented"
	return nil, nil
}

func (m *DisablePolicyErrorDetails) MarshalToVT(dAtA []byte) (int, error) {
	_ = "STUB: not implemented"
	return 0, nil
}

func (m *DisablePolicyErrorDetails) MarshalToSizedBufferVT(dAtA []byte) (int, error) {
	_ = "STUB: not implemented"
	return 0, nil
}

func (m *IntegrityErrors_BreaksScopeChain) MarshalVT() (dAtA []byte, err error) {
	_ = "STUB: not implemented"
	return nil, nil
}

func (m *IntegrityErrors_BreaksScopeChain) MarshalToVT(dAtA []byte) (int, error) {
	_ = "STUB: not implemented"
	return 0, nil
}

func (m *IntegrityErrors_BreaksScopeChain) MarshalToSizedBufferVT(dAtA []byte) (int, error) {
	_ = "STUB: not implemented"
	return 0, nil
}

func (m *IntegrityErrors_RequiredByOtherPolicies) MarshalVT() (dAtA []byte, err error) {
	_ = "STUB: not implemented"
	return nil, nil
}

func (m *IntegrityErrors_RequiredByOtherPolicies) MarshalToVT(dAtA []byte) (int, error) {
	_ = "STUB: not implemented"
	return 0, nil
}

func (m *IntegrityErrors_RequiredByOtherPolicies) MarshalToSizedBufferVT(dAtA []byte) (int, error) {
	_ = "STUB: not implemented"
	return 0, nil
}

func (m *IntegrityErrors) MarshalVT() (dAtA []byte, err error) {
	_ = "STUB: not implemented"
	return nil, nil
}

func (m *IntegrityErrors) MarshalToVT(dAtA []byte) (int, error) {
	_ = "STUB: not implemented"
	return 0, nil
}

func (m *IntegrityErrors) MarshalToSizedBufferVT(dAtA []byte) (int, error) {
	_ = "STUB: not implemented"
	return 0, nil
}

func (m *EnablePolicyResponse) MarshalVT() (dAtA []byte, err error) {
	_ = "STUB: not implemented"
	return nil, nil
}

func (m *EnablePolicyResponse) MarshalToVT(dAtA []byte) (int, error) {
	_ = "STUB: not implemented"
	return 0, nil
}

func (m *EnablePolicyResponse) MarshalToSizedBufferVT(dAtA []byte) (int, error) {
	_ = "STUB: not implemented"
	return 0, nil
}

func (m *InspectPoliciesResponse_Attribute) MarshalVT() (dAtA []byte, err error) {
	_ = "STUB: not implemented"
	return nil, nil
}

func (m *InspectPoliciesResponse_Attribute) MarshalToVT(dAtA []byte) (int, error) {
	_ = "STUB: not implemented"
	return 0, nil
}

func (m *InspectPoliciesResponse_Attribute) MarshalToSizedBufferVT(dAtA []byte) (int, error) {
	_ = "STUB: not implemented"
	return 0, nil
}

func (m *InspectPoliciesResponse_DerivedRole) MarshalVT() (dAtA []byte, err error) {
	_ = "STUB: not implemented"
	return nil, nil
}

func (m *InspectPoliciesResponse_DerivedRole) MarshalToVT(dAtA []byte) (int, error) {
	_ = "STUB: not implemented"
	return 0, nil
}

func (m *InspectPoliciesResponse_DerivedRole) MarshalToSizedBufferVT(dAtA []byte) (int, error) {
	_ = "STUB: not implemented"
	return 0, nil
}

func (m *InspectPoliciesResponse_Constant) MarshalVT() (dAtA []byte, err error) {
	_ = "STUB: not implemented"
	return nil, nil
}

func (m *InspectPoliciesResponse_Constant) MarshalToVT(dAtA []byte) (int, error) {
	_ = "STUB: not implemented"
	return 0, nil
}

func (m *InspectPoliciesResponse_Constant) MarshalToSizedBufferVT(dAtA []byte) (int, error) {
	_ = "STUB: not implemented"
	return 0, nil
}

func (m *InspectPoliciesResponse_Variable) MarshalVT() (dAtA []byte, err error) {
	_ = "STUB: not implemented"
	return nil, nil
}

func (m *InspectPoliciesResponse_Variable) MarshalToVT(dAtA []byte) (int, error) {
	_ = "STUB: not implemented"
	return 0, nil
}

func (m *InspectPoliciesResponse_Variable) MarshalToSizedBufferVT(dAtA []byte) (int, error) {
	_ = "STUB: not implemented"
	return 0, nil
}

func (m *InspectPoliciesResponse_Result) MarshalVT() (dAtA []byte, err error) {
	_ = "STUB: not implemented"
	return nil, nil
}

func (m *InspectPoliciesResponse_Result) MarshalToVT(dAtA []byte) (int, error) {
	_ = "STUB: not implemented"
	return 0, nil
}

func (m *InspectPoliciesResponse_Result) MarshalToSizedBufferVT(dAtA []byte) (int, error) {
	_ = "STUB: not implemented"
	return 0, nil
}

func (m *InspectPoliciesResponse) MarshalVT() (dAtA []byte, err error) {
	_ = "STUB: not implemented"
	return nil, nil
}

func (m *InspectPoliciesResponse) MarshalToVT(dAtA []byte) (int, error) {
	_ = "STUB: not implemented"
	return 0, nil
}

func (m *InspectPoliciesResponse) MarshalToSizedBufferVT(dAtA []byte) (int, error) {
	_ = "STUB: not implemented"
	return 0, nil
}

func (m *AddOrUpdateSchemaResponse) MarshalVT() (dAtA []byte, err error) {
	_ = "STUB: not implemented"
	return nil, nil
}

func (m *AddOrUpdateSchemaResponse) MarshalToVT(dAtA []byte) (int, error) {
	_ = "STUB: not implemented"
	return 0, nil
}

func (m *AddOrUpdateSchemaResponse) MarshalToSizedBufferVT(dAtA []byte) (int, error) {
	_ = "STUB: not implemented"
	return 0, nil
}

func (m *ListSchemasResponse) MarshalVT() (dAtA []byte, err error) {
	_ = "STUB: not implemented"
	return nil, nil
}

func (m *ListSchemasResponse) MarshalToVT(dAtA []byte) (int, error) {
	_ = "STUB: not implemented"
	return 0, nil
}

func (m *ListSchemasResponse) MarshalToSizedBufferVT(dAtA []byte) (int, error) {
	_ = "STUB: not implemented"
	return 0, nil
}

func (m *GetSchemaResponse) MarshalVT() (dAtA []byte, err error) {
	_ = "STUB: not implemented"
	return nil, nil
}

func (m *GetSchemaResponse) MarshalToVT(dAtA []byte) (int, error) {
	_ = "STUB: not implemented"
	return 0, nil
}

func (m *GetSchemaResponse) MarshalToSizedBufferVT(dAtA []byte) (int, error) {
	_ = "STUB: not implemented"
	return 0, nil
}

func (m *DeleteSchemaResponse) MarshalVT() (dAtA []byte, err error) {
	_ = "STUB: not implemented"
	return nil, nil
}

func (m *DeleteSchemaResponse) MarshalToVT(dAtA []byte) (int, error) {
	_ = "STUB: not implemented"
	return 0, nil
}

func (m *DeleteSchemaResponse) MarshalToSizedBufferVT(dAtA []byte) (int, error) {
	_ = "STUB: not implemented"
	return 0, nil
}

func (m *ReloadStoreResponse) MarshalVT() (dAtA []byte, err error) {
	_ = "STUB: not implemented"
	return nil, nil
}

func (m *ReloadStoreResponse) MarshalToVT(dAtA []byte) (int, error) {
	_ = "STUB: not implemented"
	return 0, nil
}

func (m *ReloadStoreResponse) MarshalToSizedBufferVT(dAtA []byte) (int, error) {
	_ = "STUB: not implemented"
	return 0, nil
}

func (m *PurgeStoreRevisionsResponse) MarshalVT() (dAtA []byte, err error) {
	_ = "STUB: not implemented"
	return nil, nil
}

func (m *PurgeStoreRevisionsResponse) MarshalToVT(dAtA []byte) (int, error) {
	_ = "STUB: not implemented"
	return 0, nil
}

func (m *PurgeStoreRevisionsResponse) MarshalToSizedBufferVT(dAtA []byte) (int, error) {
	_ = "STUB: not implemented"
	return 0, nil
}

func (m *PlanResourcesResponse_Meta) SizeVT() (n int) { _ = "STUB: not implemented"; return 0 }

func (m *PlanResourcesResponse) SizeVT() (n int) { _ = "STUB: not implemented"; return 0 }

func (m *CheckResourceSetResponse_ActionEffectMap) SizeVT() (n int) {
	_ = "STUB: not implemented"
	return 0
}

func (m *CheckResourceSetResponse_Meta_EffectMeta) SizeVT() (n int) {
	_ = "STUB: not implemented"
	return 0
}

func (m *CheckResourceSetResponse_Meta_ActionMeta) SizeVT() (n int) {
	_ = "STUB: not implemented"
	return 0
}

func (m *CheckResourceSetResponse_Meta) SizeVT() (n int) { _ = "STUB: not implemented"; return 0 }

func (m *CheckResourceSetResponse) SizeVT() (n int) { _ = "STUB: not implemented"; return 0 }

func (m *CheckResourceBatchResponse_ActionEffectMap) SizeVT() (n int) {
	_ = "STUB: not implemented"
	return 0
}

func (m *CheckResourceBatchResponse) SizeVT() (n int) { _ = "STUB: not implemented"; return 0 }

func (m *CheckResourcesResponse_ResultEntry_Resource) SizeVT() (n int) {
	_ = "STUB: not implemented"
	return 0
}

func (m *CheckResourcesResponse_ResultEntry_Meta_EffectMeta) SizeVT() (n int) {
	_ = "STUB: not implemented"
	return 0
}

func (m *CheckResourcesResponse_ResultEntry_Meta) SizeVT() (n int) {
	_ = "STUB: not implemented"
	return 0
}

func (m *CheckResourcesResponse_ResultEntry) SizeVT() (n int) { _ = "STUB: not implemented"; return 0 }

func (m *CheckResourcesResponse) SizeVT() (n int) { _ = "STUB: not implemented"; return 0 }

func (m *PlaygroundFailure_ErrorDetails) SizeVT() (n int) { _ = "STUB: not implemented"; return 0 }

func (m *PlaygroundFailure_Error) SizeVT() (n int) { _ = "STUB: not implemented"; return 0 }

func (m *PlaygroundFailure) SizeVT() (n int) { _ = "STUB: not implemented"; return 0 }

func (m *PlaygroundValidateResponse) SizeVT() (n int) { _ = "STUB: not implemented"; return 0 }

func (m *PlaygroundValidateResponse_Failure) SizeVT() (n int) { _ = "STUB: not implemented"; return 0 }

func (m *PlaygroundValidateResponse_Success) SizeVT() (n int) { _ = "STUB: not implemented"; return 0 }

func (m *PlaygroundTestResponse_TestResults) SizeVT() (n int) { _ = "STUB: not implemented"; return 0 }

func (m *PlaygroundTestResponse) SizeVT() (n int) { _ = "STUB: not implemented"; return 0 }

func (m *PlaygroundTestResponse_Failure) SizeVT() (n int) { _ = "STUB: not implemented"; return 0 }

func (m *PlaygroundTestResponse_Success) SizeVT() (n int) { _ = "STUB: not implemented"; return 0 }

func (m *PlaygroundEvaluateResponse_EvalResult) SizeVT() (n int) {
	_ = "STUB: not implemented"
	return 0
}

func (m *PlaygroundEvaluateResponse_EvalResultList) SizeVT() (n int) {
	_ = "STUB: not implemented"
	return 0
}

func (m *PlaygroundEvaluateResponse) SizeVT() (n int) { _ = "STUB: not implemented"; return 0 }

func (m *PlaygroundEvaluateResponse_Failure) SizeVT() (n int) { _ = "STUB: not implemented"; return 0 }

func (m *PlaygroundEvaluateResponse_Success) SizeVT() (n int) { _ = "STUB: not implemented"; return 0 }

func (m *PlaygroundProxyResponse) SizeVT() (n int) { _ = "STUB: not implemented"; return 0 }

func (m *PlaygroundProxyResponse_Failure) SizeVT() (n int) { _ = "STUB: not implemented"; return 0 }

func (m *PlaygroundProxyResponse_CheckResourceSet) SizeVT() (n int) {
	_ = "STUB: not implemented"
	return 0
}

func (m *PlaygroundProxyResponse_CheckResourceBatch) SizeVT() (n int) {
	_ = "STUB: not implemented"
	return 0
}

func (m *PlaygroundProxyResponse_PlanResources) SizeVT() (n int) {
	_ = "STUB: not implemented"
	return 0
}

func (m *PlaygroundProxyResponse_CheckResources) SizeVT() (n int) {
	_ = "STUB: not implemented"
	return 0
}

func (m *AddOrUpdatePolicyResponse) SizeVT() (n int) { _ = "STUB: not implemented"; return 0 }

func (m *ListAuditLogEntriesResponse) SizeVT() (n int) { _ = "STUB: not implemented"; return 0 }

func (m *ListAuditLogEntriesResponse_AccessLogEntry) SizeVT() (n int) {
	_ = "STUB: not implemented"
	return 0
}

func (m *ListAuditLogEntriesResponse_DecisionLogEntry) SizeVT() (n int) {
	_ = "STUB: not implemented"
	return 0
}

func (m *ServerInfoResponse) SizeVT() (n int) { _ = "STUB: not implemented"; return 0 }

func (m *ListPoliciesResponse) SizeVT() (n int) { _ = "STUB: not implemented"; return 0 }

func (m *GetPolicyResponse) SizeVT() (n int) { _ = "STUB: not implemented"; return 0 }

func (m *DeletePolicyResponse) SizeVT() (n int) { _ = "STUB: not implemented"; return 0 }

func (m *DeletePolicyErrorDetails) SizeVT() (n int) { _ = "STUB: not implemented"; return 0 }

func (m *DisablePolicyResponse) SizeVT() (n int) { _ = "STUB: not implemented"; return 0 }

func (m *DisablePolicyErrorDetails) SizeVT() (n int) { _ = "STUB: not implemented"; return 0 }

func (m *IntegrityErrors_BreaksScopeChain) SizeVT() (n int) { _ = "STUB: not implemented"; return 0 }

func (m *IntegrityErrors_RequiredByOtherPolicies) SizeVT() (n int) {
	_ = "STUB: not implemented"
	return 0
}

func (m *IntegrityErrors) SizeVT() (n int) { _ = "STUB: not implemented"; return 0 }

func (m *EnablePolicyResponse) SizeVT() (n int) { _ = "STUB: not implemented"; return 0 }

func (m *InspectPoliciesResponse_Attribute) SizeVT() (n int) { _ = "STUB: not implemented"; return 0 }

func (m *InspectPoliciesResponse_DerivedRole) SizeVT() (n int) { _ = "STUB: not implemented"; return 0 }

func (m *InspectPoliciesResponse_Constant) SizeVT() (n int) { _ = "STUB: not implemented"; return 0 }

func (m *InspectPoliciesResponse_Variable) SizeVT() (n int) { _ = "STUB: not implemented"; return 0 }

func (m *InspectPoliciesResponse_Result) SizeVT() (n int) { _ = "STUB: not implemented"; return 0 }

func (m *InspectPoliciesResponse) SizeVT() (n int) { _ = "STUB: not implemented"; return 0 }

func (m *AddOrUpdateSchemaResponse) SizeVT() (n int) { _ = "STUB: not implemented"; return 0 }

func (m *ListSchemasResponse) SizeVT() (n int) { _ = "STUB: not implemented"; return 0 }

func (m *GetSchemaResponse) SizeVT() (n int) { _ = "STUB: not implemented"; return 0 }

func (m *DeleteSchemaResponse) SizeVT() (n int) { _ = "STUB: not implemented"; return 0 }

func (m *ReloadStoreResponse) SizeVT() (n int) { _ = "STUB: not implemented"; return 0 }

func (m *PurgeStoreRevisionsResponse) SizeVT() (n int) { _ = "STUB: not implemented"; return 0 }

func (m *PlanResourcesResponse_Meta) UnmarshalVT(dAtA []byte) error {
	_ = "STUB: not implemented"
	return nil
}

func (m *PlanResourcesResponse) UnmarshalVT(dAtA []byte) error {
	_ = "STUB: not implemented"
	return nil
}

func (m *CheckResourceSetResponse_ActionEffectMap) UnmarshalVT(dAtA []byte) error {
	_ = "STUB: not implemented"
	return nil
}

func (m *CheckResourceSetResponse_Meta_EffectMeta) UnmarshalVT(dAtA []byte) error {
	_ = "STUB: not implemented"
	return nil
}

func (m *CheckResourceSetResponse_Meta_ActionMeta) UnmarshalVT(dAtA []byte) error {
	_ = "STUB: not implemented"
	return nil
}

func (m *CheckResourceSetResponse_Meta) UnmarshalVT(dAtA []byte) error {
	_ = "STUB: not implemented"
	return nil
}

func (m *CheckResourceSetResponse) UnmarshalVT(dAtA []byte) error {
	_ = "STUB: not implemented"
	return nil
}

func (m *CheckResourceBatchResponse_ActionEffectMap) UnmarshalVT(dAtA []byte) error {
	_ = "STUB: not implemented"
	return nil
}

func (m *CheckResourceBatchResponse) UnmarshalVT(dAtA []byte) error {
	_ = "STUB: not implemented"
	return nil
}

func (m *CheckResourcesResponse_ResultEntry_Resource) UnmarshalVT(dAtA []byte) error {
	_ = "STUB: not implemented"
	return nil
}

func (m *CheckResourcesResponse_ResultEntry_Meta_EffectMeta) UnmarshalVT(dAtA []byte) error {
	_ = "STUB: not implemented"
	return nil
}

func (m *CheckResourcesResponse_ResultEntry_Meta) UnmarshalVT(dAtA []byte) error {
	_ = "STUB: not implemented"
	return nil
}

func (m *CheckResourcesResponse_ResultEntry) UnmarshalVT(dAtA []byte) error {
	_ = "STUB: not implemented"
	return nil
}

func (m *CheckResourcesResponse) UnmarshalVT(dAtA []byte) error {
	_ = "STUB: not implemented"
	return nil
}

func (m *PlaygroundFailure_ErrorDetails) UnmarshalVT(dAtA []byte) error {
	_ = "STUB: not implemented"
	return nil
}

func (m *PlaygroundFailure_Error) UnmarshalVT(dAtA []byte) error {
	_ = "STUB: not implemented"
	return nil
}

func (m *PlaygroundFailure) UnmarshalVT(dAtA []byte) error { _ = "STUB: not implemented"; return nil }

func (m *PlaygroundValidateResponse) UnmarshalVT(dAtA []byte) error {
	_ = "STUB: not implemented"
	return nil
}

func (m *PlaygroundTestResponse_TestResults) UnmarshalVT(dAtA []byte) error {
	_ = "STUB: not implemented"
	return nil
}

func (m *PlaygroundTestResponse) UnmarshalVT(dAtA []byte) error {
	_ = "STUB: not implemented"
	return nil
}

func (m *PlaygroundEvaluateResponse_EvalResult) UnmarshalVT(dAtA []byte) error {
	_ = "STUB: not implemented"
	return nil
}

func (m *PlaygroundEvaluateResponse_EvalResultList) UnmarshalVT(dAtA []byte) error {
	_ = "STUB: not implemented"
	return nil
}

func (m *PlaygroundEvaluateResponse) UnmarshalVT(dAtA []byte) error {
	_ = "STUB: not implemented"
	return nil
}

func (m *PlaygroundProxyResponse) UnmarshalVT(dAtA []byte) error {
	_ = "STUB: not implemented"
	return nil
}

func (m *AddOrUpdatePolicyResponse) UnmarshalVT(dAtA []byte) error {
	_ = "STUB: not implemented"
	return nil
}

func (m *ListAuditLogEntriesResponse) UnmarshalVT(dAtA []byte) error {
	_ = "STUB: not implemented"
	return nil
}

func (m *ServerInfoResponse) UnmarshalVT(dAtA []byte) error { _ = "STUB: not implemented"; return nil }

func (m *ListPoliciesResponse) UnmarshalVT(dAtA []byte) error {
	_ = "STUB: not implemented"
	return nil
}

func (m *GetPolicyResponse) UnmarshalVT(dAtA []byte) error { _ = "STUB: not implemented"; return nil }

func (m *DeletePolicyResponse) UnmarshalVT(dAtA []byte) error {
	_ = "STUB: not implemented"
	return nil
}

func (m *DeletePolicyErrorDetails) UnmarshalVT(dAtA []byte) error {
	_ = "STUB: not implemented"
	return nil
}

func (m *DisablePolicyResponse) UnmarshalVT(dAtA []byte) error {
	_ = "STUB: not implemented"
	return nil
}

func (m *DisablePolicyErrorDetails) UnmarshalVT(dAtA []byte) error {
	_ = "STUB: not implemented"
	return nil
}

func (m *IntegrityErrors_BreaksScopeChain) UnmarshalVT(dAtA []byte) error {
	_ = "STUB: not implemented"
	return nil
}

func (m *IntegrityErrors_RequiredByOtherPolicies) UnmarshalVT(dAtA []byte) error {
	_ = "STUB: not implemented"
	return nil
}

func (m *IntegrityErrors) UnmarshalVT(dAtA []byte) error { _ = "STUB: not implemented"; return nil }

func (m *EnablePolicyResponse) UnmarshalVT(dAtA []byte) error {
	_ = "STUB: not implemented"
	return nil
}

func (m *InspectPoliciesResponse_Attribute) UnmarshalVT(dAtA []byte) error {
	_ = "STUB: not implemented"
	return nil
}

func (m *InspectPoliciesResponse_DerivedRole) UnmarshalVT(dAtA []byte) error {
	_ = "STUB: not implemented"
	return nil
}

func (m *InspectPoliciesResponse_Constant) UnmarshalVT(dAtA []byte) error {
	_ = "STUB: not implemented"
	return nil
}

func (m *InspectPoliciesResponse_Variable) UnmarshalVT(dAtA []byte) error {
	_ = "STUB: not implemented"
	return nil
}

func (m *InspectPoliciesResponse_Result) UnmarshalVT(dAtA []byte) error {
	_ = "STUB: not implemented"
	return nil
}

func (m *InspectPoliciesResponse) UnmarshalVT(dAtA []byte) error {
	_ = "STUB: not implemented"
	return nil
}

func (m *AddOrUpdateSchemaResponse) UnmarshalVT(dAtA []byte) error {
	_ = "STUB: not implemented"
	return nil
}

func (m *ListSchemasResponse) UnmarshalVT(dAtA []byte) error { _ = "STUB: not implemented"; return nil }

func (m *GetSchemaResponse) UnmarshalVT(dAtA []byte) error { _ = "STUB: not implemented"; return nil }

func (m *DeleteSchemaResponse) UnmarshalVT(dAtA []byte) error {
	_ = "STUB: not implemented"
	return nil
}

func (m *ReloadStoreResponse) UnmarshalVT(dAtA []byte) error { _ = "STUB: not implemented"; return nil }

func (m *PurgeStoreRevisionsResponse) UnmarshalVT(dAtA []byte) error {
	_ = "STUB: not implemented"
	return nil
}
