// Copyright 2021-2026 Zenauth Ltd.
// SPDX-License-Identifier: Apache-2.0

// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"context"

	"github.com/cerbos/cloud-api/bundle"
	"github.com/cerbos/cloud-api/credentials"
	mock "github.com/stretchr/testify/mock"
)

// NewClientV1 creates a new instance of ClientV1. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewClientV1(t interface {
	mock.TestingT
	Cleanup(func())
}) *ClientV1 {
	_ = "STUB: not implemented"
	return nil
}

// ClientV1 is an autogenerated mock type for the ClientV1 type
type ClientV1 struct {
	mock.Mock
}

type ClientV1_Expecter struct {
	mock *mock.Mock
}

func (_m *ClientV1) EXPECT() *ClientV1_Expecter { _ = "STUB: not implemented"; return nil }

// BootstrapBundle provides a mock function for the type ClientV1
func (_mock *ClientV1) BootstrapBundle(context1 context.Context, s string) (string, error) {
	_ = "STUB: not implemented"
	return "", nil
}

// ClientV1_BootstrapBundle_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'BootstrapBundle'
type ClientV1_BootstrapBundle_Call struct {
	*mock.Call
}

// BootstrapBundle is a helper method to define mock.On call
//   - context1 context.Context
//   - s string
func (_e *ClientV1_Expecter) BootstrapBundle(context1 interface{}, s interface{}) *ClientV1_BootstrapBundle_Call {
	_ = "STUB: not implemented"
	return nil
}

func (_c *ClientV1_BootstrapBundle_Call) Run(run func(context1 context.Context, s string)) *ClientV1_BootstrapBundle_Call {
	_ = "STUB: not implemented"
	return nil
}

func (_c *ClientV1_BootstrapBundle_Call) Return(s1 string, err error) *ClientV1_BootstrapBundle_Call {
	_ = "STUB: not implemented"
	return nil
}

func (_c *ClientV1_BootstrapBundle_Call) RunAndReturn(run func(context1 context.Context, s string) (string, error)) *ClientV1_BootstrapBundle_Call {
	_ = "STUB: not implemented"
	return nil
}

// GetBundle provides a mock function for the type ClientV1
func (_mock *ClientV1) GetBundle(context1 context.Context, s string) (string, error) {
	_ = "STUB: not implemented"
	return "", nil
}

// ClientV1_GetBundle_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetBundle'
type ClientV1_GetBundle_Call struct {
	*mock.Call
}

// GetBundle is a helper method to define mock.On call
//   - context1 context.Context
//   - s string
func (_e *ClientV1_Expecter) GetBundle(context1 interface{}, s interface{}) *ClientV1_GetBundle_Call {
	_ = "STUB: not implemented"
	return nil
}

func (_c *ClientV1_GetBundle_Call) Run(run func(context1 context.Context, s string)) *ClientV1_GetBundle_Call {
	_ = "STUB: not implemented"
	return nil
}

func (_c *ClientV1_GetBundle_Call) Return(s1 string, err error) *ClientV1_GetBundle_Call {
	_ = "STUB: not implemented"
	return nil
}

func (_c *ClientV1_GetBundle_Call) RunAndReturn(run func(context1 context.Context, s string) (string, error)) *ClientV1_GetBundle_Call {
	_ = "STUB: not implemented"
	return nil
}

// GetCachedBundle provides a mock function for the type ClientV1
func (_mock *ClientV1) GetCachedBundle(s string) (string, error) {
	_ = "STUB: not implemented"
	return "", nil
}

// ClientV1_GetCachedBundle_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetCachedBundle'
type ClientV1_GetCachedBundle_Call struct {
	*mock.Call
}

// GetCachedBundle is a helper method to define mock.On call
//   - s string
func (_e *ClientV1_Expecter) GetCachedBundle(s interface{}) *ClientV1_GetCachedBundle_Call {
	_ = "STUB: not implemented"
	return nil
}

func (_c *ClientV1_GetCachedBundle_Call) Run(run func(s string)) *ClientV1_GetCachedBundle_Call {
	_ = "STUB: not implemented"
	return nil
}

func (_c *ClientV1_GetCachedBundle_Call) Return(s1 string, err error) *ClientV1_GetCachedBundle_Call {
	_ = "STUB: not implemented"
	return nil
}

func (_c *ClientV1_GetCachedBundle_Call) RunAndReturn(run func(s string) (string, error)) *ClientV1_GetCachedBundle_Call {
	_ = "STUB: not implemented"
	return nil
}

// HubCredentials provides a mock function for the type ClientV1
func (_mock *ClientV1) HubCredentials() *credentials.Credentials {
	_ = "STUB: not implemented"
	return nil
}

// ClientV1_HubCredentials_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'HubCredentials'
type ClientV1_HubCredentials_Call struct {
	*mock.Call
}

// HubCredentials is a helper method to define mock.On call
func (_e *ClientV1_Expecter) HubCredentials() *ClientV1_HubCredentials_Call {
	_ = "STUB: not implemented"
	return nil
}

func (_c *ClientV1_HubCredentials_Call) Run(run func()) *ClientV1_HubCredentials_Call {
	_ = "STUB: not implemented"
	return nil
}

func (_c *ClientV1_HubCredentials_Call) Return(credentials1 *credentials.Credentials) *ClientV1_HubCredentials_Call {
	_ = "STUB: not implemented"
	return nil
}

func (_c *ClientV1_HubCredentials_Call) RunAndReturn(run func() *credentials.Credentials) *ClientV1_HubCredentials_Call {
	_ = "STUB: not implemented"
	return nil
}

// WatchBundle provides a mock function for the type ClientV1
func (_mock *ClientV1) WatchBundle(context1 context.Context, s string) (bundle.WatchHandle, error) {
	_ = "STUB: not implemented"
	return *new(bundle.WatchHandle), nil
}

// ClientV1_WatchBundle_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'WatchBundle'
type ClientV1_WatchBundle_Call struct {
	*mock.Call
}

// WatchBundle is a helper method to define mock.On call
//   - context1 context.Context
//   - s string
func (_e *ClientV1_Expecter) WatchBundle(context1 interface{}, s interface{}) *ClientV1_WatchBundle_Call {
	_ = "STUB: not implemented"
	return nil
}

func (_c *ClientV1_WatchBundle_Call) Run(run func(context1 context.Context, s string)) *ClientV1_WatchBundle_Call {
	_ = "STUB: not implemented"
	return nil
}

func (_c *ClientV1_WatchBundle_Call) Return(watchHandle bundle.WatchHandle, err error) *ClientV1_WatchBundle_Call {
	_ = "STUB: not implemented"
	return nil
}

func (_c *ClientV1_WatchBundle_Call) RunAndReturn(run func(context1 context.Context, s string) (bundle.WatchHandle, error)) *ClientV1_WatchBundle_Call {
	_ = "STUB: not implemented"
	return nil
}
