// Copyright 2021-2026 Zenauth Ltd.
// SPDX-License-Identifier: Apache-2.0

// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"context"

	"github.com/cerbos/cloud-api/bundle"
	"github.com/cerbos/cloud-api/bundle/v2"
	"github.com/cerbos/cloud-api/genpb/cerbos/cloud/bundle/v2"
	mock "github.com/stretchr/testify/mock"
)

// NewClientV2 creates a new instance of ClientV2. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewClientV2(t interface {
	mock.TestingT
	Cleanup(func())
}) *ClientV2 {
	_ = "STUB: not implemented"
	return nil
}

// ClientV2 is an autogenerated mock type for the ClientV2 type
type ClientV2 struct {
	mock.Mock
}

type ClientV2_Expecter struct {
	mock *mock.Mock
}

func (_m *ClientV2) EXPECT() *ClientV2_Expecter { _ = "STUB: not implemented"; return nil }

// BootstrapBundle provides a mock function for the type ClientV2
func (_mock *ClientV2) BootstrapBundle(context1 context.Context, source v2.Source) (string, bundlev2.BundleType, []byte, error) {
	_ = "STUB: not implemented"
	return "", *new(bundlev2.BundleType), nil, nil
}

// ClientV2_BootstrapBundle_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'BootstrapBundle'
type ClientV2_BootstrapBundle_Call struct {
	*mock.Call
}

// BootstrapBundle is a helper method to define mock.On call
//   - context1 context.Context
//   - source v2.Source
func (_e *ClientV2_Expecter) BootstrapBundle(context1 interface{}, source interface{}) *ClientV2_BootstrapBundle_Call {
	_ = "STUB: not implemented"
	return nil
}

func (_c *ClientV2_BootstrapBundle_Call) Run(run func(context1 context.Context, source v2.Source)) *ClientV2_BootstrapBundle_Call {
	_ = "STUB: not implemented"
	return nil
}

func (_c *ClientV2_BootstrapBundle_Call) Return(s string, bundleType bundlev2.BundleType, bytes []byte, err error) *ClientV2_BootstrapBundle_Call {
	_ = "STUB: not implemented"
	return nil
}

func (_c *ClientV2_BootstrapBundle_Call) RunAndReturn(run func(context1 context.Context, source v2.Source) (string, bundlev2.BundleType, []byte, error)) *ClientV2_BootstrapBundle_Call {
	_ = "STUB: not implemented"
	return nil
}

// GetBundle provides a mock function for the type ClientV2
func (_mock *ClientV2) GetBundle(context1 context.Context, source v2.Source) (string, bundlev2.BundleType, []byte, error) {
	_ = "STUB: not implemented"
	return "", *new(bundlev2.BundleType), nil, nil
}

// ClientV2_GetBundle_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetBundle'
type ClientV2_GetBundle_Call struct {
	*mock.Call
}

// GetBundle is a helper method to define mock.On call
//   - context1 context.Context
//   - source v2.Source
func (_e *ClientV2_Expecter) GetBundle(context1 interface{}, source interface{}) *ClientV2_GetBundle_Call {
	_ = "STUB: not implemented"
	return nil
}

func (_c *ClientV2_GetBundle_Call) Run(run func(context1 context.Context, source v2.Source)) *ClientV2_GetBundle_Call {
	_ = "STUB: not implemented"
	return nil
}

func (_c *ClientV2_GetBundle_Call) Return(s string, bundleType bundlev2.BundleType, bytes []byte, err error) *ClientV2_GetBundle_Call {
	_ = "STUB: not implemented"
	return nil
}

func (_c *ClientV2_GetBundle_Call) RunAndReturn(run func(context1 context.Context, source v2.Source) (string, bundlev2.BundleType, []byte, error)) *ClientV2_GetBundle_Call {
	_ = "STUB: not implemented"
	return nil
}

// GetCachedBundle provides a mock function for the type ClientV2
func (_mock *ClientV2) GetCachedBundle(source v2.Source) (string, error) {
	_ = "STUB: not implemented"
	return "", nil
}

// ClientV2_GetCachedBundle_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetCachedBundle'
type ClientV2_GetCachedBundle_Call struct {
	*mock.Call
}

// GetCachedBundle is a helper method to define mock.On call
//   - source v2.Source
func (_e *ClientV2_Expecter) GetCachedBundle(source interface{}) *ClientV2_GetCachedBundle_Call {
	_ = "STUB: not implemented"
	return nil
}

func (_c *ClientV2_GetCachedBundle_Call) Run(run func(source v2.Source)) *ClientV2_GetCachedBundle_Call {
	_ = "STUB: not implemented"
	return nil
}

func (_c *ClientV2_GetCachedBundle_Call) Return(s string, err error) *ClientV2_GetCachedBundle_Call {
	_ = "STUB: not implemented"
	return nil
}

func (_c *ClientV2_GetCachedBundle_Call) RunAndReturn(run func(source v2.Source) (string, error)) *ClientV2_GetCachedBundle_Call {
	_ = "STUB: not implemented"
	return nil
}

// WatchBundle provides a mock function for the type ClientV2
func (_mock *ClientV2) WatchBundle(context1 context.Context, source v2.Source) (bundle.WatchHandle, error) {
	_ = "STUB: not implemented"
	return *new(bundle.WatchHandle), nil
}

// ClientV2_WatchBundle_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'WatchBundle'
type ClientV2_WatchBundle_Call struct {
	*mock.Call
}

// WatchBundle is a helper method to define mock.On call
//   - context1 context.Context
//   - source v2.Source
func (_e *ClientV2_Expecter) WatchBundle(context1 interface{}, source interface{}) *ClientV2_WatchBundle_Call {
	_ = "STUB: not implemented"
	return nil
}

func (_c *ClientV2_WatchBundle_Call) Run(run func(context1 context.Context, source v2.Source)) *ClientV2_WatchBundle_Call {
	_ = "STUB: not implemented"
	return nil
}

func (_c *ClientV2_WatchBundle_Call) Return(watchHandle bundle.WatchHandle, err error) *ClientV2_WatchBundle_Call {
	_ = "STUB: not implemented"
	return nil
}

func (_c *ClientV2_WatchBundle_Call) RunAndReturn(run func(context1 context.Context, source v2.Source) (bundle.WatchHandle, error)) *ClientV2_WatchBundle_Call {
	_ = "STUB: not implemented"
	return nil
}
