// Copyright 2021-2026 Zenauth Ltd.
// SPDX-License-Identifier: Apache-2.0

// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"context"
	"io"

	"github.com/cerbos/cerbos/internal/namer"
	"github.com/cerbos/cerbos/internal/policy"
	"github.com/cerbos/cerbos/internal/storage"
	"github.com/cerbos/cerbos/internal/storage/index"
	mock "github.com/stretchr/testify/mock"
)

// NewIndex creates a new instance of Index. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewIndex(t interface {
	mock.TestingT
	Cleanup(func())
}) *Index {
	_ = "STUB: not implemented"
	return nil
}

// Index is an autogenerated mock type for the Index type
type Index struct {
	mock.Mock
}

type Index_Expecter struct {
	mock *mock.Mock
}

func (_m *Index) EXPECT() *Index_Expecter { _ = "STUB: not implemented"; return nil }

// AddOrUpdate provides a mock function for the type Index
func (_mock *Index) AddOrUpdate(entry index.Entry) (storage.Event, error) {
	_ = "STUB: not implemented"
	return *new(storage.Event), nil
}

// Index_AddOrUpdate_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'AddOrUpdate'
type Index_AddOrUpdate_Call struct {
	*mock.Call
}

// AddOrUpdate is a helper method to define mock.On call
//   - entry index.Entry
func (_e *Index_Expecter) AddOrUpdate(entry interface{}) *Index_AddOrUpdate_Call {
	_ = "STUB: not implemented"
	return nil
}

func (_c *Index_AddOrUpdate_Call) Run(run func(entry index.Entry)) *Index_AddOrUpdate_Call {
	_ = "STUB: not implemented"
	return nil
}

func (_c *Index_AddOrUpdate_Call) Return(event storage.Event, err error) *Index_AddOrUpdate_Call {
	_ = "STUB: not implemented"
	return nil
}

func (_c *Index_AddOrUpdate_Call) RunAndReturn(run func(entry index.Entry) (storage.Event, error)) *Index_AddOrUpdate_Call {
	_ = "STUB: not implemented"
	return nil
}

// Clear provides a mock function for the type Index
func (_mock *Index) Clear() error { _ = "STUB: not implemented"; return nil }

// Index_Clear_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Clear'
type Index_Clear_Call struct {
	*mock.Call
}

// Clear is a helper method to define mock.On call
func (_e *Index_Expecter) Clear() *Index_Clear_Call { _ = "STUB: not implemented"; return nil }

func (_c *Index_Clear_Call) Run(run func()) *Index_Clear_Call {
	_ = "STUB: not implemented"
	return nil
}

func (_c *Index_Clear_Call) Return(err error) *Index_Clear_Call {
	_ = "STUB: not implemented"
	return nil
}

func (_c *Index_Clear_Call) RunAndReturn(run func() error) *Index_Clear_Call {
	_ = "STUB: not implemented"
	return nil
}

// Close provides a mock function for the type Index
func (_mock *Index) Close() error { _ = "STUB: not implemented"; return nil }

// Index_Close_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Close'
type Index_Close_Call struct {
	*mock.Call
}

// Close is a helper method to define mock.On call
func (_e *Index_Expecter) Close() *Index_Close_Call { _ = "STUB: not implemented"; return nil }

func (_c *Index_Close_Call) Run(run func()) *Index_Close_Call {
	_ = "STUB: not implemented"
	return nil
}

func (_c *Index_Close_Call) Return(err error) *Index_Close_Call {
	_ = "STUB: not implemented"
	return nil
}

func (_c *Index_Close_Call) RunAndReturn(run func() error) *Index_Close_Call {
	_ = "STUB: not implemented"
	return nil
}

// Delete provides a mock function for the type Index
func (_mock *Index) Delete(entry index.Entry) (storage.Event, error) {
	_ = "STUB: not implemented"
	return *new(storage.Event), nil
}

// Index_Delete_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Delete'
type Index_Delete_Call struct {
	*mock.Call
}

// Delete is a helper method to define mock.On call
//   - entry index.Entry
func (_e *Index_Expecter) Delete(entry interface{}) *Index_Delete_Call {
	_ = "STUB: not implemented"
	return nil
}

func (_c *Index_Delete_Call) Run(run func(entry index.Entry)) *Index_Delete_Call {
	_ = "STUB: not implemented"
	return nil
}

func (_c *Index_Delete_Call) Return(event storage.Event, err error) *Index_Delete_Call {
	_ = "STUB: not implemented"
	return nil
}

func (_c *Index_Delete_Call) RunAndReturn(run func(entry index.Entry) (storage.Event, error)) *Index_Delete_Call {
	_ = "STUB: not implemented"
	return nil
}

// GetAll provides a mock function for the type Index
func (_mock *Index) GetAll(context1 context.Context) ([]*policy.CompilationUnit, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

// Index_GetAll_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetAll'
type Index_GetAll_Call struct {
	*mock.Call
}

// GetAll is a helper method to define mock.On call
//   - context1 context.Context
func (_e *Index_Expecter) GetAll(context1 interface{}) *Index_GetAll_Call {
	_ = "STUB: not implemented"
	return nil
}

func (_c *Index_GetAll_Call) Run(run func(context1 context.Context)) *Index_GetAll_Call {
	_ = "STUB: not implemented"
	return nil
}

func (_c *Index_GetAll_Call) Return(compilationUnits []*policy.CompilationUnit, err error) *Index_GetAll_Call {
	_ = "STUB: not implemented"
	return nil
}

func (_c *Index_GetAll_Call) RunAndReturn(run func(context1 context.Context) ([]*policy.CompilationUnit, error)) *Index_GetAll_Call {
	_ = "STUB: not implemented"
	return nil
}

// GetAllCompilationUnits provides a mock function for the type Index
func (_mock *Index) GetAllCompilationUnits(context1 context.Context) <-chan *policy.CompilationUnit {
	_ = "STUB: not implemented"
	return nil
}

// Index_GetAllCompilationUnits_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetAllCompilationUnits'
type Index_GetAllCompilationUnits_Call struct {
	*mock.Call
}

// GetAllCompilationUnits is a helper method to define mock.On call
//   - context1 context.Context
func (_e *Index_Expecter) GetAllCompilationUnits(context1 interface{}) *Index_GetAllCompilationUnits_Call {
	_ = "STUB: not implemented"
	return nil
}

func (_c *Index_GetAllCompilationUnits_Call) Run(run func(context1 context.Context)) *Index_GetAllCompilationUnits_Call {
	_ = "STUB: not implemented"
	return nil
}

func (_c *Index_GetAllCompilationUnits_Call) Return(compilationUnitCh <-chan *policy.CompilationUnit) *Index_GetAllCompilationUnits_Call {
	_ = "STUB: not implemented"
	return nil
}

func (_c *Index_GetAllCompilationUnits_Call) RunAndReturn(run func(context1 context.Context) <-chan *policy.CompilationUnit) *Index_GetAllCompilationUnits_Call {
	_ = "STUB: not implemented"
	return nil
}

// GetAllCompilationUnitsWithCount provides a mock function for the type Index
func (_mock *Index) GetAllCompilationUnitsWithCount(context1 context.Context) (int, <-chan *policy.CompilationUnit) {
	_ = "STUB: not implemented"
	return 0, nil
}

// Index_GetAllCompilationUnitsWithCount_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetAllCompilationUnitsWithCount'
type Index_GetAllCompilationUnitsWithCount_Call struct {
	*mock.Call
}

// GetAllCompilationUnitsWithCount is a helper method to define mock.On call
//   - context1 context.Context
func (_e *Index_Expecter) GetAllCompilationUnitsWithCount(context1 interface{}) *Index_GetAllCompilationUnitsWithCount_Call {
	_ = "STUB: not implemented"
	return nil
}

func (_c *Index_GetAllCompilationUnitsWithCount_Call) Run(run func(context1 context.Context)) *Index_GetAllCompilationUnitsWithCount_Call {
	_ = "STUB: not implemented"
	return nil
}

func (_c *Index_GetAllCompilationUnitsWithCount_Call) Return(n int, compilationUnitCh <-chan *policy.CompilationUnit) *Index_GetAllCompilationUnitsWithCount_Call {
	_ = "STUB: not implemented"
	return nil
}

func (_c *Index_GetAllCompilationUnitsWithCount_Call) RunAndReturn(run func(context1 context.Context) (int, <-chan *policy.CompilationUnit)) *Index_GetAllCompilationUnitsWithCount_Call {
	_ = "STUB: not implemented"
	return nil
}

// GetAllMatching provides a mock function for the type Index
func (_mock *Index) GetAllMatching(moduleIDs []namer.ModuleID) ([]*policy.CompilationUnit, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

// Index_GetAllMatching_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetAllMatching'
type Index_GetAllMatching_Call struct {
	*mock.Call
}

// GetAllMatching is a helper method to define mock.On call
//   - moduleIDs []namer.ModuleID
func (_e *Index_Expecter) GetAllMatching(moduleIDs interface{}) *Index_GetAllMatching_Call {
	_ = "STUB: not implemented"
	return nil
}

func (_c *Index_GetAllMatching_Call) Run(run func(moduleIDs []namer.ModuleID)) *Index_GetAllMatching_Call {
	_ = "STUB: not implemented"
	return nil
}

func (_c *Index_GetAllMatching_Call) Return(compilationUnits []*policy.CompilationUnit, err error) *Index_GetAllMatching_Call {
	_ = "STUB: not implemented"
	return nil
}

func (_c *Index_GetAllMatching_Call) RunAndReturn(run func(moduleIDs []namer.ModuleID) ([]*policy.CompilationUnit, error)) *Index_GetAllMatching_Call {
	_ = "STUB: not implemented"
	return nil
}

// GetCompilationUnits provides a mock function for the type Index
func (_mock *Index) GetCompilationUnits(moduleIDs ...namer.ModuleID) (map[namer.ModuleID]*policy.CompilationUnit, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

// Index_GetCompilationUnits_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetCompilationUnits'
type Index_GetCompilationUnits_Call struct {
	*mock.Call
}

// GetCompilationUnits is a helper method to define mock.On call
//   - moduleIDs ...namer.ModuleID
func (_e *Index_Expecter) GetCompilationUnits(moduleIDs ...interface{}) *Index_GetCompilationUnits_Call {
	_ = "STUB: not implemented"
	return nil
}

func (_c *Index_GetCompilationUnits_Call) Run(run func(moduleIDs ...namer.ModuleID)) *Index_GetCompilationUnits_Call {
	_ = "STUB: not implemented"
	return nil
}

func (_c *Index_GetCompilationUnits_Call) Return(moduleIDToCompilationUnit map[namer.ModuleID]*policy.CompilationUnit, err error) *Index_GetCompilationUnits_Call {
	_ = "STUB: not implemented"
	return nil
}

func (_c *Index_GetCompilationUnits_Call) RunAndReturn(run func(moduleIDs ...namer.ModuleID) (map[namer.ModuleID]*policy.CompilationUnit, error)) *Index_GetCompilationUnits_Call {
	_ = "STUB: not implemented"
	return nil
}

// GetDependents provides a mock function for the type Index
func (_mock *Index) GetDependents(moduleIDs ...namer.ModuleID) (map[namer.ModuleID][]namer.ModuleID, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

// Index_GetDependents_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetDependents'
type Index_GetDependents_Call struct {
	*mock.Call
}

// GetDependents is a helper method to define mock.On call
//   - moduleIDs ...namer.ModuleID
func (_e *Index_Expecter) GetDependents(moduleIDs ...interface{}) *Index_GetDependents_Call {
	_ = "STUB: not implemented"
	return nil
}

func (_c *Index_GetDependents_Call) Run(run func(moduleIDs ...namer.ModuleID)) *Index_GetDependents_Call {
	_ = "STUB: not implemented"
	return nil
}

func (_c *Index_GetDependents_Call) Return(moduleIDToModuleIDs map[namer.ModuleID][]namer.ModuleID, err error) *Index_GetDependents_Call {
	_ = "STUB: not implemented"
	return nil
}

func (_c *Index_GetDependents_Call) RunAndReturn(run func(moduleIDs ...namer.ModuleID) (map[namer.ModuleID][]namer.ModuleID, error)) *Index_GetDependents_Call {
	_ = "STUB: not implemented"
	return nil
}

// GetFiles provides a mock function for the type Index
func (_mock *Index) GetFiles() []string { _ = "STUB: not implemented"; return nil }

// Index_GetFiles_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetFiles'
type Index_GetFiles_Call struct {
	*mock.Call
}

// GetFiles is a helper method to define mock.On call
func (_e *Index_Expecter) GetFiles() *Index_GetFiles_Call { _ = "STUB: not implemented"; return nil }

func (_c *Index_GetFiles_Call) Run(run func()) *Index_GetFiles_Call {
	_ = "STUB: not implemented"
	return nil
}

func (_c *Index_GetFiles_Call) Return(strings []string) *Index_GetFiles_Call {
	_ = "STUB: not implemented"
	return nil
}

func (_c *Index_GetFiles_Call) RunAndReturn(run func() []string) *Index_GetFiles_Call {
	_ = "STUB: not implemented"
	return nil
}

// GetFirstMatch provides a mock function for the type Index
func (_mock *Index) GetFirstMatch(moduleIDs []namer.ModuleID) (*policy.CompilationUnit, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

// Index_GetFirstMatch_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetFirstMatch'
type Index_GetFirstMatch_Call struct {
	*mock.Call
}

// GetFirstMatch is a helper method to define mock.On call
//   - moduleIDs []namer.ModuleID
func (_e *Index_Expecter) GetFirstMatch(moduleIDs interface{}) *Index_GetFirstMatch_Call {
	_ = "STUB: not implemented"
	return nil
}

func (_c *Index_GetFirstMatch_Call) Run(run func(moduleIDs []namer.ModuleID)) *Index_GetFirstMatch_Call {
	_ = "STUB: not implemented"
	return nil
}

func (_c *Index_GetFirstMatch_Call) Return(compilationUnit *policy.CompilationUnit, err error) *Index_GetFirstMatch_Call {
	_ = "STUB: not implemented"
	return nil
}

func (_c *Index_GetFirstMatch_Call) RunAndReturn(run func(moduleIDs []namer.ModuleID) (*policy.CompilationUnit, error)) *Index_GetFirstMatch_Call {
	_ = "STUB: not implemented"
	return nil
}

// InspectPolicies provides a mock function for the type Index
func (_mock *Index) InspectPolicies(context1 context.Context, strings ...string) (map[string]*responsev1.InspectPoliciesResponse_Result, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

// Index_InspectPolicies_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'InspectPolicies'
type Index_InspectPolicies_Call struct {
	*mock.Call
}

// InspectPolicies is a helper method to define mock.On call
//   - context1 context.Context
//   - strings ...string
func (_e *Index_Expecter) InspectPolicies(context1 interface{}, strings ...interface{}) *Index_InspectPolicies_Call {
	_ = "STUB: not implemented"
	return nil
}

func (_c *Index_InspectPolicies_Call) Run(run func(context1 context.Context, strings ...string)) *Index_InspectPolicies_Call {
	_ = "STUB: not implemented"
	return nil
}

func (_c *Index_InspectPolicies_Call) Return(stringToInspectPoliciesResponse_Result map[string]*responsev1.InspectPoliciesResponse_Result, err error) *Index_InspectPolicies_Call {
	_ = "STUB: not implemented"
	return nil
}

func (_c *Index_InspectPolicies_Call) RunAndReturn(run func(context1 context.Context, strings ...string) (map[string]*responsev1.InspectPoliciesResponse_Result, error)) *Index_InspectPolicies_Call {
	_ = "STUB: not implemented"
	return nil
}

// ListPolicyIDs provides a mock function for the type Index
func (_mock *Index) ListPolicyIDs(context1 context.Context, strings ...string) ([]string, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

// Index_ListPolicyIDs_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ListPolicyIDs'
type Index_ListPolicyIDs_Call struct {
	*mock.Call
}

// ListPolicyIDs is a helper method to define mock.On call
//   - context1 context.Context
//   - strings ...string
func (_e *Index_Expecter) ListPolicyIDs(context1 interface{}, strings ...interface{}) *Index_ListPolicyIDs_Call {
	_ = "STUB: not implemented"
	return nil
}

func (_c *Index_ListPolicyIDs_Call) Run(run func(context1 context.Context, strings ...string)) *Index_ListPolicyIDs_Call {
	_ = "STUB: not implemented"
	return nil
}

func (_c *Index_ListPolicyIDs_Call) Return(strings1 []string, err error) *Index_ListPolicyIDs_Call {
	_ = "STUB: not implemented"
	return nil
}

func (_c *Index_ListPolicyIDs_Call) RunAndReturn(run func(context1 context.Context, strings ...string) ([]string, error)) *Index_ListPolicyIDs_Call {
	_ = "STUB: not implemented"
	return nil
}

// ListSchemaIDs provides a mock function for the type Index
func (_mock *Index) ListSchemaIDs(context1 context.Context) ([]string, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

// Index_ListSchemaIDs_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ListSchemaIDs'
type Index_ListSchemaIDs_Call struct {
	*mock.Call
}

// ListSchemaIDs is a helper method to define mock.On call
//   - context1 context.Context
func (_e *Index_Expecter) ListSchemaIDs(context1 interface{}) *Index_ListSchemaIDs_Call {
	_ = "STUB: not implemented"
	return nil
}

func (_c *Index_ListSchemaIDs_Call) Run(run func(context1 context.Context)) *Index_ListSchemaIDs_Call {
	_ = "STUB: not implemented"
	return nil
}

func (_c *Index_ListSchemaIDs_Call) Return(strings []string, err error) *Index_ListSchemaIDs_Call {
	_ = "STUB: not implemented"
	return nil
}

func (_c *Index_ListSchemaIDs_Call) RunAndReturn(run func(context1 context.Context) ([]string, error)) *Index_ListSchemaIDs_Call {
	_ = "STUB: not implemented"
	return nil
}

// LoadPolicy provides a mock function for the type Index
func (_mock *Index) LoadPolicy(context1 context.Context, strings ...string) ([]*policy.Wrapper, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

// Index_LoadPolicy_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'LoadPolicy'
type Index_LoadPolicy_Call struct {
	*mock.Call
}

// LoadPolicy is a helper method to define mock.On call
//   - context1 context.Context
//   - strings ...string
func (_e *Index_Expecter) LoadPolicy(context1 interface{}, strings ...interface{}) *Index_LoadPolicy_Call {
	_ = "STUB: not implemented"
	return nil
}

func (_c *Index_LoadPolicy_Call) Run(run func(context1 context.Context, strings ...string)) *Index_LoadPolicy_Call {
	_ = "STUB: not implemented"
	return nil
}

func (_c *Index_LoadPolicy_Call) Return(wrappers []*policy.Wrapper, err error) *Index_LoadPolicy_Call {
	_ = "STUB: not implemented"
	return nil
}

func (_c *Index_LoadPolicy_Call) RunAndReturn(run func(context1 context.Context, strings ...string) ([]*policy.Wrapper, error)) *Index_LoadPolicy_Call {
	_ = "STUB: not implemented"
	return nil
}

// LoadSchema provides a mock function for the type Index
func (_mock *Index) LoadSchema(context1 context.Context, s string) (io.ReadCloser, error) {
	_ = "STUB: not implemented"
	return *new(io.ReadCloser), nil
}

// Index_LoadSchema_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'LoadSchema'
type Index_LoadSchema_Call struct {
	*mock.Call
}

// LoadSchema is a helper method to define mock.On call
//   - context1 context.Context
//   - s string
func (_e *Index_Expecter) LoadSchema(context1 interface{}, s interface{}) *Index_LoadSchema_Call {
	_ = "STUB: not implemented"
	return nil
}

func (_c *Index_LoadSchema_Call) Run(run func(context1 context.Context, s string)) *Index_LoadSchema_Call {
	_ = "STUB: not implemented"
	return nil
}

func (_c *Index_LoadSchema_Call) Return(readCloser io.ReadCloser, err error) *Index_LoadSchema_Call {
	_ = "STUB: not implemented"
	return nil
}

func (_c *Index_LoadSchema_Call) RunAndReturn(run func(context1 context.Context, s string) (io.ReadCloser, error)) *Index_LoadSchema_Call {
	_ = "STUB: not implemented"
	return nil
}

// Reload provides a mock function for the type Index
func (_mock *Index) Reload(context1 context.Context) ([]storage.Event, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

// Index_Reload_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Reload'
type Index_Reload_Call struct {
	*mock.Call
}

// Reload is a helper method to define mock.On call
//   - context1 context.Context
func (_e *Index_Expecter) Reload(context1 interface{}) *Index_Reload_Call {
	_ = "STUB: not implemented"
	return nil
}

func (_c *Index_Reload_Call) Run(run func(context1 context.Context)) *Index_Reload_Call {
	_ = "STUB: not implemented"
	return nil
}

func (_c *Index_Reload_Call) Return(events []storage.Event, err error) *Index_Reload_Call {
	_ = "STUB: not implemented"
	return nil
}

func (_c *Index_Reload_Call) RunAndReturn(run func(context1 context.Context) ([]storage.Event, error)) *Index_Reload_Call {
	_ = "STUB: not implemented"
	return nil
}

// RepoStats provides a mock function for the type Index
func (_mock *Index) RepoStats(context1 context.Context) storage.RepoStats {
	_ = "STUB: not implemented"
	return *new(storage.RepoStats)
}

// Index_RepoStats_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'RepoStats'
type Index_RepoStats_Call struct {
	*mock.Call
}

// RepoStats is a helper method to define mock.On call
//   - context1 context.Context
func (_e *Index_Expecter) RepoStats(context1 interface{}) *Index_RepoStats_Call {
	_ = "STUB: not implemented"
	return nil
}

func (_c *Index_RepoStats_Call) Run(run func(context1 context.Context)) *Index_RepoStats_Call {
	_ = "STUB: not implemented"
	return nil
}

func (_c *Index_RepoStats_Call) Return(repoStats storage.RepoStats) *Index_RepoStats_Call {
	_ = "STUB: not implemented"
	return nil
}

func (_c *Index_RepoStats_Call) RunAndReturn(run func(context1 context.Context) storage.RepoStats) *Index_RepoStats_Call {
	_ = "STUB: not implemented"
	return nil
}
