// Copyright 2021-2026 Zenauth Ltd.
// SPDX-License-Identifier: Apache-2.0

// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"context"

	mock "github.com/stretchr/testify/mock"
)

// NewIngestSyncer creates a new instance of IngestSyncer. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewIngestSyncer(t interface {
	mock.TestingT
	Cleanup(func())
}) *IngestSyncer {
	_ = "STUB: not implemented"
	return nil
}

// IngestSyncer is an autogenerated mock type for the IngestSyncer type
type IngestSyncer struct {
	mock.Mock
}

type IngestSyncer_Expecter struct {
	mock *mock.Mock
}

func (_m *IngestSyncer) EXPECT() *IngestSyncer_Expecter { _ = "STUB: not implemented"; return nil }

// Sync provides a mock function for the type IngestSyncer
func (_mock *IngestSyncer) Sync(context1 context.Context, ingestBatch *logsv1.IngestBatch) error {
	_ = "STUB: not implemented"
	return nil
}

// IngestSyncer_Sync_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Sync'
type IngestSyncer_Sync_Call struct {
	*mock.Call
}

// Sync is a helper method to define mock.On call
//   - context1 context.Context
//   - ingestBatch *logsv1.IngestBatch
func (_e *IngestSyncer_Expecter) Sync(context1 interface{}, ingestBatch interface{}) *IngestSyncer_Sync_Call {
	_ = "STUB: not implemented"
	return nil
}

func (_c *IngestSyncer_Sync_Call) Run(run func(context1 context.Context, ingestBatch *logsv1.IngestBatch)) *IngestSyncer_Sync_Call {
	_ = "STUB: not implemented"
	return nil
}

func (_c *IngestSyncer_Sync_Call) Return(err error) *IngestSyncer_Sync_Call {
	_ = "STUB: not implemented"
	return nil
}

func (_c *IngestSyncer_Sync_Call) RunAndReturn(run func(context1 context.Context, ingestBatch *logsv1.IngestBatch) error) *IngestSyncer_Sync_Call {
	_ = "STUB: not implemented"
	return nil
}
