// Copyright 2021-2026 Zenauth Ltd.
// SPDX-License-Identifier: Apache-2.0

// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"github.com/cerbos/cloud-api/bundle"
	mock "github.com/stretchr/testify/mock"
)

// NewWatchHandle creates a new instance of WatchHandle. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewWatchHandle(t interface {
	mock.TestingT
	Cleanup(func())
}) *WatchHandle {
	_ = "STUB: not implemented"
	return nil
}

// WatchHandle is an autogenerated mock type for the WatchHandle type
type WatchHandle struct {
	mock.Mock
}

type WatchHandle_Expecter struct {
	mock *mock.Mock
}

func (_m *WatchHandle) EXPECT() *WatchHandle_Expecter { _ = "STUB: not implemented"; return nil }

// ActiveBundleChanged provides a mock function for the type WatchHandle
func (_mock *WatchHandle) ActiveBundleChanged(s string) error {
	_ = "STUB: not implemented"
	return nil
}

// WatchHandle_ActiveBundleChanged_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ActiveBundleChanged'
type WatchHandle_ActiveBundleChanged_Call struct {
	*mock.Call
}

// ActiveBundleChanged is a helper method to define mock.On call
//   - s string
func (_e *WatchHandle_Expecter) ActiveBundleChanged(s interface{}) *WatchHandle_ActiveBundleChanged_Call {
	_ = "STUB: not implemented"
	return nil
}

func (_c *WatchHandle_ActiveBundleChanged_Call) Run(run func(s string)) *WatchHandle_ActiveBundleChanged_Call {
	_ = "STUB: not implemented"
	return nil
}

func (_c *WatchHandle_ActiveBundleChanged_Call) Return(err error) *WatchHandle_ActiveBundleChanged_Call {
	_ = "STUB: not implemented"
	return nil
}

func (_c *WatchHandle_ActiveBundleChanged_Call) RunAndReturn(run func(s string) error) *WatchHandle_ActiveBundleChanged_Call {
	_ = "STUB: not implemented"
	return nil
}

// Errors provides a mock function for the type WatchHandle
func (_mock *WatchHandle) Errors() <-chan error { _ = "STUB: not implemented"; return nil }

// WatchHandle_Errors_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Errors'
type WatchHandle_Errors_Call struct {
	*mock.Call
}

// Errors is a helper method to define mock.On call
func (_e *WatchHandle_Expecter) Errors() *WatchHandle_Errors_Call {
	_ = "STUB: not implemented"
	return nil
}

func (_c *WatchHandle_Errors_Call) Run(run func()) *WatchHandle_Errors_Call {
	_ = "STUB: not implemented"
	return nil
}

func (_c *WatchHandle_Errors_Call) Return(errCh <-chan error) *WatchHandle_Errors_Call {
	_ = "STUB: not implemented"
	return nil
}

func (_c *WatchHandle_Errors_Call) RunAndReturn(run func() <-chan error) *WatchHandle_Errors_Call {
	_ = "STUB: not implemented"
	return nil
}

// ServerEvents provides a mock function for the type WatchHandle
func (_mock *WatchHandle) ServerEvents() <-chan bundle.ServerEvent {
	_ = "STUB: not implemented"
	return nil
}

// WatchHandle_ServerEvents_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ServerEvents'
type WatchHandle_ServerEvents_Call struct {
	*mock.Call
}

// ServerEvents is a helper method to define mock.On call
func (_e *WatchHandle_Expecter) ServerEvents() *WatchHandle_ServerEvents_Call {
	_ = "STUB: not implemented"
	return nil
}

func (_c *WatchHandle_ServerEvents_Call) Run(run func()) *WatchHandle_ServerEvents_Call {
	_ = "STUB: not implemented"
	return nil
}

func (_c *WatchHandle_ServerEvents_Call) Return(serverEventCh <-chan bundle.ServerEvent) *WatchHandle_ServerEvents_Call {
	_ = "STUB: not implemented"
	return nil
}

func (_c *WatchHandle_ServerEvents_Call) RunAndReturn(run func() <-chan bundle.ServerEvent) *WatchHandle_ServerEvents_Call {
	_ = "STUB: not implemented"
	return nil
}
