// Code generated by protoc-gen-go-vtproto. DO NOT EDIT.
// protoc-gen-go-vtproto version: v0.6.1-0.20250313105119-ba97887b0a25
// source: cerbos/engine/v1/engine.proto

package enginev1

import (
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

func (m *PlanResourcesInput_Resource) MarshalVT() (dAtA []byte, err error) {
	_ = "STUB: not implemented"
	return nil, nil
}

func (m *PlanResourcesInput_Resource) MarshalToVT(dAtA []byte) (int, error) {
	_ = "STUB: not implemented"
	return 0, nil
}

func (m *PlanResourcesInput_Resource) MarshalToSizedBufferVT(dAtA []byte) (int, error) {
	_ = "STUB: not implemented"
	return 0, nil
}

func (m *PlanResourcesInput) MarshalVT() (dAtA []byte, err error) {
	_ = "STUB: not implemented"
	return nil, nil
}

func (m *PlanResourcesInput) MarshalToVT(dAtA []byte) (int, error) {
	_ = "STUB: not implemented"
	return 0, nil
}

func (m *PlanResourcesInput) MarshalToSizedBufferVT(dAtA []byte) (int, error) {
	_ = "STUB: not implemented"
	return 0, nil
}

func (m *PlanResourcesAst_Node) MarshalVT() (dAtA []byte, err error) {
	_ = "STUB: not implemented"
	return nil, nil
}

func (m *PlanResourcesAst_Node) MarshalToVT(dAtA []byte) (int, error) {
	_ = "STUB: not implemented"
	return 0, nil
}

func (m *PlanResourcesAst_Node) MarshalToSizedBufferVT(dAtA []byte) (int, error) {
	_ = "STUB: not implemented"
	return 0, nil
}

func (m *PlanResourcesAst_Node_LogicalOperation) MarshalToVT(dAtA []byte) (int, error) {
	_ = "STUB: not implemented"
	return 0, nil
}

func (m *PlanResourcesAst_Node_LogicalOperation) MarshalToSizedBufferVT(dAtA []byte) (int, error) {
	_ = "STUB: not implemented"
	return 0, nil
}

func (m *PlanResourcesAst_Node_Expression) MarshalToVT(dAtA []byte) (int, error) {
	_ = "STUB: not implemented"
	return 0, nil
}

func (m *PlanResourcesAst_Node_Expression) MarshalToSizedBufferVT(dAtA []byte) (int, error) {
	_ = "STUB: not implemented"
	return 0, nil
}

func (m *PlanResourcesAst_LogicalOperation) MarshalVT() (dAtA []byte, err error) {
	_ = "STUB: not implemented"
	return nil, nil
}

func (m *PlanResourcesAst_LogicalOperation) MarshalToVT(dAtA []byte) (int, error) {
	_ = "STUB: not implemented"
	return 0, nil
}

func (m *PlanResourcesAst_LogicalOperation) MarshalToSizedBufferVT(dAtA []byte) (int, error) {
	_ = "STUB: not implemented"
	return 0, nil
}

func (m *PlanResourcesAst) MarshalVT() (dAtA []byte, err error) {
	_ = "STUB: not implemented"
	return nil, nil
}

func (m *PlanResourcesAst) MarshalToVT(dAtA []byte) (int, error) {
	_ = "STUB: not implemented"
	return 0, nil
}

func (m *PlanResourcesAst) MarshalToSizedBufferVT(dAtA []byte) (int, error) {
	_ = "STUB: not implemented"
	return 0, nil
}

func (m *PlanResourcesFilter_Expression_Operand) MarshalVT() (dAtA []byte, err error) {
	_ = "STUB: not implemented"
	return nil, nil
}

func (m *PlanResourcesFilter_Expression_Operand) MarshalToVT(dAtA []byte) (int, error) {
	_ = "STUB: not implemented"
	return 0, nil
}

func (m *PlanResourcesFilter_Expression_Operand) MarshalToSizedBufferVT(dAtA []byte) (int, error) {
	_ = "STUB: not implemented"
	return 0, nil
}

func (m *PlanResourcesFilter_Expression_Operand_Value) MarshalToVT(dAtA []byte) (int, error) {
	_ = "STUB: not implemented"
	return 0, nil
}

func (m *PlanResourcesFilter_Expression_Operand_Value) MarshalToSizedBufferVT(dAtA []byte) (int, error) {
	_ = "STUB: not implemented"
	return 0, nil
}

func (m *PlanResourcesFilter_Expression_Operand_Expression) MarshalToVT(dAtA []byte) (int, error) {
	_ = "STUB: not implemented"
	return 0, nil
}

func (m *PlanResourcesFilter_Expression_Operand_Expression) MarshalToSizedBufferVT(dAtA []byte) (int, error) {
	_ = "STUB: not implemented"
	return 0, nil
}

func (m *PlanResourcesFilter_Expression_Operand_Variable) MarshalToVT(dAtA []byte) (int, error) {
	_ = "STUB: not implemented"
	return 0, nil
}

func (m *PlanResourcesFilter_Expression_Operand_Variable) MarshalToSizedBufferVT(dAtA []byte) (int, error) {
	_ = "STUB: not implemented"
	return 0, nil
}

func (m *PlanResourcesFilter_Expression) MarshalVT() (dAtA []byte, err error) {
	_ = "STUB: not implemented"
	return nil, nil
}

func (m *PlanResourcesFilter_Expression) MarshalToVT(dAtA []byte) (int, error) {
	_ = "STUB: not implemented"
	return 0, nil
}

func (m *PlanResourcesFilter_Expression) MarshalToSizedBufferVT(dAtA []byte) (int, error) {
	_ = "STUB: not implemented"
	return 0, nil
}

func (m *PlanResourcesFilter) MarshalVT() (dAtA []byte, err error) {
	_ = "STUB: not implemented"
	return nil, nil
}

func (m *PlanResourcesFilter) MarshalToVT(dAtA []byte) (int, error) {
	_ = "STUB: not implemented"
	return 0, nil
}

func (m *PlanResourcesFilter) MarshalToSizedBufferVT(dAtA []byte) (int, error) {
	_ = "STUB: not implemented"
	return 0, nil
}

func (m *PlanResourcesOutput) MarshalVT() (dAtA []byte, err error) {
	_ = "STUB: not implemented"
	return nil, nil
}

func (m *PlanResourcesOutput) MarshalToVT(dAtA []byte) (int, error) {
	_ = "STUB: not implemented"
	return 0, nil
}

func (m *PlanResourcesOutput) MarshalToSizedBufferVT(dAtA []byte) (int, error) {
	_ = "STUB: not implemented"
	return 0, nil
}

func (m *CheckInput) MarshalVT() (dAtA []byte, err error) {
	_ = "STUB: not implemented"
	return nil, nil
}

func (m *CheckInput) MarshalToVT(dAtA []byte) (int, error) {
	_ = "STUB: not implemented"
	return 0, nil
}

func (m *CheckInput) MarshalToSizedBufferVT(dAtA []byte) (int, error) {
	_ = "STUB: not implemented"
	return 0, nil
}

func (m *CheckOutput_ActionEffect) MarshalVT() (dAtA []byte, err error) {
	_ = "STUB: not implemented"
	return nil, nil
}

func (m *CheckOutput_ActionEffect) MarshalToVT(dAtA []byte) (int, error) {
	_ = "STUB: not implemented"
	return 0, nil
}

func (m *CheckOutput_ActionEffect) MarshalToSizedBufferVT(dAtA []byte) (int, error) {
	_ = "STUB: not implemented"
	return 0, nil
}

func (m *CheckOutput) MarshalVT() (dAtA []byte, err error) {
	_ = "STUB: not implemented"
	return nil, nil
}

func (m *CheckOutput) MarshalToVT(dAtA []byte) (int, error) {
	_ = "STUB: not implemented"
	return 0, nil
}

func (m *CheckOutput) MarshalToSizedBufferVT(dAtA []byte) (int, error) {
	_ = "STUB: not implemented"
	return 0, nil
}

func (m *OutputEntry) MarshalVT() (dAtA []byte, err error) {
	_ = "STUB: not implemented"
	return nil, nil
}

func (m *OutputEntry) MarshalToVT(dAtA []byte) (int, error) {
	_ = "STUB: not implemented"
	return 0, nil
}

func (m *OutputEntry) MarshalToSizedBufferVT(dAtA []byte) (int, error) {
	_ = "STUB: not implemented"
	return 0, nil
}

func (m *Resource) MarshalVT() (dAtA []byte, err error) { _ = "STUB: not implemented"; return nil, nil }

func (m *Resource) MarshalToVT(dAtA []byte) (int, error) { _ = "STUB: not implemented"; return 0, nil }

func (m *Resource) MarshalToSizedBufferVT(dAtA []byte) (int, error) {
	_ = "STUB: not implemented"
	return 0, nil
}

func (m *Principal) MarshalVT() (dAtA []byte, err error) {
	_ = "STUB: not implemented"
	return nil, nil
}

func (m *Principal) MarshalToVT(dAtA []byte) (int, error) { _ = "STUB: not implemented"; return 0, nil }

func (m *Principal) MarshalToSizedBufferVT(dAtA []byte) (int, error) {
	_ = "STUB: not implemented"
	return 0, nil
}

func (m *AuxData) MarshalVT() (dAtA []byte, err error) { _ = "STUB: not implemented"; return nil, nil }

func (m *AuxData) MarshalToVT(dAtA []byte) (int, error) { _ = "STUB: not implemented"; return 0, nil }

func (m *AuxData) MarshalToSizedBufferVT(dAtA []byte) (int, error) {
	_ = "STUB: not implemented"
	return 0, nil
}

func (m *Trace_Component_Variable) MarshalVT() (dAtA []byte, err error) {
	_ = "STUB: not implemented"
	return nil, nil
}

func (m *Trace_Component_Variable) MarshalToVT(dAtA []byte) (int, error) {
	_ = "STUB: not implemented"
	return 0, nil
}

func (m *Trace_Component_Variable) MarshalToSizedBufferVT(dAtA []byte) (int, error) {
	_ = "STUB: not implemented"
	return 0, nil
}

func (m *Trace_Component) MarshalVT() (dAtA []byte, err error) {
	_ = "STUB: not implemented"
	return nil, nil
}

func (m *Trace_Component) MarshalToVT(dAtA []byte) (int, error) {
	_ = "STUB: not implemented"
	return 0, nil
}

func (m *Trace_Component) MarshalToSizedBufferVT(dAtA []byte) (int, error) {
	_ = "STUB: not implemented"
	return 0, nil
}

func (m *Trace_Component_Action) MarshalToVT(dAtA []byte) (int, error) {
	_ = "STUB: not implemented"
	return 0, nil
}

func (m *Trace_Component_Action) MarshalToSizedBufferVT(dAtA []byte) (int, error) {
	_ = "STUB: not implemented"
	return 0, nil
}

func (m *Trace_Component_DerivedRole) MarshalToVT(dAtA []byte) (int, error) {
	_ = "STUB: not implemented"
	return 0, nil
}

func (m *Trace_Component_DerivedRole) MarshalToSizedBufferVT(dAtA []byte) (int, error) {
	_ = "STUB: not implemented"
	return 0, nil
}

func (m *Trace_Component_Expr) MarshalToVT(dAtA []byte) (int, error) {
	_ = "STUB: not implemented"
	return 0, nil
}

func (m *Trace_Component_Expr) MarshalToSizedBufferVT(dAtA []byte) (int, error) {
	_ = "STUB: not implemented"
	return 0, nil
}

func (m *Trace_Component_Index) MarshalToVT(dAtA []byte) (int, error) {
	_ = "STUB: not implemented"
	return 0, nil
}

func (m *Trace_Component_Index) MarshalToSizedBufferVT(dAtA []byte) (int, error) {
	_ = "STUB: not implemented"
	return 0, nil
}

func (m *Trace_Component_Policy) MarshalToVT(dAtA []byte) (int, error) {
	_ = "STUB: not implemented"
	return 0, nil
}

func (m *Trace_Component_Policy) MarshalToSizedBufferVT(dAtA []byte) (int, error) {
	_ = "STUB: not implemented"
	return 0, nil
}

func (m *Trace_Component_Resource) MarshalToVT(dAtA []byte) (int, error) {
	_ = "STUB: not implemented"
	return 0, nil
}

func (m *Trace_Component_Resource) MarshalToSizedBufferVT(dAtA []byte) (int, error) {
	_ = "STUB: not implemented"
	return 0, nil
}

func (m *Trace_Component_Rule) MarshalToVT(dAtA []byte) (int, error) {
	_ = "STUB: not implemented"
	return 0, nil
}

func (m *Trace_Component_Rule) MarshalToSizedBufferVT(dAtA []byte) (int, error) {
	_ = "STUB: not implemented"
	return 0, nil
}

func (m *Trace_Component_Scope) MarshalToVT(dAtA []byte) (int, error) {
	_ = "STUB: not implemented"
	return 0, nil
}

func (m *Trace_Component_Scope) MarshalToSizedBufferVT(dAtA []byte) (int, error) {
	_ = "STUB: not implemented"
	return 0, nil
}

func (m *Trace_Component_Variable_) MarshalToVT(dAtA []byte) (int, error) {
	_ = "STUB: not implemented"
	return 0, nil
}

func (m *Trace_Component_Variable_) MarshalToSizedBufferVT(dAtA []byte) (int, error) {
	_ = "STUB: not implemented"
	return 0, nil
}

func (m *Trace_Component_Output) MarshalToVT(dAtA []byte) (int, error) {
	_ = "STUB: not implemented"
	return 0, nil
}

func (m *Trace_Component_Output) MarshalToSizedBufferVT(dAtA []byte) (int, error) {
	_ = "STUB: not implemented"
	return 0, nil
}

func (m *Trace_Component_RolePolicyScope) MarshalToVT(dAtA []byte) (int, error) {
	_ = "STUB: not implemented"
	return 0, nil
}

func (m *Trace_Component_RolePolicyScope) MarshalToSizedBufferVT(dAtA []byte) (int, error) {
	_ = "STUB: not implemented"
	return 0, nil
}

func (m *Trace_Component_Role) MarshalToVT(dAtA []byte) (int, error) {
	_ = "STUB: not implemented"
	return 0, nil
}

func (m *Trace_Component_Role) MarshalToSizedBufferVT(dAtA []byte) (int, error) {
	_ = "STUB: not implemented"
	return 0, nil
}

func (m *Trace_Event) MarshalVT() (dAtA []byte, err error) {
	_ = "STUB: not implemented"
	return nil, nil
}

func (m *Trace_Event) MarshalToVT(dAtA []byte) (int, error) {
	_ = "STUB: not implemented"
	return 0, nil
}

func (m *Trace_Event) MarshalToSizedBufferVT(dAtA []byte) (int, error) {
	_ = "STUB: not implemented"
	return 0, nil
}

func (m *Trace) MarshalVT() (dAtA []byte, err error) { _ = "STUB: not implemented"; return nil, nil }

func (m *Trace) MarshalToVT(dAtA []byte) (int, error) { _ = "STUB: not implemented"; return 0, nil }

func (m *Trace) MarshalToSizedBufferVT(dAtA []byte) (int, error) {
	_ = "STUB: not implemented"
	return 0, nil
}

func (m *TraceEntry) MarshalVT() (dAtA []byte, err error) {
	_ = "STUB: not implemented"
	return nil, nil
}

func (m *TraceEntry) MarshalToVT(dAtA []byte) (int, error) {
	_ = "STUB: not implemented"
	return 0, nil
}

func (m *TraceEntry) MarshalToSizedBufferVT(dAtA []byte) (int, error) {
	_ = "STUB: not implemented"
	return 0, nil
}

func (m *TraceBatch) MarshalVT() (dAtA []byte, err error) {
	_ = "STUB: not implemented"
	return nil, nil
}

func (m *TraceBatch) MarshalToVT(dAtA []byte) (int, error) {
	_ = "STUB: not implemented"
	return 0, nil
}

func (m *TraceBatch) MarshalToSizedBufferVT(dAtA []byte) (int, error) {
	_ = "STUB: not implemented"
	return 0, nil
}

func (m *Request_Principal) MarshalVT() (dAtA []byte, err error) {
	_ = "STUB: not implemented"
	return nil, nil
}

func (m *Request_Principal) MarshalToVT(dAtA []byte) (int, error) {
	_ = "STUB: not implemented"
	return 0, nil
}

func (m *Request_Principal) MarshalToSizedBufferVT(dAtA []byte) (int, error) {
	_ = "STUB: not implemented"
	return 0, nil
}

func (m *Request_Resource) MarshalVT() (dAtA []byte, err error) {
	_ = "STUB: not implemented"
	return nil, nil
}

func (m *Request_Resource) MarshalToVT(dAtA []byte) (int, error) {
	_ = "STUB: not implemented"
	return 0, nil
}

func (m *Request_Resource) MarshalToSizedBufferVT(dAtA []byte) (int, error) {
	_ = "STUB: not implemented"
	return 0, nil
}

func (m *Request) MarshalVT() (dAtA []byte, err error) { _ = "STUB: not implemented"; return nil, nil }

func (m *Request) MarshalToVT(dAtA []byte) (int, error) { _ = "STUB: not implemented"; return 0, nil }

func (m *Request) MarshalToSizedBufferVT(dAtA []byte) (int, error) {
	_ = "STUB: not implemented"
	return 0, nil
}

func (m *Runtime) MarshalVT() (dAtA []byte, err error) { _ = "STUB: not implemented"; return nil, nil }

func (m *Runtime) MarshalToVT(dAtA []byte) (int, error) { _ = "STUB: not implemented"; return 0, nil }

func (m *Runtime) MarshalToSizedBufferVT(dAtA []byte) (int, error) {
	_ = "STUB: not implemented"
	return 0, nil
}

func (m *PlanResourcesInput_Resource) SizeVT() (n int) { _ = "STUB: not implemented"; return 0 }

func (m *PlanResourcesInput) SizeVT() (n int) { _ = "STUB: not implemented"; return 0 }

func (m *PlanResourcesAst_Node) SizeVT() (n int) { _ = "STUB: not implemented"; return 0 }

func (m *PlanResourcesAst_Node_LogicalOperation) SizeVT() (n int) {
	_ = "STUB: not implemented"
	return 0
}

func (m *PlanResourcesAst_Node_Expression) SizeVT() (n int) { _ = "STUB: not implemented"; return 0 }

func (m *PlanResourcesAst_LogicalOperation) SizeVT() (n int) { _ = "STUB: not implemented"; return 0 }

func (m *PlanResourcesAst) SizeVT() (n int) { _ = "STUB: not implemented"; return 0 }

func (m *PlanResourcesFilter_Expression_Operand) SizeVT() (n int) {
	_ = "STUB: not implemented"
	return 0
}

func (m *PlanResourcesFilter_Expression_Operand_Value) SizeVT() (n int) {
	_ = "STUB: not implemented"
	return 0
}

func (m *PlanResourcesFilter_Expression_Operand_Expression) SizeVT() (n int) {
	_ = "STUB: not implemented"
	return 0
}

func (m *PlanResourcesFilter_Expression_Operand_Variable) SizeVT() (n int) {
	_ = "STUB: not implemented"
	return 0
}

func (m *PlanResourcesFilter_Expression) SizeVT() (n int) { _ = "STUB: not implemented"; return 0 }

func (m *PlanResourcesFilter) SizeVT() (n int) { _ = "STUB: not implemented"; return 0 }

func (m *PlanResourcesOutput) SizeVT() (n int) { _ = "STUB: not implemented"; return 0 }

func (m *CheckInput) SizeVT() (n int) { _ = "STUB: not implemented"; return 0 }

func (m *CheckOutput_ActionEffect) SizeVT() (n int) { _ = "STUB: not implemented"; return 0 }

func (m *CheckOutput) SizeVT() (n int) { _ = "STUB: not implemented"; return 0 }

func (m *OutputEntry) SizeVT() (n int) { _ = "STUB: not implemented"; return 0 }

func (m *Resource) SizeVT() (n int) { _ = "STUB: not implemented"; return 0 }

func (m *Principal) SizeVT() (n int) { _ = "STUB: not implemented"; return 0 }

func (m *AuxData) SizeVT() (n int) { _ = "STUB: not implemented"; return 0 }

func (m *Trace_Component_Variable) SizeVT() (n int) { _ = "STUB: not implemented"; return 0 }

func (m *Trace_Component) SizeVT() (n int) { _ = "STUB: not implemented"; return 0 }

func (m *Trace_Component_Action) SizeVT() (n int) { _ = "STUB: not implemented"; return 0 }

func (m *Trace_Component_DerivedRole) SizeVT() (n int) { _ = "STUB: not implemented"; return 0 }

func (m *Trace_Component_Expr) SizeVT() (n int) { _ = "STUB: not implemented"; return 0 }

func (m *Trace_Component_Index) SizeVT() (n int) { _ = "STUB: not implemented"; return 0 }

func (m *Trace_Component_Policy) SizeVT() (n int) { _ = "STUB: not implemented"; return 0 }

func (m *Trace_Component_Resource) SizeVT() (n int) { _ = "STUB: not implemented"; return 0 }

func (m *Trace_Component_Rule) SizeVT() (n int) { _ = "STUB: not implemented"; return 0 }

func (m *Trace_Component_Scope) SizeVT() (n int) { _ = "STUB: not implemented"; return 0 }

func (m *Trace_Component_Variable_) SizeVT() (n int) { _ = "STUB: not implemented"; return 0 }

func (m *Trace_Component_Output) SizeVT() (n int) { _ = "STUB: not implemented"; return 0 }

func (m *Trace_Component_RolePolicyScope) SizeVT() (n int) { _ = "STUB: not implemented"; return 0 }

func (m *Trace_Component_Role) SizeVT() (n int) { _ = "STUB: not implemented"; return 0 }

func (m *Trace_Event) SizeVT() (n int) { _ = "STUB: not implemented"; return 0 }

func (m *Trace) SizeVT() (n int) { _ = "STUB: not implemented"; return 0 }

func (m *TraceEntry) SizeVT() (n int) { _ = "STUB: not implemented"; return 0 }

func (m *TraceBatch) SizeVT() (n int) { _ = "STUB: not implemented"; return 0 }

func (m *Request_Principal) SizeVT() (n int) { _ = "STUB: not implemented"; return 0 }

func (m *Request_Resource) SizeVT() (n int) { _ = "STUB: not implemented"; return 0 }

func (m *Request) SizeVT() (n int) { _ = "STUB: not implemented"; return 0 }

func (m *Runtime) SizeVT() (n int) { _ = "STUB: not implemented"; return 0 }

func (m *PlanResourcesInput_Resource) UnmarshalVT(dAtA []byte) error {
	_ = "STUB: not implemented"
	return nil
}

func (m *PlanResourcesInput) UnmarshalVT(dAtA []byte) error { _ = "STUB: not implemented"; return nil }

func (m *PlanResourcesAst_Node) UnmarshalVT(dAtA []byte) error {
	_ = "STUB: not implemented"
	return nil
}

func (m *PlanResourcesAst_LogicalOperation) UnmarshalVT(dAtA []byte) error {
	_ = "STUB: not implemented"
	return nil
}

func (m *PlanResourcesAst) UnmarshalVT(dAtA []byte) error { _ = "STUB: not implemented"; return nil }

func (m *PlanResourcesFilter_Expression_Operand) UnmarshalVT(dAtA []byte) error {
	_ = "STUB: not implemented"
	return nil
}

func (m *PlanResourcesFilter_Expression) UnmarshalVT(dAtA []byte) error {
	_ = "STUB: not implemented"
	return nil
}

func (m *PlanResourcesFilter) UnmarshalVT(dAtA []byte) error { _ = "STUB: not implemented"; return nil }

func (m *PlanResourcesOutput) UnmarshalVT(dAtA []byte) error { _ = "STUB: not implemented"; return nil }

func (m *CheckInput) UnmarshalVT(dAtA []byte) error { _ = "STUB: not implemented"; return nil }

func (m *CheckOutput_ActionEffect) UnmarshalVT(dAtA []byte) error {
	_ = "STUB: not implemented"
	return nil
}

func (m *CheckOutput) UnmarshalVT(dAtA []byte) error { _ = "STUB: not implemented"; return nil }

func (m *OutputEntry) UnmarshalVT(dAtA []byte) error { _ = "STUB: not implemented"; return nil }

func (m *Resource) UnmarshalVT(dAtA []byte) error { _ = "STUB: not implemented"; return nil }

func (m *Principal) UnmarshalVT(dAtA []byte) error { _ = "STUB: not implemented"; return nil }

func (m *AuxData) UnmarshalVT(dAtA []byte) error { _ = "STUB: not implemented"; return nil }

func (m *Trace_Component_Variable) UnmarshalVT(dAtA []byte) error {
	_ = "STUB: not implemented"
	return nil
}

func (m *Trace_Component) UnmarshalVT(dAtA []byte) error { _ = "STUB: not implemented"; return nil }

func (m *Trace_Event) UnmarshalVT(dAtA []byte) error { _ = "STUB: not implemented"; return nil }

func (m *Trace) UnmarshalVT(dAtA []byte) error { _ = "STUB: not implemented"; return nil }

func (m *TraceEntry) UnmarshalVT(dAtA []byte) error { _ = "STUB: not implemented"; return nil }

func (m *TraceBatch) UnmarshalVT(dAtA []byte) error { _ = "STUB: not implemented"; return nil }

func (m *Request_Principal) UnmarshalVT(dAtA []byte) error { _ = "STUB: not implemented"; return nil }

func (m *Request_Resource) UnmarshalVT(dAtA []byte) error { _ = "STUB: not implemented"; return nil }

func (m *Request) UnmarshalVT(dAtA []byte) error { _ = "STUB: not implemented"; return nil }

func (m *Runtime) UnmarshalVT(dAtA []byte) error { _ = "STUB: not implemented"; return nil }
