// Code generated by protoc-gen-go-hashpb. DO NOT EDIT.
// protoc-gen-go-hashpb v0.5.0
// Source: cerbos/audit/v1/audit.proto

package auditv1

import (
	hash "hash"
)

// HashPB computes a hash of the message using the given hash function
// The ignore set must contain fully-qualified field names (pkg.msg.field) that should be ignored from the hash
func (m *AccessLogEntry) HashPB(hasher hash.Hash, ignore map[string]struct{}) {
	_ = "STUB: not implemented"
	return
}

// HashPB computes a hash of the message using the given hash function
// The ignore set must contain fully-qualified field names (pkg.msg.field) that should be ignored from the hash
func (m *DecisionLogEntry) HashPB(hasher hash.Hash, ignore map[string]struct{}) {
	_ = "STUB: not implemented"
	return
}

// HashPB computes a hash of the message using the given hash function
// The ignore set must contain fully-qualified field names (pkg.msg.field) that should be ignored from the hash
func (m *DecisionLogEntry_CheckResources) HashPB(hasher hash.Hash, ignore map[string]struct{}) {
	_ = "STUB: not implemented"
	return
}

// HashPB computes a hash of the message using the given hash function
// The ignore set must contain fully-qualified field names (pkg.msg.field) that should be ignored from the hash
func (m *DecisionLogEntry_PlanResources) HashPB(hasher hash.Hash, ignore map[string]struct{}) {
	_ = "STUB: not implemented"
	return
}

// HashPB computes a hash of the message using the given hash function
// The ignore set must contain fully-qualified field names (pkg.msg.field) that should be ignored from the hash
func (m *MetaValues) HashPB(hasher hash.Hash, ignore map[string]struct{}) {
	_ = "STUB: not implemented"
	return
}

// HashPB computes a hash of the message using the given hash function
// The ignore set must contain fully-qualified field names (pkg.msg.field) that should be ignored from the hash
func (m *Peer) HashPB(hasher hash.Hash, ignore map[string]struct{}) {
	_ = "STUB: not implemented"
	return
}

// HashPB computes a hash of the message using the given hash function
// The ignore set must contain fully-qualified field names (pkg.msg.field) that should be ignored from the hash
func (m *AuditTrail) HashPB(hasher hash.Hash, ignore map[string]struct{}) {
	_ = "STUB: not implemented"
	return
}

// HashPB computes a hash of the message using the given hash function
// The ignore set must contain fully-qualified field names (pkg.msg.field) that should be ignored from the hash
func (m *PolicySource) HashPB(hasher hash.Hash, ignore map[string]struct{}) {
	_ = "STUB: not implemented"
	return
}

// HashPB computes a hash of the message using the given hash function
// The ignore set must contain fully-qualified field names (pkg.msg.field) that should be ignored from the hash
func (m *PolicySource_Blob) HashPB(hasher hash.Hash, ignore map[string]struct{}) {
	_ = "STUB: not implemented"
	return
}

// HashPB computes a hash of the message using the given hash function
// The ignore set must contain fully-qualified field names (pkg.msg.field) that should be ignored from the hash
func (m *PolicySource_Database) HashPB(hasher hash.Hash, ignore map[string]struct{}) {
	_ = "STUB: not implemented"
	return
}

// HashPB computes a hash of the message using the given hash function
// The ignore set must contain fully-qualified field names (pkg.msg.field) that should be ignored from the hash
func (m *PolicySource_Disk) HashPB(hasher hash.Hash, ignore map[string]struct{}) {
	_ = "STUB: not implemented"
	return
}

// HashPB computes a hash of the message using the given hash function
// The ignore set must contain fully-qualified field names (pkg.msg.field) that should be ignored from the hash
func (m *PolicySource_EmbeddedPDP) HashPB(hasher hash.Hash, ignore map[string]struct{}) {
	_ = "STUB: not implemented"
	return
}

// HashPB computes a hash of the message using the given hash function
// The ignore set must contain fully-qualified field names (pkg.msg.field) that should be ignored from the hash
func (m *PolicySource_Git) HashPB(hasher hash.Hash, ignore map[string]struct{}) {
	_ = "STUB: not implemented"
	return
}

// HashPB computes a hash of the message using the given hash function
// The ignore set must contain fully-qualified field names (pkg.msg.field) that should be ignored from the hash
func (m *PolicySource_Hub) HashPB(hasher hash.Hash, ignore map[string]struct{}) {
	_ = "STUB: not implemented"
	return
}

// HashPB computes a hash of the message using the given hash function
// The ignore set must contain fully-qualified field names (pkg.msg.field) that should be ignored from the hash
func (m *PolicySource_Hub_EmbeddedBundle) HashPB(hasher hash.Hash, ignore map[string]struct{}) {
	_ = "STUB: not implemented"
	return
}

// HashPB computes a hash of the message using the given hash function
// The ignore set must contain fully-qualified field names (pkg.msg.field) that should be ignored from the hash
func (m *PolicySource_Hub_LocalBundle) HashPB(hasher hash.Hash, ignore map[string]struct{}) {
	_ = "STUB: not implemented"
	return
}

// HashPB computes a hash of the message using the given hash function
// The ignore set must contain fully-qualified field names (pkg.msg.field) that should be ignored from the hash
func (m *PolicySource_Hub_RemoteBundle) HashPB(hasher hash.Hash, ignore map[string]struct{}) {
	_ = "STUB: not implemented"
	return
}

// HashPB computes a hash of the message using the given hash function
// The ignore set must contain fully-qualified field names (pkg.msg.field) that should be ignored from the hash
func (m *RequestContext) HashPB(hasher hash.Hash, ignore map[string]struct{}) {
	_ = "STUB: not implemented"
	return
}
