// Code generated by protoc-gen-go-vtproto. DO NOT EDIT.
// protoc-gen-go-vtproto version: v0.6.1-0.20250313105119-ba97887b0a25
// source: cerbos/audit/v1/audit.proto

package auditv1

import (
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

func (m *AccessLogEntry) MarshalVT() (dAtA []byte, err error) {
	_ = "STUB: not implemented"
	return nil, nil
}

func (m *AccessLogEntry) MarshalToVT(dAtA []byte) (int, error) {
	_ = "STUB: not implemented"
	return 0, nil
}

func (m *AccessLogEntry) MarshalToSizedBufferVT(dAtA []byte) (int, error) {
	_ = "STUB: not implemented"
	return 0, nil
}

func (m *DecisionLogEntry_CheckResources) MarshalVT() (dAtA []byte, err error) {
	_ = "STUB: not implemented"
	return nil, nil
}

func (m *DecisionLogEntry_CheckResources) MarshalToVT(dAtA []byte) (int, error) {
	_ = "STUB: not implemented"
	return 0, nil
}

func (m *DecisionLogEntry_CheckResources) MarshalToSizedBufferVT(dAtA []byte) (int, error) {
	_ = "STUB: not implemented"
	return 0, nil
}

func (m *DecisionLogEntry_PlanResources) MarshalVT() (dAtA []byte, err error) {
	_ = "STUB: not implemented"
	return nil, nil
}

func (m *DecisionLogEntry_PlanResources) MarshalToVT(dAtA []byte) (int, error) {
	_ = "STUB: not implemented"
	return 0, nil
}

func (m *DecisionLogEntry_PlanResources) MarshalToSizedBufferVT(dAtA []byte) (int, error) {
	_ = "STUB: not implemented"
	return 0, nil
}

func (m *DecisionLogEntry) MarshalVT() (dAtA []byte, err error) {
	_ = "STUB: not implemented"
	return nil, nil
}

func (m *DecisionLogEntry) MarshalToVT(dAtA []byte) (int, error) {
	_ = "STUB: not implemented"
	return 0, nil
}

func (m *DecisionLogEntry) MarshalToSizedBufferVT(dAtA []byte) (int, error) {
	_ = "STUB: not implemented"
	return 0, nil
}

func (m *DecisionLogEntry_CheckResources_) MarshalToVT(dAtA []byte) (int, error) {
	_ = "STUB: not implemented"
	return 0, nil
}

func (m *DecisionLogEntry_CheckResources_) MarshalToSizedBufferVT(dAtA []byte) (int, error) {
	_ = "STUB: not implemented"
	return 0, nil
}

func (m *DecisionLogEntry_PlanResources_) MarshalToVT(dAtA []byte) (int, error) {
	_ = "STUB: not implemented"
	return 0, nil
}

func (m *DecisionLogEntry_PlanResources_) MarshalToSizedBufferVT(dAtA []byte) (int, error) {
	_ = "STUB: not implemented"
	return 0, nil
}

func (m *MetaValues) MarshalVT() (dAtA []byte, err error) {
	_ = "STUB: not implemented"
	return nil, nil
}

func (m *MetaValues) MarshalToVT(dAtA []byte) (int, error) {
	_ = "STUB: not implemented"
	return 0, nil
}

func (m *MetaValues) MarshalToSizedBufferVT(dAtA []byte) (int, error) {
	_ = "STUB: not implemented"
	return 0, nil
}

func (m *Peer) MarshalVT() (dAtA []byte, err error) { _ = "STUB: not implemented"; return nil, nil }

func (m *Peer) MarshalToVT(dAtA []byte) (int, error) { _ = "STUB: not implemented"; return 0, nil }

func (m *Peer) MarshalToSizedBufferVT(dAtA []byte) (int, error) {
	_ = "STUB: not implemented"
	return 0, nil
}

func (m *AuditTrail) MarshalVT() (dAtA []byte, err error) {
	_ = "STUB: not implemented"
	return nil, nil
}

func (m *AuditTrail) MarshalToVT(dAtA []byte) (int, error) {
	_ = "STUB: not implemented"
	return 0, nil
}

func (m *AuditTrail) MarshalToSizedBufferVT(dAtA []byte) (int, error) {
	_ = "STUB: not implemented"
	return 0, nil
}

func (m *PolicySource_Blob) MarshalVT() (dAtA []byte, err error) {
	_ = "STUB: not implemented"
	return nil, nil
}

func (m *PolicySource_Blob) MarshalToVT(dAtA []byte) (int, error) {
	_ = "STUB: not implemented"
	return 0, nil
}

func (m *PolicySource_Blob) MarshalToSizedBufferVT(dAtA []byte) (int, error) {
	_ = "STUB: not implemented"
	return 0, nil
}

func (m *PolicySource_Database) MarshalVT() (dAtA []byte, err error) {
	_ = "STUB: not implemented"
	return nil, nil
}

func (m *PolicySource_Database) MarshalToVT(dAtA []byte) (int, error) {
	_ = "STUB: not implemented"
	return 0, nil
}

func (m *PolicySource_Database) MarshalToSizedBufferVT(dAtA []byte) (int, error) {
	_ = "STUB: not implemented"
	return 0, nil
}

func (m *PolicySource_Disk) MarshalVT() (dAtA []byte, err error) {
	_ = "STUB: not implemented"
	return nil, nil
}

func (m *PolicySource_Disk) MarshalToVT(dAtA []byte) (int, error) {
	_ = "STUB: not implemented"
	return 0, nil
}

func (m *PolicySource_Disk) MarshalToSizedBufferVT(dAtA []byte) (int, error) {
	_ = "STUB: not implemented"
	return 0, nil
}

func (m *PolicySource_EmbeddedPDP) MarshalVT() (dAtA []byte, err error) {
	_ = "STUB: not implemented"
	return nil, nil
}

func (m *PolicySource_EmbeddedPDP) MarshalToVT(dAtA []byte) (int, error) {
	_ = "STUB: not implemented"
	return 0, nil
}

func (m *PolicySource_EmbeddedPDP) MarshalToSizedBufferVT(dAtA []byte) (int, error) {
	_ = "STUB: not implemented"
	return 0, nil
}

func (m *PolicySource_Git) MarshalVT() (dAtA []byte, err error) {
	_ = "STUB: not implemented"
	return nil, nil
}

func (m *PolicySource_Git) MarshalToVT(dAtA []byte) (int, error) {
	_ = "STUB: not implemented"
	return 0, nil
}

func (m *PolicySource_Git) MarshalToSizedBufferVT(dAtA []byte) (int, error) {
	_ = "STUB: not implemented"
	return 0, nil
}

func (m *PolicySource_Hub_EmbeddedBundle) MarshalVT() (dAtA []byte, err error) {
	_ = "STUB: not implemented"
	return nil, nil
}

func (m *PolicySource_Hub_EmbeddedBundle) MarshalToVT(dAtA []byte) (int, error) {
	_ = "STUB: not implemented"
	return 0, nil
}

func (m *PolicySource_Hub_EmbeddedBundle) MarshalToSizedBufferVT(dAtA []byte) (int, error) {
	_ = "STUB: not implemented"
	return 0, nil
}

func (m *PolicySource_Hub_LocalBundle) MarshalVT() (dAtA []byte, err error) {
	_ = "STUB: not implemented"
	return nil, nil
}

func (m *PolicySource_Hub_LocalBundle) MarshalToVT(dAtA []byte) (int, error) {
	_ = "STUB: not implemented"
	return 0, nil
}

func (m *PolicySource_Hub_LocalBundle) MarshalToSizedBufferVT(dAtA []byte) (int, error) {
	_ = "STUB: not implemented"
	return 0, nil
}

func (m *PolicySource_Hub_RemoteBundle) MarshalVT() (dAtA []byte, err error) {
	_ = "STUB: not implemented"
	return nil, nil
}

func (m *PolicySource_Hub_RemoteBundle) MarshalToVT(dAtA []byte) (int, error) {
	_ = "STUB: not implemented"
	return 0, nil
}

func (m *PolicySource_Hub_RemoteBundle) MarshalToSizedBufferVT(dAtA []byte) (int, error) {
	_ = "STUB: not implemented"
	return 0, nil
}

func (m *PolicySource_Hub) MarshalVT() (dAtA []byte, err error) {
	_ = "STUB: not implemented"
	return nil, nil
}

func (m *PolicySource_Hub) MarshalToVT(dAtA []byte) (int, error) {
	_ = "STUB: not implemented"
	return 0, nil
}

func (m *PolicySource_Hub) MarshalToSizedBufferVT(dAtA []byte) (int, error) {
	_ = "STUB: not implemented"
	return 0, nil
}

func (m *PolicySource_Hub_Label) MarshalToVT(dAtA []byte) (int, error) {
	_ = "STUB: not implemented"
	return 0, nil
}

func (m *PolicySource_Hub_Label) MarshalToSizedBufferVT(dAtA []byte) (int, error) {
	_ = "STUB: not implemented"
	return 0, nil
}

func (m *PolicySource_Hub_DeploymentId) MarshalToVT(dAtA []byte) (int, error) {
	_ = "STUB: not implemented"
	return 0, nil
}

func (m *PolicySource_Hub_DeploymentId) MarshalToSizedBufferVT(dAtA []byte) (int, error) {
	_ = "STUB: not implemented"
	return 0, nil
}

func (m *PolicySource_Hub_PlaygroundId) MarshalToVT(dAtA []byte) (int, error) {
	_ = "STUB: not implemented"
	return 0, nil
}

func (m *PolicySource_Hub_PlaygroundId) MarshalToSizedBufferVT(dAtA []byte) (int, error) {
	_ = "STUB: not implemented"
	return 0, nil
}

func (m *PolicySource_Hub_LocalBundle_) MarshalToVT(dAtA []byte) (int, error) {
	_ = "STUB: not implemented"
	return 0, nil
}

func (m *PolicySource_Hub_LocalBundle_) MarshalToSizedBufferVT(dAtA []byte) (int, error) {
	_ = "STUB: not implemented"
	return 0, nil
}

func (m *PolicySource_Hub_EmbeddedBundle_) MarshalToVT(dAtA []byte) (int, error) {
	_ = "STUB: not implemented"
	return 0, nil
}

func (m *PolicySource_Hub_EmbeddedBundle_) MarshalToSizedBufferVT(dAtA []byte) (int, error) {
	_ = "STUB: not implemented"
	return 0, nil
}

func (m *PolicySource_Hub_RemoteBundle_) MarshalToVT(dAtA []byte) (int, error) {
	_ = "STUB: not implemented"
	return 0, nil
}

func (m *PolicySource_Hub_RemoteBundle_) MarshalToSizedBufferVT(dAtA []byte) (int, error) {
	_ = "STUB: not implemented"
	return 0, nil
}

func (m *PolicySource) MarshalVT() (dAtA []byte, err error) {
	_ = "STUB: not implemented"
	return nil, nil
}

func (m *PolicySource) MarshalToVT(dAtA []byte) (int, error) {
	_ = "STUB: not implemented"
	return 0, nil
}

func (m *PolicySource) MarshalToSizedBufferVT(dAtA []byte) (int, error) {
	_ = "STUB: not implemented"
	return 0, nil
}

func (m *PolicySource_Blob_) MarshalToVT(dAtA []byte) (int, error) {
	_ = "STUB: not implemented"
	return 0, nil
}

func (m *PolicySource_Blob_) MarshalToSizedBufferVT(dAtA []byte) (int, error) {
	_ = "STUB: not implemented"
	return 0, nil
}

func (m *PolicySource_Database_) MarshalToVT(dAtA []byte) (int, error) {
	_ = "STUB: not implemented"
	return 0, nil
}

func (m *PolicySource_Database_) MarshalToSizedBufferVT(dAtA []byte) (int, error) {
	_ = "STUB: not implemented"
	return 0, nil
}

func (m *PolicySource_Disk_) MarshalToVT(dAtA []byte) (int, error) {
	_ = "STUB: not implemented"
	return 0, nil
}

func (m *PolicySource_Disk_) MarshalToSizedBufferVT(dAtA []byte) (int, error) {
	_ = "STUB: not implemented"
	return 0, nil
}

func (m *PolicySource_Git_) MarshalToVT(dAtA []byte) (int, error) {
	_ = "STUB: not implemented"
	return 0, nil
}

func (m *PolicySource_Git_) MarshalToSizedBufferVT(dAtA []byte) (int, error) {
	_ = "STUB: not implemented"
	return 0, nil
}

func (m *PolicySource_Hub_) MarshalToVT(dAtA []byte) (int, error) {
	_ = "STUB: not implemented"
	return 0, nil
}

func (m *PolicySource_Hub_) MarshalToSizedBufferVT(dAtA []byte) (int, error) {
	_ = "STUB: not implemented"
	return 0, nil
}

func (m *PolicySource_EmbeddedPdp) MarshalToVT(dAtA []byte) (int, error) {
	_ = "STUB: not implemented"
	return 0, nil
}

func (m *PolicySource_EmbeddedPdp) MarshalToSizedBufferVT(dAtA []byte) (int, error) {
	_ = "STUB: not implemented"
	return 0, nil
}

func (m *RequestContext) MarshalVT() (dAtA []byte, err error) {
	_ = "STUB: not implemented"
	return nil, nil
}

func (m *RequestContext) MarshalToVT(dAtA []byte) (int, error) {
	_ = "STUB: not implemented"
	return 0, nil
}

func (m *RequestContext) MarshalToSizedBufferVT(dAtA []byte) (int, error) {
	_ = "STUB: not implemented"
	return 0, nil
}

func (m *AccessLogEntry) SizeVT() (n int) { _ = "STUB: not implemented"; return 0 }

func (m *DecisionLogEntry_CheckResources) SizeVT() (n int) { _ = "STUB: not implemented"; return 0 }

func (m *DecisionLogEntry_PlanResources) SizeVT() (n int) { _ = "STUB: not implemented"; return 0 }

func (m *DecisionLogEntry) SizeVT() (n int) { _ = "STUB: not implemented"; return 0 }

func (m *DecisionLogEntry_CheckResources_) SizeVT() (n int) { _ = "STUB: not implemented"; return 0 }

func (m *DecisionLogEntry_PlanResources_) SizeVT() (n int) { _ = "STUB: not implemented"; return 0 }

func (m *MetaValues) SizeVT() (n int) { _ = "STUB: not implemented"; return 0 }

func (m *Peer) SizeVT() (n int) { _ = "STUB: not implemented"; return 0 }

func (m *AuditTrail) SizeVT() (n int) { _ = "STUB: not implemented"; return 0 }

func (m *PolicySource_Blob) SizeVT() (n int) { _ = "STUB: not implemented"; return 0 }

func (m *PolicySource_Database) SizeVT() (n int) { _ = "STUB: not implemented"; return 0 }

func (m *PolicySource_Disk) SizeVT() (n int) { _ = "STUB: not implemented"; return 0 }

func (m *PolicySource_EmbeddedPDP) SizeVT() (n int) { _ = "STUB: not implemented"; return 0 }

func (m *PolicySource_Git) SizeVT() (n int) { _ = "STUB: not implemented"; return 0 }

func (m *PolicySource_Hub_EmbeddedBundle) SizeVT() (n int) { _ = "STUB: not implemented"; return 0 }

func (m *PolicySource_Hub_LocalBundle) SizeVT() (n int) { _ = "STUB: not implemented"; return 0 }

func (m *PolicySource_Hub_RemoteBundle) SizeVT() (n int) { _ = "STUB: not implemented"; return 0 }

func (m *PolicySource_Hub) SizeVT() (n int) { _ = "STUB: not implemented"; return 0 }

func (m *PolicySource_Hub_Label) SizeVT() (n int) { _ = "STUB: not implemented"; return 0 }

func (m *PolicySource_Hub_DeploymentId) SizeVT() (n int) { _ = "STUB: not implemented"; return 0 }

func (m *PolicySource_Hub_PlaygroundId) SizeVT() (n int) { _ = "STUB: not implemented"; return 0 }

func (m *PolicySource_Hub_LocalBundle_) SizeVT() (n int) { _ = "STUB: not implemented"; return 0 }

func (m *PolicySource_Hub_EmbeddedBundle_) SizeVT() (n int) { _ = "STUB: not implemented"; return 0 }

func (m *PolicySource_Hub_RemoteBundle_) SizeVT() (n int) { _ = "STUB: not implemented"; return 0 }

func (m *PolicySource) SizeVT() (n int) { _ = "STUB: not implemented"; return 0 }

func (m *PolicySource_Blob_) SizeVT() (n int) { _ = "STUB: not implemented"; return 0 }

func (m *PolicySource_Database_) SizeVT() (n int) { _ = "STUB: not implemented"; return 0 }

func (m *PolicySource_Disk_) SizeVT() (n int) { _ = "STUB: not implemented"; return 0 }

func (m *PolicySource_Git_) SizeVT() (n int) { _ = "STUB: not implemented"; return 0 }

func (m *PolicySource_Hub_) SizeVT() (n int) { _ = "STUB: not implemented"; return 0 }

func (m *PolicySource_EmbeddedPdp) SizeVT() (n int) { _ = "STUB: not implemented"; return 0 }

func (m *RequestContext) SizeVT() (n int) { _ = "STUB: not implemented"; return 0 }

func (m *AccessLogEntry) UnmarshalVT(dAtA []byte) error { _ = "STUB: not implemented"; return nil }

func (m *DecisionLogEntry_CheckResources) UnmarshalVT(dAtA []byte) error {
	_ = "STUB: not implemented"
	return nil
}

func (m *DecisionLogEntry_PlanResources) UnmarshalVT(dAtA []byte) error {
	_ = "STUB: not implemented"
	return nil
}

func (m *DecisionLogEntry) UnmarshalVT(dAtA []byte) error { _ = "STUB: not implemented"; return nil }

func (m *MetaValues) UnmarshalVT(dAtA []byte) error { _ = "STUB: not implemented"; return nil }

func (m *Peer) UnmarshalVT(dAtA []byte) error { _ = "STUB: not implemented"; return nil }

func (m *AuditTrail) UnmarshalVT(dAtA []byte) error { _ = "STUB: not implemented"; return nil }

func (m *PolicySource_Blob) UnmarshalVT(dAtA []byte) error { _ = "STUB: not implemented"; return nil }

func (m *PolicySource_Database) UnmarshalVT(dAtA []byte) error {
	_ = "STUB: not implemented"
	return nil
}

func (m *PolicySource_Disk) UnmarshalVT(dAtA []byte) error { _ = "STUB: not implemented"; return nil }

func (m *PolicySource_EmbeddedPDP) UnmarshalVT(dAtA []byte) error {
	_ = "STUB: not implemented"
	return nil
}

func (m *PolicySource_Git) UnmarshalVT(dAtA []byte) error { _ = "STUB: not implemented"; return nil }

func (m *PolicySource_Hub_EmbeddedBundle) UnmarshalVT(dAtA []byte) error {
	_ = "STUB: not implemented"
	return nil
}

func (m *PolicySource_Hub_LocalBundle) UnmarshalVT(dAtA []byte) error {
	_ = "STUB: not implemented"
	return nil
}

func (m *PolicySource_Hub_RemoteBundle) UnmarshalVT(dAtA []byte) error {
	_ = "STUB: not implemented"
	return nil
}

func (m *PolicySource_Hub) UnmarshalVT(dAtA []byte) error { _ = "STUB: not implemented"; return nil }

func (m *PolicySource) UnmarshalVT(dAtA []byte) error { _ = "STUB: not implemented"; return nil }

func (m *RequestContext) UnmarshalVT(dAtA []byte) error { _ = "STUB: not implemented"; return nil }
