// Copyright 2021-2026 Zenauth Ltd.
// SPDX-License-Identifier: Apache-2.0

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: cerbos/audit/v1/audit.proto

package auditv1

import (
	sync "sync"

	v1 "github.com/cerbos/cerbos/api/genpb/cerbos/engine/v1"
	v11 "github.com/cerbos/cerbos/api/genpb/cerbos/policy/v1"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	structpb "google.golang.org/protobuf/types/known/structpb"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type PolicySource_Database_Driver int32

const (
	PolicySource_Database_DRIVER_UNSPECIFIED PolicySource_Database_Driver = 0
	PolicySource_Database_DRIVER_MYSQL       PolicySource_Database_Driver = 1
	PolicySource_Database_DRIVER_POSTGRES    PolicySource_Database_Driver = 2
	PolicySource_Database_DRIVER_SQLITE3     PolicySource_Database_Driver = 3
)

// Enum value maps for PolicySource_Database_Driver.
var (
	PolicySource_Database_Driver_name = map[int32]string{
		0: "DRIVER_UNSPECIFIED",
		1: "DRIVER_MYSQL",
		2: "DRIVER_POSTGRES",
		3: "DRIVER_SQLITE3",
	}
	PolicySource_Database_Driver_value = map[string]int32{
		"DRIVER_UNSPECIFIED": 0,
		"DRIVER_MYSQL":       1,
		"DRIVER_POSTGRES":    2,
		"DRIVER_SQLITE3":     3,
	}
)

func (x PolicySource_Database_Driver) Enum() *PolicySource_Database_Driver {
	_ = "STUB: not implemented"
	return nil
}

func (x PolicySource_Database_Driver) String() string { _ = "STUB: not implemented"; return "" }

func (PolicySource_Database_Driver) Descriptor() protoreflect.EnumDescriptor {
	_ = "STUB: not implemented"
	return *new(protoreflect.EnumDescriptor)
}

func (PolicySource_Database_Driver) Type() protoreflect.EnumType {
	_ = "STUB: not implemented"
	return *new(protoreflect.EnumType)
}

func (x PolicySource_Database_Driver) Number() protoreflect.EnumNumber {
	_ = "STUB: not implemented"
	return *new(protoreflect.EnumNumber)
}

// Deprecated: Use PolicySource_Database_Driver.Descriptor instead.
func (PolicySource_Database_Driver) EnumDescriptor() ([]byte, []int) {
	_ = "STUB: not implemented"
	return nil, nil
}

type AccessLogEntry struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	CallId         string                 `protobuf:"bytes,1,opt,name=call_id,json=callId,proto3" json:"call_id,omitempty"`
	Timestamp      *timestamppb.Timestamp `protobuf:"bytes,2,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	Peer           *Peer                  `protobuf:"bytes,3,opt,name=peer,proto3" json:"peer,omitempty"`
	Metadata       map[string]*MetaValues `protobuf:"bytes,4,rep,name=metadata,proto3" json:"metadata,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	Method         string                 `protobuf:"bytes,5,opt,name=method,proto3" json:"method,omitempty"`
	StatusCode     uint32                 `protobuf:"varint,6,opt,name=status_code,json=statusCode,proto3" json:"status_code,omitempty"`
	Oversized      bool                   `protobuf:"varint,7,opt,name=oversized,proto3" json:"oversized,omitempty"`
	PolicySource   *PolicySource          `protobuf:"bytes,8,opt,name=policy_source,json=policySource,proto3" json:"policy_source,omitempty"`
	RequestContext *RequestContext        `protobuf:"bytes,9,opt,name=request_context,json=requestContext,proto3,oneof" json:"request_context,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *AccessLogEntry) Reset() { _ = "STUB: not implemented"; return }

func (x *AccessLogEntry) String() string { _ = "STUB: not implemented"; return "" }

func (*AccessLogEntry) ProtoMessage() { _ = "STUB: not implemented"; return }

func (x *AccessLogEntry) ProtoReflect() protoreflect.Message {
	_ = "STUB: not implemented"
	return *new(protoreflect.Message)
}

// Deprecated: Use AccessLogEntry.ProtoReflect.Descriptor instead.
func (*AccessLogEntry) Descriptor() ([]byte, []int) { _ = "STUB: not implemented"; return nil, nil }

func (x *AccessLogEntry) GetCallId() string { _ = "STUB: not implemented"; return "" }

func (x *AccessLogEntry) GetTimestamp() *timestamppb.Timestamp {
	_ = "STUB: not implemented"
	return nil
}

func (x *AccessLogEntry) GetPeer() *Peer { _ = "STUB: not implemented"; return nil }

func (x *AccessLogEntry) GetMetadata() map[string]*MetaValues {
	_ = "STUB: not implemented"
	return nil
}

func (x *AccessLogEntry) GetMethod() string { _ = "STUB: not implemented"; return "" }

func (x *AccessLogEntry) GetStatusCode() uint32 { _ = "STUB: not implemented"; return 0 }

func (x *AccessLogEntry) GetOversized() bool { _ = "STUB: not implemented"; return false }

func (x *AccessLogEntry) GetPolicySource() *PolicySource { _ = "STUB: not implemented"; return nil }

func (x *AccessLogEntry) GetRequestContext() *RequestContext { _ = "STUB: not implemented"; return nil }

type DecisionLogEntry struct {
	state     protoimpl.MessageState `protogen:"open.v1"`
	CallId    string                 `protobuf:"bytes,1,opt,name=call_id,json=callId,proto3" json:"call_id,omitempty"`
	Timestamp *timestamppb.Timestamp `protobuf:"bytes,2,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	Peer      *Peer                  `protobuf:"bytes,3,opt,name=peer,proto3" json:"peer,omitempty"`
	// Deprecated. Use method.check_resources.inputs instead.
	//
	// Deprecated: Marked as deprecated in cerbos/audit/v1/audit.proto.
	Inputs []*v1.CheckInput `protobuf:"bytes,4,rep,name=inputs,proto3" json:"inputs,omitempty"`
	// Deprecated. Use method.check_resources.outputs instead.
	//
	// Deprecated: Marked as deprecated in cerbos/audit/v1/audit.proto.
	Outputs []*v1.CheckOutput `protobuf:"bytes,5,rep,name=outputs,proto3" json:"outputs,omitempty"`
	// Deprecated. Use method.check_resources.error instead.
	//
	// Deprecated: Marked as deprecated in cerbos/audit/v1/audit.proto.
	Error string `protobuf:"bytes,6,opt,name=error,proto3" json:"error,omitempty"`
	// Types that are valid to be assigned to Method:
	//
	//	*DecisionLogEntry_CheckResources_
	//	*DecisionLogEntry_PlanResources_
	Method         isDecisionLogEntry_Method `protobuf_oneof:"method"`
	Metadata       map[string]*MetaValues    `protobuf:"bytes,15,rep,name=metadata,proto3" json:"metadata,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	AuditTrail     *AuditTrail               `protobuf:"bytes,16,opt,name=audit_trail,json=auditTrail,proto3" json:"audit_trail,omitempty"`
	Oversized      bool                      `protobuf:"varint,17,opt,name=oversized,proto3" json:"oversized,omitempty"`
	PolicySource   *PolicySource             `protobuf:"bytes,18,opt,name=policy_source,json=policySource,proto3" json:"policy_source,omitempty"`
	RequestContext *RequestContext           `protobuf:"bytes,19,opt,name=request_context,json=requestContext,proto3,oneof" json:"request_context,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *DecisionLogEntry) Reset() { _ = "STUB: not implemented"; return }

func (x *DecisionLogEntry) String() string { _ = "STUB: not implemented"; return "" }

func (*DecisionLogEntry) ProtoMessage() { _ = "STUB: not implemented"; return }

func (x *DecisionLogEntry) ProtoReflect() protoreflect.Message {
	_ = "STUB: not implemented"
	return *new(protoreflect.Message)
}

// Deprecated: Use DecisionLogEntry.ProtoReflect.Descriptor instead.
func (*DecisionLogEntry) Descriptor() ([]byte, []int) { _ = "STUB: not implemented"; return nil, nil }

func (x *DecisionLogEntry) GetCallId() string { _ = "STUB: not implemented"; return "" }

func (x *DecisionLogEntry) GetTimestamp() *timestamppb.Timestamp {
	_ = "STUB: not implemented"
	return nil
}

func (x *DecisionLogEntry) GetPeer() *Peer { _ = "STUB: not implemented"; return nil }

// Deprecated: Marked as deprecated in cerbos/audit/v1/audit.proto.
func (x *DecisionLogEntry) GetInputs() []*v1.CheckInput { _ = "STUB: not implemented"; return nil }

// Deprecated: Marked as deprecated in cerbos/audit/v1/audit.proto.
func (x *DecisionLogEntry) GetOutputs() []*v1.CheckOutput { _ = "STUB: not implemented"; return nil }

// Deprecated: Marked as deprecated in cerbos/audit/v1/audit.proto.
func (x *DecisionLogEntry) GetError() string { _ = "STUB: not implemented"; return "" }

func (x *DecisionLogEntry) GetMethod() isDecisionLogEntry_Method {
	_ = "STUB: not implemented"
	return *new(isDecisionLogEntry_Method)
}

func (x *DecisionLogEntry) GetCheckResources() *DecisionLogEntry_CheckResources {
	_ = "STUB: not implemented"
	return nil
}

func (x *DecisionLogEntry) GetPlanResources() *DecisionLogEntry_PlanResources {
	_ = "STUB: not implemented"
	return nil
}

func (x *DecisionLogEntry) GetMetadata() map[string]*MetaValues {
	_ = "STUB: not implemented"
	return nil
}

func (x *DecisionLogEntry) GetAuditTrail() *AuditTrail { _ = "STUB: not implemented"; return nil }

func (x *DecisionLogEntry) GetOversized() bool { _ = "STUB: not implemented"; return false }

func (x *DecisionLogEntry) GetPolicySource() *PolicySource { _ = "STUB: not implemented"; return nil }

func (x *DecisionLogEntry) GetRequestContext() *RequestContext {
	_ = "STUB: not implemented"
	return nil
}

type isDecisionLogEntry_Method interface {
	isDecisionLogEntry_Method()
}

type DecisionLogEntry_CheckResources_ struct {
	CheckResources *DecisionLogEntry_CheckResources `protobuf:"bytes,7,opt,name=check_resources,json=checkResources,proto3,oneof"`
}

type DecisionLogEntry_PlanResources_ struct {
	PlanResources *DecisionLogEntry_PlanResources `protobuf:"bytes,8,opt,name=plan_resources,json=planResources,proto3,oneof"`
}

func (*DecisionLogEntry_CheckResources_) isDecisionLogEntry_Method() {
	_ = "STUB: not implemented"
	return
}

func (*DecisionLogEntry_PlanResources_) isDecisionLogEntry_Method() {
	_ = "STUB: not implemented"
	return
}

type MetaValues struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Values        []string               `protobuf:"bytes,1,rep,name=values,proto3" json:"values,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MetaValues) Reset() { _ = "STUB: not implemented"; return }

func (x *MetaValues) String() string { _ = "STUB: not implemented"; return "" }

func (*MetaValues) ProtoMessage() { _ = "STUB: not implemented"; return }

func (x *MetaValues) ProtoReflect() protoreflect.Message {
	_ = "STUB: not implemented"
	return *new(protoreflect.Message)
}

// Deprecated: Use MetaValues.ProtoReflect.Descriptor instead.
func (*MetaValues) Descriptor() ([]byte, []int) { _ = "STUB: not implemented"; return nil, nil }

func (x *MetaValues) GetValues() []string { _ = "STUB: not implemented"; return nil }

type Peer struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Address       string                 `protobuf:"bytes,1,opt,name=address,proto3" json:"address,omitempty"`
	AuthInfo      string                 `protobuf:"bytes,2,opt,name=auth_info,json=authInfo,proto3" json:"auth_info,omitempty"`
	UserAgent     string                 `protobuf:"bytes,3,opt,name=user_agent,json=userAgent,proto3" json:"user_agent,omitempty"`
	ForwardedFor  string                 `protobuf:"bytes,4,opt,name=forwarded_for,json=forwardedFor,proto3" json:"forwarded_for,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Peer) Reset() { _ = "STUB: not implemented"; return }

func (x *Peer) String() string { _ = "STUB: not implemented"; return "" }

func (*Peer) ProtoMessage() { _ = "STUB: not implemented"; return }

func (x *Peer) ProtoReflect() protoreflect.Message {
	_ = "STUB: not implemented"
	return *new(protoreflect.Message)
}

// Deprecated: Use Peer.ProtoReflect.Descriptor instead.
func (*Peer) Descriptor() ([]byte, []int) { _ = "STUB: not implemented"; return nil, nil }

func (x *Peer) GetAddress() string { _ = "STUB: not implemented"; return "" }

func (x *Peer) GetAuthInfo() string { _ = "STUB: not implemented"; return "" }

func (x *Peer) GetUserAgent() string { _ = "STUB: not implemented"; return "" }

func (x *Peer) GetForwardedFor() string { _ = "STUB: not implemented"; return "" }

type AuditTrail struct {
	state             protoimpl.MessageState           `protogen:"open.v1"`
	EffectivePolicies map[string]*v11.SourceAttributes `protobuf:"bytes,1,rep,name=effective_policies,json=effectivePolicies,proto3" json:"effective_policies,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *AuditTrail) Reset() { _ = "STUB: not implemented"; return }

func (x *AuditTrail) String() string { _ = "STUB: not implemented"; return "" }

func (*AuditTrail) ProtoMessage() { _ = "STUB: not implemented"; return }

func (x *AuditTrail) ProtoReflect() protoreflect.Message {
	_ = "STUB: not implemented"
	return *new(protoreflect.Message)
}

// Deprecated: Use AuditTrail.ProtoReflect.Descriptor instead.
func (*AuditTrail) Descriptor() ([]byte, []int) { _ = "STUB: not implemented"; return nil, nil }

func (x *AuditTrail) GetEffectivePolicies() map[string]*v11.SourceAttributes {
	_ = "STUB: not implemented"
	return nil
}

type PolicySource struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Types that are valid to be assigned to Source:
	//
	//	*PolicySource_Blob_
	//	*PolicySource_Database_
	//	*PolicySource_Disk_
	//	*PolicySource_Git_
	//	*PolicySource_Hub_
	//	*PolicySource_EmbeddedPdp
	Source        isPolicySource_Source `protobuf_oneof:"source"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PolicySource) Reset() { _ = "STUB: not implemented"; return }

func (x *PolicySource) String() string { _ = "STUB: not implemented"; return "" }

func (*PolicySource) ProtoMessage() { _ = "STUB: not implemented"; return }

func (x *PolicySource) ProtoReflect() protoreflect.Message {
	_ = "STUB: not implemented"
	return *new(protoreflect.Message)
}

// Deprecated: Use PolicySource.ProtoReflect.Descriptor instead.
func (*PolicySource) Descriptor() ([]byte, []int) { _ = "STUB: not implemented"; return nil, nil }

func (x *PolicySource) GetSource() isPolicySource_Source {
	_ = "STUB: not implemented"
	return *new(isPolicySource_Source)
}

func (x *PolicySource) GetBlob() *PolicySource_Blob { _ = "STUB: not implemented"; return nil }

func (x *PolicySource) GetDatabase() *PolicySource_Database { _ = "STUB: not implemented"; return nil }

func (x *PolicySource) GetDisk() *PolicySource_Disk { _ = "STUB: not implemented"; return nil }

func (x *PolicySource) GetGit() *PolicySource_Git { _ = "STUB: not implemented"; return nil }

func (x *PolicySource) GetHub() *PolicySource_Hub { _ = "STUB: not implemented"; return nil }

func (x *PolicySource) GetEmbeddedPdp() *PolicySource_EmbeddedPDP {
	_ = "STUB: not implemented"
	return nil
}

type isPolicySource_Source interface {
	isPolicySource_Source()
}

type PolicySource_Blob_ struct {
	Blob *PolicySource_Blob `protobuf:"bytes,1,opt,name=blob,proto3,oneof"`
}

type PolicySource_Database_ struct {
	Database *PolicySource_Database `protobuf:"bytes,2,opt,name=database,proto3,oneof"`
}

type PolicySource_Disk_ struct {
	Disk *PolicySource_Disk `protobuf:"bytes,3,opt,name=disk,proto3,oneof"`
}

type PolicySource_Git_ struct {
	Git *PolicySource_Git `protobuf:"bytes,4,opt,name=git,proto3,oneof"`
}

type PolicySource_Hub_ struct {
	Hub *PolicySource_Hub `protobuf:"bytes,5,opt,name=hub,proto3,oneof"`
}

type PolicySource_EmbeddedPdp struct {
	EmbeddedPdp *PolicySource_EmbeddedPDP `protobuf:"bytes,6,opt,name=embedded_pdp,json=embeddedPdp,proto3,oneof"`
}

func (*PolicySource_Blob_) isPolicySource_Source() { _ = "STUB: not implemented"; return }

func (*PolicySource_Database_) isPolicySource_Source() { _ = "STUB: not implemented"; return }

func (*PolicySource_Disk_) isPolicySource_Source() { _ = "STUB: not implemented"; return }

func (*PolicySource_Git_) isPolicySource_Source() { _ = "STUB: not implemented"; return }

func (*PolicySource_Hub_) isPolicySource_Source() { _ = "STUB: not implemented"; return }

func (*PolicySource_EmbeddedPdp) isPolicySource_Source() { _ = "STUB: not implemented"; return }

type RequestContext struct {
	state         protoimpl.MessageState     `protogen:"open.v1"`
	Annotations   map[string]*structpb.Value `protobuf:"bytes,1,rep,name=annotations,proto3" json:"annotations,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RequestContext) Reset() { _ = "STUB: not implemented"; return }

func (x *RequestContext) String() string { _ = "STUB: not implemented"; return "" }

func (*RequestContext) ProtoMessage() { _ = "STUB: not implemented"; return }

func (x *RequestContext) ProtoReflect() protoreflect.Message {
	_ = "STUB: not implemented"
	return *new(protoreflect.Message)
}

// Deprecated: Use RequestContext.ProtoReflect.Descriptor instead.
func (*RequestContext) Descriptor() ([]byte, []int) { _ = "STUB: not implemented"; return nil, nil }

func (x *RequestContext) GetAnnotations() map[string]*structpb.Value {
	_ = "STUB: not implemented"
	return nil
}

type DecisionLogEntry_CheckResources struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Inputs        []*v1.CheckInput       `protobuf:"bytes,1,rep,name=inputs,proto3" json:"inputs,omitempty"`
	Outputs       []*v1.CheckOutput      `protobuf:"bytes,2,rep,name=outputs,proto3" json:"outputs,omitempty"`
	Error         string                 `protobuf:"bytes,3,opt,name=error,proto3" json:"error,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DecisionLogEntry_CheckResources) Reset() { _ = "STUB: not implemented"; return }

func (x *DecisionLogEntry_CheckResources) String() string { _ = "STUB: not implemented"; return "" }

func (*DecisionLogEntry_CheckResources) ProtoMessage() { _ = "STUB: not implemented"; return }

func (x *DecisionLogEntry_CheckResources) ProtoReflect() protoreflect.Message {
	_ = "STUB: not implemented"
	return *new(protoreflect.Message)
}

// Deprecated: Use DecisionLogEntry_CheckResources.ProtoReflect.Descriptor instead.
func (*DecisionLogEntry_CheckResources) Descriptor() ([]byte, []int) {
	_ = "STUB: not implemented"
	return nil, nil
}

func (x *DecisionLogEntry_CheckResources) GetInputs() []*v1.CheckInput {
	_ = "STUB: not implemented"
	return nil
}

func (x *DecisionLogEntry_CheckResources) GetOutputs() []*v1.CheckOutput {
	_ = "STUB: not implemented"
	return nil
}

func (x *DecisionLogEntry_CheckResources) GetError() string { _ = "STUB: not implemented"; return "" }

type DecisionLogEntry_PlanResources struct {
	state         protoimpl.MessageState  `protogen:"open.v1"`
	Input         *v1.PlanResourcesInput  `protobuf:"bytes,1,opt,name=input,proto3" json:"input,omitempty"`
	Output        *v1.PlanResourcesOutput `protobuf:"bytes,2,opt,name=output,proto3" json:"output,omitempty"`
	Error         string                  `protobuf:"bytes,3,opt,name=error,proto3" json:"error,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DecisionLogEntry_PlanResources) Reset() { _ = "STUB: not implemented"; return }

func (x *DecisionLogEntry_PlanResources) String() string { _ = "STUB: not implemented"; return "" }

func (*DecisionLogEntry_PlanResources) ProtoMessage() { _ = "STUB: not implemented"; return }

func (x *DecisionLogEntry_PlanResources) ProtoReflect() protoreflect.Message {
	_ = "STUB: not implemented"
	return *new(protoreflect.Message)
}

// Deprecated: Use DecisionLogEntry_PlanResources.ProtoReflect.Descriptor instead.
func (*DecisionLogEntry_PlanResources) Descriptor() ([]byte, []int) {
	_ = "STUB: not implemented"
	return nil, nil
}

func (x *DecisionLogEntry_PlanResources) GetInput() *v1.PlanResourcesInput {
	_ = "STUB: not implemented"
	return nil
}

func (x *DecisionLogEntry_PlanResources) GetOutput() *v1.PlanResourcesOutput {
	_ = "STUB: not implemented"
	return nil
}

func (x *DecisionLogEntry_PlanResources) GetError() string { _ = "STUB: not implemented"; return "" }

type PolicySource_Blob struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	BucketUrl     string                 `protobuf:"bytes,1,opt,name=bucket_url,json=bucketUrl,proto3" json:"bucket_url,omitempty"`
	Prefix        string                 `protobuf:"bytes,2,opt,name=prefix,proto3" json:"prefix,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PolicySource_Blob) Reset() { _ = "STUB: not implemented"; return }

func (x *PolicySource_Blob) String() string { _ = "STUB: not implemented"; return "" }

func (*PolicySource_Blob) ProtoMessage() { _ = "STUB: not implemented"; return }

func (x *PolicySource_Blob) ProtoReflect() protoreflect.Message {
	_ = "STUB: not implemented"
	return *new(protoreflect.Message)
}

// Deprecated: Use PolicySource_Blob.ProtoReflect.Descriptor instead.
func (*PolicySource_Blob) Descriptor() ([]byte, []int) { _ = "STUB: not implemented"; return nil, nil }

func (x *PolicySource_Blob) GetBucketUrl() string { _ = "STUB: not implemented"; return "" }

func (x *PolicySource_Blob) GetPrefix() string { _ = "STUB: not implemented"; return "" }

type PolicySource_Database struct {
	state         protoimpl.MessageState       `protogen:"open.v1"`
	Driver        PolicySource_Database_Driver `protobuf:"varint,1,opt,name=driver,proto3,enum=cerbos.audit.v1.PolicySource_Database_Driver" json:"driver,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PolicySource_Database) Reset() { _ = "STUB: not implemented"; return }

func (x *PolicySource_Database) String() string { _ = "STUB: not implemented"; return "" }

func (*PolicySource_Database) ProtoMessage() { _ = "STUB: not implemented"; return }

func (x *PolicySource_Database) ProtoReflect() protoreflect.Message {
	_ = "STUB: not implemented"
	return *new(protoreflect.Message)
}

// Deprecated: Use PolicySource_Database.ProtoReflect.Descriptor instead.
func (*PolicySource_Database) Descriptor() ([]byte, []int) {
	_ = "STUB: not implemented"
	return nil, nil
}

func (x *PolicySource_Database) GetDriver() PolicySource_Database_Driver {
	_ = "STUB: not implemented"
	return *new(PolicySource_Database_Driver)
}

type PolicySource_Disk struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Directory     string                 `protobuf:"bytes,1,opt,name=directory,proto3" json:"directory,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PolicySource_Disk) Reset() { _ = "STUB: not implemented"; return }

func (x *PolicySource_Disk) String() string { _ = "STUB: not implemented"; return "" }

func (*PolicySource_Disk) ProtoMessage() { _ = "STUB: not implemented"; return }

func (x *PolicySource_Disk) ProtoReflect() protoreflect.Message {
	_ = "STUB: not implemented"
	return *new(protoreflect.Message)
}

// Deprecated: Use PolicySource_Disk.ProtoReflect.Descriptor instead.
func (*PolicySource_Disk) Descriptor() ([]byte, []int) { _ = "STUB: not implemented"; return nil, nil }

func (x *PolicySource_Disk) GetDirectory() string { _ = "STUB: not implemented"; return "" }

type PolicySource_EmbeddedPDP struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Url           string                 `protobuf:"bytes,1,opt,name=url,proto3" json:"url,omitempty"`
	CommitHash    string                 `protobuf:"bytes,2,opt,name=commit_hash,json=commitHash,proto3" json:"commit_hash,omitempty"`
	BuiltAt       *timestamppb.Timestamp `protobuf:"bytes,3,opt,name=built_at,json=builtAt,proto3" json:"built_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PolicySource_EmbeddedPDP) Reset() { _ = "STUB: not implemented"; return }

func (x *PolicySource_EmbeddedPDP) String() string { _ = "STUB: not implemented"; return "" }

func (*PolicySource_EmbeddedPDP) ProtoMessage() { _ = "STUB: not implemented"; return }

func (x *PolicySource_EmbeddedPDP) ProtoReflect() protoreflect.Message {
	_ = "STUB: not implemented"
	return *new(protoreflect.Message)
}

// Deprecated: Use PolicySource_EmbeddedPDP.ProtoReflect.Descriptor instead.
func (*PolicySource_EmbeddedPDP) Descriptor() ([]byte, []int) {
	_ = "STUB: not implemented"
	return nil, nil
}

func (x *PolicySource_EmbeddedPDP) GetUrl() string { _ = "STUB: not implemented"; return "" }

func (x *PolicySource_EmbeddedPDP) GetCommitHash() string { _ = "STUB: not implemented"; return "" }

func (x *PolicySource_EmbeddedPDP) GetBuiltAt() *timestamppb.Timestamp {
	_ = "STUB: not implemented"
	return nil
}

type PolicySource_Git struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	RepositoryUrl string                 `protobuf:"bytes,1,opt,name=repository_url,json=repositoryUrl,proto3" json:"repository_url,omitempty"`
	Branch        string                 `protobuf:"bytes,2,opt,name=branch,proto3" json:"branch,omitempty"`
	Subdirectory  string                 `protobuf:"bytes,3,opt,name=subdirectory,proto3" json:"subdirectory,omitempty"`
	Hash          string                 `protobuf:"bytes,4,opt,name=hash,proto3" json:"hash,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PolicySource_Git) Reset() { _ = "STUB: not implemented"; return }

func (x *PolicySource_Git) String() string { _ = "STUB: not implemented"; return "" }

func (*PolicySource_Git) ProtoMessage() { _ = "STUB: not implemented"; return }

func (x *PolicySource_Git) ProtoReflect() protoreflect.Message {
	_ = "STUB: not implemented"
	return *new(protoreflect.Message)
}

// Deprecated: Use PolicySource_Git.ProtoReflect.Descriptor instead.
func (*PolicySource_Git) Descriptor() ([]byte, []int) { _ = "STUB: not implemented"; return nil, nil }

func (x *PolicySource_Git) GetRepositoryUrl() string { _ = "STUB: not implemented"; return "" }

func (x *PolicySource_Git) GetBranch() string { _ = "STUB: not implemented"; return "" }

func (x *PolicySource_Git) GetSubdirectory() string { _ = "STUB: not implemented"; return "" }

func (x *PolicySource_Git) GetHash() string { _ = "STUB: not implemented"; return "" }

type PolicySource_Hub struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Types that are valid to be assigned to Source:
	//
	//	*PolicySource_Hub_Label
	//	*PolicySource_Hub_DeploymentId
	//	*PolicySource_Hub_PlaygroundId
	//	*PolicySource_Hub_LocalBundle_
	//	*PolicySource_Hub_EmbeddedBundle_
	//	*PolicySource_Hub_RemoteBundle_
	Source        isPolicySource_Hub_Source `protobuf_oneof:"source"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PolicySource_Hub) Reset() { _ = "STUB: not implemented"; return }

func (x *PolicySource_Hub) String() string { _ = "STUB: not implemented"; return "" }

func (*PolicySource_Hub) ProtoMessage() { _ = "STUB: not implemented"; return }

func (x *PolicySource_Hub) ProtoReflect() protoreflect.Message {
	_ = "STUB: not implemented"
	return *new(protoreflect.Message)
}

// Deprecated: Use PolicySource_Hub.ProtoReflect.Descriptor instead.
func (*PolicySource_Hub) Descriptor() ([]byte, []int) { _ = "STUB: not implemented"; return nil, nil }

func (x *PolicySource_Hub) GetSource() isPolicySource_Hub_Source {
	_ = "STUB: not implemented"
	return *new(isPolicySource_Hub_Source)
}

func (x *PolicySource_Hub) GetLabel() string { _ = "STUB: not implemented"; return "" }

// Deprecated: Marked as deprecated in cerbos/audit/v1/audit.proto.
func (x *PolicySource_Hub) GetDeploymentId() string { _ = "STUB: not implemented"; return "" }

func (x *PolicySource_Hub) GetPlaygroundId() string { _ = "STUB: not implemented"; return "" }

func (x *PolicySource_Hub) GetLocalBundle() *PolicySource_Hub_LocalBundle {
	_ = "STUB: not implemented"
	return nil
}

func (x *PolicySource_Hub) GetEmbeddedBundle() *PolicySource_Hub_EmbeddedBundle {
	_ = "STUB: not implemented"
	return nil
}

func (x *PolicySource_Hub) GetRemoteBundle() *PolicySource_Hub_RemoteBundle {
	_ = "STUB: not implemented"
	return nil
}

type isPolicySource_Hub_Source interface {
	isPolicySource_Hub_Source()
}

type PolicySource_Hub_Label struct {
	Label string `protobuf:"bytes,1,opt,name=label,proto3,oneof"`
}

type PolicySource_Hub_DeploymentId struct {
	// Deprecated: Marked as deprecated in cerbos/audit/v1/audit.proto.
	DeploymentId string `protobuf:"bytes,2,opt,name=deployment_id,json=deploymentId,proto3,oneof"`
}

type PolicySource_Hub_PlaygroundId struct {
	PlaygroundId string `protobuf:"bytes,3,opt,name=playground_id,json=playgroundId,proto3,oneof"`
}

type PolicySource_Hub_LocalBundle_ struct {
	LocalBundle *PolicySource_Hub_LocalBundle `protobuf:"bytes,4,opt,name=local_bundle,json=localBundle,proto3,oneof"`
}

type PolicySource_Hub_EmbeddedBundle_ struct {
	EmbeddedBundle *PolicySource_Hub_EmbeddedBundle `protobuf:"bytes,5,opt,name=embedded_bundle,json=embeddedBundle,proto3,oneof"`
}

type PolicySource_Hub_RemoteBundle_ struct {
	RemoteBundle *PolicySource_Hub_RemoteBundle `protobuf:"bytes,6,opt,name=remote_bundle,json=remoteBundle,proto3,oneof"`
}

func (*PolicySource_Hub_Label) isPolicySource_Hub_Source() { _ = "STUB: not implemented"; return }

func (*PolicySource_Hub_DeploymentId) isPolicySource_Hub_Source() {
	_ = "STUB: not implemented"
	return
}

func (*PolicySource_Hub_PlaygroundId) isPolicySource_Hub_Source() {
	_ = "STUB: not implemented"
	return
}

func (*PolicySource_Hub_LocalBundle_) isPolicySource_Hub_Source() {
	_ = "STUB: not implemented"
	return
}

func (*PolicySource_Hub_EmbeddedBundle_) isPolicySource_Hub_Source() {
	_ = "STUB: not implemented"
	return
}

func (*PolicySource_Hub_RemoteBundle_) isPolicySource_Hub_Source() {
	_ = "STUB: not implemented"
	return
}

type PolicySource_Hub_EmbeddedBundle struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	RuleId        string                 `protobuf:"bytes,1,opt,name=rule_id,json=ruleId,proto3" json:"rule_id,omitempty"`
	Scopes        []string               `protobuf:"bytes,2,rep,name=scopes,proto3" json:"scopes,omitempty"`
	BundleId      string                 `protobuf:"bytes,3,opt,name=bundle_id,json=bundleId,proto3" json:"bundle_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PolicySource_Hub_EmbeddedBundle) Reset() { _ = "STUB: not implemented"; return }

func (x *PolicySource_Hub_EmbeddedBundle) String() string { _ = "STUB: not implemented"; return "" }

func (*PolicySource_Hub_EmbeddedBundle) ProtoMessage() { _ = "STUB: not implemented"; return }

func (x *PolicySource_Hub_EmbeddedBundle) ProtoReflect() protoreflect.Message {
	_ = "STUB: not implemented"
	return *new(protoreflect.Message)
}

// Deprecated: Use PolicySource_Hub_EmbeddedBundle.ProtoReflect.Descriptor instead.
func (*PolicySource_Hub_EmbeddedBundle) Descriptor() ([]byte, []int) {
	_ = "STUB: not implemented"
	return nil, nil
}

func (x *PolicySource_Hub_EmbeddedBundle) GetRuleId() string { _ = "STUB: not implemented"; return "" }

func (x *PolicySource_Hub_EmbeddedBundle) GetScopes() []string {
	_ = "STUB: not implemented"
	return nil
}

func (x *PolicySource_Hub_EmbeddedBundle) GetBundleId() string {
	_ = "STUB: not implemented"
	return ""
}

type PolicySource_Hub_LocalBundle struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Path          string                 `protobuf:"bytes,1,opt,name=path,proto3" json:"path,omitempty"`
	BundleId      string                 `protobuf:"bytes,2,opt,name=bundle_id,json=bundleId,proto3" json:"bundle_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PolicySource_Hub_LocalBundle) Reset() { _ = "STUB: not implemented"; return }

func (x *PolicySource_Hub_LocalBundle) String() string { _ = "STUB: not implemented"; return "" }

func (*PolicySource_Hub_LocalBundle) ProtoMessage() { _ = "STUB: not implemented"; return }

func (x *PolicySource_Hub_LocalBundle) ProtoReflect() protoreflect.Message {
	_ = "STUB: not implemented"
	return *new(protoreflect.Message)
}

// Deprecated: Use PolicySource_Hub_LocalBundle.ProtoReflect.Descriptor instead.
func (*PolicySource_Hub_LocalBundle) Descriptor() ([]byte, []int) {
	_ = "STUB: not implemented"
	return nil, nil
}

func (x *PolicySource_Hub_LocalBundle) GetPath() string { _ = "STUB: not implemented"; return "" }

func (x *PolicySource_Hub_LocalBundle) GetBundleId() string { _ = "STUB: not implemented"; return "" }

type PolicySource_Hub_RemoteBundle struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	DeploymentId  string                 `protobuf:"bytes,1,opt,name=deployment_id,json=deploymentId,proto3" json:"deployment_id,omitempty"`
	BundleId      string                 `protobuf:"bytes,2,opt,name=bundle_id,json=bundleId,proto3" json:"bundle_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PolicySource_Hub_RemoteBundle) Reset() { _ = "STUB: not implemented"; return }

func (x *PolicySource_Hub_RemoteBundle) String() string { _ = "STUB: not implemented"; return "" }

func (*PolicySource_Hub_RemoteBundle) ProtoMessage() { _ = "STUB: not implemented"; return }

func (x *PolicySource_Hub_RemoteBundle) ProtoReflect() protoreflect.Message {
	_ = "STUB: not implemented"
	return *new(protoreflect.Message)
}

// Deprecated: Use PolicySource_Hub_RemoteBundle.ProtoReflect.Descriptor instead.
func (*PolicySource_Hub_RemoteBundle) Descriptor() ([]byte, []int) {
	_ = "STUB: not implemented"
	return nil, nil
}

func (x *PolicySource_Hub_RemoteBundle) GetDeploymentId() string {
	_ = "STUB: not implemented"
	return ""
}

func (x *PolicySource_Hub_RemoteBundle) GetBundleId() string { _ = "STUB: not implemented"; return "" }

var File_cerbos_audit_v1_audit_proto protoreflect.FileDescriptor

const file_cerbos_audit_v1_audit_proto_rawDesc = "" +
	"\n" +
	"\x1bcerbos/audit/v1/audit.proto\x12\x0fcerbos.audit.v1\x1a\x1bbuf/validate/validate.proto\x1a\x1dcerbos/engine/v1/engine.proto\x1a\x1dcerbos/policy/v1/policy.proto\x1a\x1cgoogle/protobuf/struct.proto\x1a\x1fgoogle/protobuf/timestamp.proto\x1a.protoc-gen-openapiv2/options/annotations.proto\"\xb1\x04\n" +
	"\x0eAccessLogEntry\x12\x17\n" +
	"\acall_id\x18\x01 \x01(\tR\x06callId\x128\n" +
	"\ttimestamp\x18\x02 \x01(\v2\x1a.google.protobuf.TimestampR\ttimestamp\x12)\n" +
	"\x04peer\x18\x03 \x01(\v2\x15.cerbos.audit.v1.PeerR\x04peer\x12I\n" +
	"\bmetadata\x18\x04 \x03(\v2-.cerbos.audit.v1.AccessLogEntry.MetadataEntryR\bmetadata\x12\x16\n" +
	"\x06method\x18\x05 \x01(\tR\x06method\x12\x1f\n" +
	"\vstatus_code\x18\x06 \x01(\rR\n" +
	"statusCode\x12\x1c\n" +
	"\toversized\x18\a \x01(\bR\toversized\x12B\n" +
	"\rpolicy_source\x18\b \x01(\v2\x1d.cerbos.audit.v1.PolicySourceR\fpolicySource\x12M\n" +
	"\x0frequest_context\x18\t \x01(\v2\x1f.cerbos.audit.v1.RequestContextH\x00R\x0erequestContext\x88\x01\x01\x1aX\n" +
	"\rMetadataEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x121\n" +
	"\x05value\x18\x02 \x01(\v2\x1b.cerbos.audit.v1.MetaValuesR\x05value:\x028\x01B\x12\n" +
	"\x10_request_context\"\xc7\t\n" +
	"\x10DecisionLogEntry\x12\x17\n" +
	"\acall_id\x18\x01 \x01(\tR\x06callId\x128\n" +
	"\ttimestamp\x18\x02 \x01(\v2\x1a.google.protobuf.TimestampR\ttimestamp\x12)\n" +
	"\x04peer\x18\x03 \x01(\v2\x15.cerbos.audit.v1.PeerR\x04peer\x128\n" +
	"\x06inputs\x18\x04 \x03(\v2\x1c.cerbos.engine.v1.CheckInputB\x02\x18\x01R\x06inputs\x12;\n" +
	"\aoutputs\x18\x05 \x03(\v2\x1d.cerbos.engine.v1.CheckOutputB\x02\x18\x01R\aoutputs\x12\x18\n" +
	"\x05error\x18\x06 \x01(\tB\x02\x18\x01R\x05error\x12[\n" +
	"\x0fcheck_resources\x18\a \x01(\v20.cerbos.audit.v1.DecisionLogEntry.CheckResourcesH\x00R\x0echeckResources\x12X\n" +
	"\x0eplan_resources\x18\b \x01(\v2/.cerbos.audit.v1.DecisionLogEntry.PlanResourcesH\x00R\rplanResources\x12K\n" +
	"\bmetadata\x18\x0f \x03(\v2/.cerbos.audit.v1.DecisionLogEntry.MetadataEntryR\bmetadata\x12<\n" +
	"\vaudit_trail\x18\x10 \x01(\v2\x1b.cerbos.audit.v1.AuditTrailR\n" +
	"auditTrail\x12\x1c\n" +
	"\toversized\x18\x11 \x01(\bR\toversized\x12B\n" +
	"\rpolicy_source\x18\x12 \x01(\v2\x1d.cerbos.audit.v1.PolicySourceR\fpolicySource\x12M\n" +
	"\x0frequest_context\x18\x13 \x01(\v2\x1f.cerbos.audit.v1.RequestContextH\x01R\x0erequestContext\x88\x01\x01\x1a\x95\x01\n" +
	"\x0eCheckResources\x124\n" +
	"\x06inputs\x18\x01 \x03(\v2\x1c.cerbos.engine.v1.CheckInputR\x06inputs\x127\n" +
	"\aoutputs\x18\x02 \x03(\v2\x1d.cerbos.engine.v1.CheckOutputR\aoutputs\x12\x14\n" +
	"\x05error\x18\x03 \x01(\tR\x05error\x1a\xa0\x01\n" +
	"\rPlanResources\x12:\n" +
	"\x05input\x18\x01 \x01(\v2$.cerbos.engine.v1.PlanResourcesInputR\x05input\x12=\n" +
	"\x06output\x18\x02 \x01(\v2%.cerbos.engine.v1.PlanResourcesOutputR\x06output\x12\x14\n" +
	"\x05error\x18\x03 \x01(\tR\x05error\x1aX\n" +
	"\rMetadataEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x121\n" +
	"\x05value\x18\x02 \x01(\v2\x1b.cerbos.audit.v1.MetaValuesR\x05value:\x028\x01B\b\n" +
	"\x06methodB\x12\n" +
	"\x10_request_context\"$\n" +
	"\n" +
	"MetaValues\x12\x16\n" +
	"\x06values\x18\x01 \x03(\tR\x06values\"\x81\x01\n" +
	"\x04Peer\x12\x18\n" +
	"\aaddress\x18\x01 \x01(\tR\aaddress\x12\x1b\n" +
	"\tauth_info\x18\x02 \x01(\tR\bauthInfo\x12\x1d\n" +
	"\n" +
	"user_agent\x18\x03 \x01(\tR\tuserAgent\x12#\n" +
	"\rforwarded_for\x18\x04 \x01(\tR\fforwardedFor\"\xd9\x01\n" +
	"\n" +
	"AuditTrail\x12a\n" +
	"\x12effective_policies\x18\x01 \x03(\v22.cerbos.audit.v1.AuditTrail.EffectivePoliciesEntryR\x11effectivePolicies\x1ah\n" +
	"\x16EffectivePoliciesEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x128\n" +
	"\x05value\x18\x02 \x01(\v2\".cerbos.policy.v1.SourceAttributesR\x05value:\x028\x01\"\x93\f\n" +
	"\fPolicySource\x128\n" +
	"\x04blob\x18\x01 \x01(\v2\".cerbos.audit.v1.PolicySource.BlobH\x00R\x04blob\x12D\n" +
	"\bdatabase\x18\x02 \x01(\v2&.cerbos.audit.v1.PolicySource.DatabaseH\x00R\bdatabase\x128\n" +
	"\x04disk\x18\x03 \x01(\v2\".cerbos.audit.v1.PolicySource.DiskH\x00R\x04disk\x125\n" +
	"\x03git\x18\x04 \x01(\v2!.cerbos.audit.v1.PolicySource.GitH\x00R\x03git\x125\n" +
	"\x03hub\x18\x05 \x01(\v2!.cerbos.audit.v1.PolicySource.HubH\x00R\x03hub\x12N\n" +
	"\fembedded_pdp\x18\x06 \x01(\v2).cerbos.audit.v1.PolicySource.EmbeddedPDPH\x00R\vembeddedPdp\x1a=\n" +
	"\x04Blob\x12\x1d\n" +
	"\n" +
	"bucket_url\x18\x01 \x01(\tR\tbucketUrl\x12\x16\n" +
	"\x06prefix\x18\x02 \x01(\tR\x06prefix\x1a\xae\x01\n" +
	"\bDatabase\x12E\n" +
	"\x06driver\x18\x01 \x01(\x0e2-.cerbos.audit.v1.PolicySource.Database.DriverR\x06driver\"[\n" +
	"\x06Driver\x12\x16\n" +
	"\x12DRIVER_UNSPECIFIED\x10\x00\x12\x10\n" +
	"\fDRIVER_MYSQL\x10\x01\x12\x13\n" +
	"\x0fDRIVER_POSTGRES\x10\x02\x12\x12\n" +
	"\x0eDRIVER_SQLITE3\x10\x03\x1a$\n" +
	"\x04Disk\x12\x1c\n" +
	"\tdirectory\x18\x01 \x01(\tR\tdirectory\x1aw\n" +
	"\vEmbeddedPDP\x12\x10\n" +
	"\x03url\x18\x01 \x01(\tR\x03url\x12\x1f\n" +
	"\vcommit_hash\x18\x02 \x01(\tR\n" +
	"commitHash\x125\n" +
	"\bbuilt_at\x18\x03 \x01(\v2\x1a.google.protobuf.TimestampR\abuiltAt\x1a|\n" +
	"\x03Git\x12%\n" +
	"\x0erepository_url\x18\x01 \x01(\tR\rrepositoryUrl\x12\x16\n" +
	"\x06branch\x18\x02 \x01(\tR\x06branch\x12\"\n" +
	"\fsubdirectory\x18\x03 \x01(\tR\fsubdirectory\x12\x12\n" +
	"\x04hash\x18\x04 \x01(\tR\x04hash\x1a\xf3\x04\n" +
	"\x03Hub\x12\x16\n" +
	"\x05label\x18\x01 \x01(\tH\x00R\x05label\x12)\n" +
	"\rdeployment_id\x18\x02 \x01(\tB\x02\x18\x01H\x00R\fdeploymentId\x12%\n" +
	"\rplayground_id\x18\x03 \x01(\tH\x00R\fplaygroundId\x12R\n" +
	"\flocal_bundle\x18\x04 \x01(\v2-.cerbos.audit.v1.PolicySource.Hub.LocalBundleH\x00R\vlocalBundle\x12[\n" +
	"\x0fembedded_bundle\x18\x05 \x01(\v20.cerbos.audit.v1.PolicySource.Hub.EmbeddedBundleH\x00R\x0eembeddedBundle\x12U\n" +
	"\rremote_bundle\x18\x06 \x01(\v2..cerbos.audit.v1.PolicySource.Hub.RemoteBundleH\x00R\fremoteBundle\x1a^\n" +
	"\x0eEmbeddedBundle\x12\x17\n" +
	"\arule_id\x18\x01 \x01(\tR\x06ruleId\x12\x16\n" +
	"\x06scopes\x18\x02 \x03(\tR\x06scopes\x12\x1b\n" +
	"\tbundle_id\x18\x03 \x01(\tR\bbundleId\x1a>\n" +
	"\vLocalBundle\x12\x12\n" +
	"\x04path\x18\x01 \x01(\tR\x04path\x12\x1b\n" +
	"\tbundle_id\x18\x02 \x01(\tR\bbundleId\x1aP\n" +
	"\fRemoteBundle\x12#\n" +
	"\rdeployment_id\x18\x01 \x01(\tR\fdeploymentId\x12\x1b\n" +
	"\tbundle_id\x18\x02 \x01(\tR\bbundleIdB\b\n" +
	"\x06sourceB\b\n" +
	"\x06source\"\xae\x03\n" +
	"\x0eRequestContext\x12\xbc\x01\n" +
	"\vannotations\x18\x01 \x03(\v20.cerbos.audit.v1.RequestContext.AnnotationsEntryBh\x92AY2\x1fKey-value pairs of annotations.J3{\"app-name\": \"awesome-app\", \"app-version\": \"1.2.3\"}\xc8\x01\x01\xbaH\t\x9a\x01\x06\"\x04r\x02\x10\x01R\vannotations\x1aV\n" +
	"\x10AnnotationsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12,\n" +
	"\x05value\x18\x02 \x01(\v2\x16.google.protobuf.ValueR\x05value:\x028\x01:\x84\x01\x92A\x80\x01\n" +
	"~2|Optional metadata to attach to the request. This information will be captured in the audit logs if audit logging is enabled.Bk\n" +
	"\x17dev.cerbos.api.v1.auditZ:github.com/cerbos/cerbos/api/genpb/cerbos/audit/v1;auditv1\xaa\x02\x13Cerbos.Api.V1.Auditb\x06proto3"

var (
	file_cerbos_audit_v1_audit_proto_rawDescOnce sync.Once
	file_cerbos_audit_v1_audit_proto_rawDescData []byte
)

func file_cerbos_audit_v1_audit_proto_rawDescGZIP() []byte { _ = "STUB: not implemented"; return nil }

var file_cerbos_audit_v1_audit_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_cerbos_audit_v1_audit_proto_msgTypes = make([]protoimpl.MessageInfo, 22)
var file_cerbos_audit_v1_audit_proto_goTypes = []any{
	(PolicySource_Database_Driver)(0),       // 0: cerbos.audit.v1.PolicySource.Database.Driver
	(*AccessLogEntry)(nil),                  // 1: cerbos.audit.v1.AccessLogEntry
	(*DecisionLogEntry)(nil),                // 2: cerbos.audit.v1.DecisionLogEntry
	(*MetaValues)(nil),                      // 3: cerbos.audit.v1.MetaValues
	(*Peer)(nil),                            // 4: cerbos.audit.v1.Peer
	(*AuditTrail)(nil),                      // 5: cerbos.audit.v1.AuditTrail
	(*PolicySource)(nil),                    // 6: cerbos.audit.v1.PolicySource
	(*RequestContext)(nil),                  // 7: cerbos.audit.v1.RequestContext
	nil,                                     // 8: cerbos.audit.v1.AccessLogEntry.MetadataEntry
	(*DecisionLogEntry_CheckResources)(nil), // 9: cerbos.audit.v1.DecisionLogEntry.CheckResources
	(*DecisionLogEntry_PlanResources)(nil),  // 10: cerbos.audit.v1.DecisionLogEntry.PlanResources
	nil,                                     // 11: cerbos.audit.v1.DecisionLogEntry.MetadataEntry
	nil,                                     // 12: cerbos.audit.v1.AuditTrail.EffectivePoliciesEntry
	(*PolicySource_Blob)(nil),               // 13: cerbos.audit.v1.PolicySource.Blob
	(*PolicySource_Database)(nil),           // 14: cerbos.audit.v1.PolicySource.Database
	(*PolicySource_Disk)(nil),               // 15: cerbos.audit.v1.PolicySource.Disk
	(*PolicySource_EmbeddedPDP)(nil),        // 16: cerbos.audit.v1.PolicySource.EmbeddedPDP
	(*PolicySource_Git)(nil),                // 17: cerbos.audit.v1.PolicySource.Git
	(*PolicySource_Hub)(nil),                // 18: cerbos.audit.v1.PolicySource.Hub
	(*PolicySource_Hub_EmbeddedBundle)(nil), // 19: cerbos.audit.v1.PolicySource.Hub.EmbeddedBundle
	(*PolicySource_Hub_LocalBundle)(nil),    // 20: cerbos.audit.v1.PolicySource.Hub.LocalBundle
	(*PolicySource_Hub_RemoteBundle)(nil),   // 21: cerbos.audit.v1.PolicySource.Hub.RemoteBundle
	nil,                                     // 22: cerbos.audit.v1.RequestContext.AnnotationsEntry
	(*timestamppb.Timestamp)(nil),           // 23: google.protobuf.Timestamp
	(*v1.CheckInput)(nil),                   // 24: cerbos.engine.v1.CheckInput
	(*v1.CheckOutput)(nil),                  // 25: cerbos.engine.v1.CheckOutput
	(*v1.PlanResourcesInput)(nil),           // 26: cerbos.engine.v1.PlanResourcesInput
	(*v1.PlanResourcesOutput)(nil),          // 27: cerbos.engine.v1.PlanResourcesOutput
	(*v11.SourceAttributes)(nil),            // 28: cerbos.policy.v1.SourceAttributes
	(*structpb.Value)(nil),                  // 29: google.protobuf.Value
}
var file_cerbos_audit_v1_audit_proto_depIdxs = []int32{
	23, // 0: cerbos.audit.v1.AccessLogEntry.timestamp:type_name -> google.protobuf.Timestamp
	4,  // 1: cerbos.audit.v1.AccessLogEntry.peer:type_name -> cerbos.audit.v1.Peer
	8,  // 2: cerbos.audit.v1.AccessLogEntry.metadata:type_name -> cerbos.audit.v1.AccessLogEntry.MetadataEntry
	6,  // 3: cerbos.audit.v1.AccessLogEntry.policy_source:type_name -> cerbos.audit.v1.PolicySource
	7,  // 4: cerbos.audit.v1.AccessLogEntry.request_context:type_name -> cerbos.audit.v1.RequestContext
	23, // 5: cerbos.audit.v1.DecisionLogEntry.timestamp:type_name -> google.protobuf.Timestamp
	4,  // 6: cerbos.audit.v1.DecisionLogEntry.peer:type_name -> cerbos.audit.v1.Peer
	24, // 7: cerbos.audit.v1.DecisionLogEntry.inputs:type_name -> cerbos.engine.v1.CheckInput
	25, // 8: cerbos.audit.v1.DecisionLogEntry.outputs:type_name -> cerbos.engine.v1.CheckOutput
	9,  // 9: cerbos.audit.v1.DecisionLogEntry.check_resources:type_name -> cerbos.audit.v1.DecisionLogEntry.CheckResources
	10, // 10: cerbos.audit.v1.DecisionLogEntry.plan_resources:type_name -> cerbos.audit.v1.DecisionLogEntry.PlanResources
	11, // 11: cerbos.audit.v1.DecisionLogEntry.metadata:type_name -> cerbos.audit.v1.DecisionLogEntry.MetadataEntry
	5,  // 12: cerbos.audit.v1.DecisionLogEntry.audit_trail:type_name -> cerbos.audit.v1.AuditTrail
	6,  // 13: cerbos.audit.v1.DecisionLogEntry.policy_source:type_name -> cerbos.audit.v1.PolicySource
	7,  // 14: cerbos.audit.v1.DecisionLogEntry.request_context:type_name -> cerbos.audit.v1.RequestContext
	12, // 15: cerbos.audit.v1.AuditTrail.effective_policies:type_name -> cerbos.audit.v1.AuditTrail.EffectivePoliciesEntry
	13, // 16: cerbos.audit.v1.PolicySource.blob:type_name -> cerbos.audit.v1.PolicySource.Blob
	14, // 17: cerbos.audit.v1.PolicySource.database:type_name -> cerbos.audit.v1.PolicySource.Database
	15, // 18: cerbos.audit.v1.PolicySource.disk:type_name -> cerbos.audit.v1.PolicySource.Disk
	17, // 19: cerbos.audit.v1.PolicySource.git:type_name -> cerbos.audit.v1.PolicySource.Git
	18, // 20: cerbos.audit.v1.PolicySource.hub:type_name -> cerbos.audit.v1.PolicySource.Hub
	16, // 21: cerbos.audit.v1.PolicySource.embedded_pdp:type_name -> cerbos.audit.v1.PolicySource.EmbeddedPDP
	22, // 22: cerbos.audit.v1.RequestContext.annotations:type_name -> cerbos.audit.v1.RequestContext.AnnotationsEntry
	3,  // 23: cerbos.audit.v1.AccessLogEntry.MetadataEntry.value:type_name -> cerbos.audit.v1.MetaValues
	24, // 24: cerbos.audit.v1.DecisionLogEntry.CheckResources.inputs:type_name -> cerbos.engine.v1.CheckInput
	25, // 25: cerbos.audit.v1.DecisionLogEntry.CheckResources.outputs:type_name -> cerbos.engine.v1.CheckOutput
	26, // 26: cerbos.audit.v1.DecisionLogEntry.PlanResources.input:type_name -> cerbos.engine.v1.PlanResourcesInput
	27, // 27: cerbos.audit.v1.DecisionLogEntry.PlanResources.output:type_name -> cerbos.engine.v1.PlanResourcesOutput
	3,  // 28: cerbos.audit.v1.DecisionLogEntry.MetadataEntry.value:type_name -> cerbos.audit.v1.MetaValues
	28, // 29: cerbos.audit.v1.AuditTrail.EffectivePoliciesEntry.value:type_name -> cerbos.policy.v1.SourceAttributes
	0,  // 30: cerbos.audit.v1.PolicySource.Database.driver:type_name -> cerbos.audit.v1.PolicySource.Database.Driver
	23, // 31: cerbos.audit.v1.PolicySource.EmbeddedPDP.built_at:type_name -> google.protobuf.Timestamp
	20, // 32: cerbos.audit.v1.PolicySource.Hub.local_bundle:type_name -> cerbos.audit.v1.PolicySource.Hub.LocalBundle
	19, // 33: cerbos.audit.v1.PolicySource.Hub.embedded_bundle:type_name -> cerbos.audit.v1.PolicySource.Hub.EmbeddedBundle
	21, // 34: cerbos.audit.v1.PolicySource.Hub.remote_bundle:type_name -> cerbos.audit.v1.PolicySource.Hub.RemoteBundle
	29, // 35: cerbos.audit.v1.RequestContext.AnnotationsEntry.value:type_name -> google.protobuf.Value
	36, // [36:36] is the sub-list for method output_type
	36, // [36:36] is the sub-list for method input_type
	36, // [36:36] is the sub-list for extension type_name
	36, // [36:36] is the sub-list for extension extendee
	0,  // [0:36] is the sub-list for field type_name
}

func init()                                  { file_cerbos_audit_v1_audit_proto_init() }
func file_cerbos_audit_v1_audit_proto_init() { _ = "STUB: not implemented"; return }
