// Code generated by protoc-gen-go-hashpb. DO NOT EDIT.
// protoc-gen-go-hashpb v0.5.0

package auditv1

import (
	hash "hash"
	sync "sync"

	v1 "github.com/cerbos/cerbos/api/genpb/cerbos/engine/v1"
	v11 "github.com/cerbos/cerbos/api/genpb/cerbos/policy/v1"
	v12 "github.com/cerbos/cerbos/api/genpb/cerbos/schema/v1"
	structpb "google.golang.org/protobuf/types/known/structpb"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
)

var hashpb_bufPool = sync.Pool{
	New: func() any { return new([10]byte) },
}

var hashpb_stringKeyPool = sync.Pool{
	New: func() any { return make([]string, 0, 32) },
}

var hashpb_int32KeyPool = sync.Pool{
	New: func() any { return make([]int32, 0, 32) },
}

var hashpb_int64KeyPool = sync.Pool{
	New: func() any { return make([]int64, 0, 32) },
}

var hashpb_uint32KeyPool = sync.Pool{
	New: func() any { return make([]uint32, 0, 32) },
}

var hashpb_uint64KeyPool = sync.Pool{
	New: func() any { return make([]uint64, 0, 32) },
}

func cerbos_audit_v1_AccessLogEntry_hashpb_sum(m *AccessLogEntry, hasher hash.Hash, ignore map[string]struct{}, b *[10]byte) {
	_ = "STUB: not implemented"
	return
}

func cerbos_audit_v1_AuditTrail_hashpb_sum(m *AuditTrail, hasher hash.Hash, ignore map[string]struct{}, b *[10]byte) {
	_ = "STUB: not implemented"
	return
}

func cerbos_audit_v1_DecisionLogEntry_CheckResources_hashpb_sum(m *DecisionLogEntry_CheckResources, hasher hash.Hash, ignore map[string]struct{}, b *[10]byte) {
	_ = "STUB: not implemented"
	return
}

func cerbos_audit_v1_DecisionLogEntry_PlanResources_hashpb_sum(m *DecisionLogEntry_PlanResources, hasher hash.Hash, ignore map[string]struct{}, b *[10]byte) {
	_ = "STUB: not implemented"
	return
}

func cerbos_audit_v1_DecisionLogEntry_hashpb_sum(m *DecisionLogEntry, hasher hash.Hash, ignore map[string]struct{}, b *[10]byte) {
	_ = "STUB: not implemented"
	return
}

func cerbos_audit_v1_MetaValues_hashpb_sum(m *MetaValues, hasher hash.Hash, ignore map[string]struct{}, b *[10]byte) {
	_ = "STUB: not implemented"
	return
}

func cerbos_audit_v1_Peer_hashpb_sum(m *Peer, hasher hash.Hash, ignore map[string]struct{}, b *[10]byte) {
	_ = "STUB: not implemented"
	return
}

func cerbos_audit_v1_PolicySource_Blob_hashpb_sum(m *PolicySource_Blob, hasher hash.Hash, ignore map[string]struct{}, b *[10]byte) {
	_ = "STUB: not implemented"
	return
}

func cerbos_audit_v1_PolicySource_Database_hashpb_sum(m *PolicySource_Database, hasher hash.Hash, ignore map[string]struct{}, b *[10]byte) {
	_ = "STUB: not implemented"
	return
}

func cerbos_audit_v1_PolicySource_Disk_hashpb_sum(m *PolicySource_Disk, hasher hash.Hash, ignore map[string]struct{}, b *[10]byte) {
	_ = "STUB: not implemented"
	return
}

func cerbos_audit_v1_PolicySource_EmbeddedPDP_hashpb_sum(m *PolicySource_EmbeddedPDP, hasher hash.Hash, ignore map[string]struct{}, b *[10]byte) {
	_ = "STUB: not implemented"
	return
}

func cerbos_audit_v1_PolicySource_Git_hashpb_sum(m *PolicySource_Git, hasher hash.Hash, ignore map[string]struct{}, b *[10]byte) {
	_ = "STUB: not implemented"
	return
}

func cerbos_audit_v1_PolicySource_Hub_EmbeddedBundle_hashpb_sum(m *PolicySource_Hub_EmbeddedBundle, hasher hash.Hash, ignore map[string]struct{}, b *[10]byte) {
	_ = "STUB: not implemented"
	return
}

func cerbos_audit_v1_PolicySource_Hub_LocalBundle_hashpb_sum(m *PolicySource_Hub_LocalBundle, hasher hash.Hash, ignore map[string]struct{}, b *[10]byte) {
	_ = "STUB: not implemented"
	return
}

func cerbos_audit_v1_PolicySource_Hub_RemoteBundle_hashpb_sum(m *PolicySource_Hub_RemoteBundle, hasher hash.Hash, ignore map[string]struct{}, b *[10]byte) {
	_ = "STUB: not implemented"
	return
}

func cerbos_audit_v1_PolicySource_Hub_hashpb_sum(m *PolicySource_Hub, hasher hash.Hash, ignore map[string]struct{}, b *[10]byte) {
	_ = "STUB: not implemented"
	return
}

func cerbos_audit_v1_PolicySource_hashpb_sum(m *PolicySource, hasher hash.Hash, ignore map[string]struct{}, b *[10]byte) {
	_ = "STUB: not implemented"
	return
}

func cerbos_audit_v1_RequestContext_hashpb_sum(m *RequestContext, hasher hash.Hash, ignore map[string]struct{}, b *[10]byte) {
	_ = "STUB: not implemented"
	return
}

func cerbos_engine_v1_AuxData_hashpb_sum(m *v1.AuxData, hasher hash.Hash, ignore map[string]struct{}, b *[10]byte) {
	_ = "STUB: not implemented"
	return
}

func cerbos_engine_v1_CheckInput_hashpb_sum(m *v1.CheckInput, hasher hash.Hash, ignore map[string]struct{}, b *[10]byte) {
	_ = "STUB: not implemented"
	return
}

func cerbos_engine_v1_CheckOutput_ActionEffect_hashpb_sum(m *v1.CheckOutput_ActionEffect, hasher hash.Hash, ignore map[string]struct{}, b *[10]byte) {
	_ = "STUB: not implemented"
	return
}

func cerbos_engine_v1_CheckOutput_hashpb_sum(m *v1.CheckOutput, hasher hash.Hash, ignore map[string]struct{}, b *[10]byte) {
	_ = "STUB: not implemented"
	return
}

func cerbos_engine_v1_OutputEntry_hashpb_sum(m *v1.OutputEntry, hasher hash.Hash, ignore map[string]struct{}, b *[10]byte) {
	_ = "STUB: not implemented"
	return
}

func cerbos_engine_v1_PlanResourcesFilter_Expression_Operand_hashpb_sum(m *v1.PlanResourcesFilter_Expression_Operand, hasher hash.Hash, ignore map[string]struct{}, b *[10]byte) {
	_ = "STUB: not implemented"
	return
}

func cerbos_engine_v1_PlanResourcesFilter_Expression_hashpb_sum(m *v1.PlanResourcesFilter_Expression, hasher hash.Hash, ignore map[string]struct{}, b *[10]byte) {
	_ = "STUB: not implemented"
	return
}

func cerbos_engine_v1_PlanResourcesFilter_hashpb_sum(m *v1.PlanResourcesFilter, hasher hash.Hash, ignore map[string]struct{}, b *[10]byte) {
	_ = "STUB: not implemented"
	return
}

func cerbos_engine_v1_PlanResourcesInput_Resource_hashpb_sum(m *v1.PlanResourcesInput_Resource, hasher hash.Hash, ignore map[string]struct{}, b *[10]byte) {
	_ = "STUB: not implemented"
	return
}

func cerbos_engine_v1_PlanResourcesInput_hashpb_sum(m *v1.PlanResourcesInput, hasher hash.Hash, ignore map[string]struct{}, b *[10]byte) {
	_ = "STUB: not implemented"
	return
}

func cerbos_engine_v1_PlanResourcesOutput_hashpb_sum(m *v1.PlanResourcesOutput, hasher hash.Hash, ignore map[string]struct{}, b *[10]byte) {
	_ = "STUB: not implemented"
	return
}

func cerbos_engine_v1_Principal_hashpb_sum(m *v1.Principal, hasher hash.Hash, ignore map[string]struct{}, b *[10]byte) {
	_ = "STUB: not implemented"
	return
}

func cerbos_engine_v1_Resource_hashpb_sum(m *v1.Resource, hasher hash.Hash, ignore map[string]struct{}, b *[10]byte) {
	_ = "STUB: not implemented"
	return
}

func cerbos_policy_v1_SourceAttributes_hashpb_sum(m *v11.SourceAttributes, hasher hash.Hash, ignore map[string]struct{}, b *[10]byte) {
	_ = "STUB: not implemented"
	return
}

func cerbos_schema_v1_ValidationError_hashpb_sum(m *v12.ValidationError, hasher hash.Hash, ignore map[string]struct{}, b *[10]byte) {
	_ = "STUB: not implemented"
	return
}

func google_protobuf_ListValue_hashpb_sum(m *structpb.ListValue, hasher hash.Hash, ignore map[string]struct{}, b *[10]byte) {
	_ = "STUB: not implemented"
	return
}

func google_protobuf_Struct_hashpb_sum(m *structpb.Struct, hasher hash.Hash, ignore map[string]struct{}, b *[10]byte) {
	_ = "STUB: not implemented"
	return
}

func google_protobuf_Timestamp_hashpb_sum(m *timestamppb.Timestamp, hasher hash.Hash, ignore map[string]struct{}, b *[10]byte) {
	_ = "STUB: not implemented"
	return
}

func google_protobuf_Value_hashpb_sum(m *structpb.Value, hasher hash.Hash, ignore map[string]struct{}, b *[10]byte) {
	_ = "STUB: not implemented"
	return
}
