// Copyright 2021-2026 Zenauth Ltd.
// SPDX-License-Identifier: Apache-2.0

// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.2
// - protoc             (unknown)
// source: cerbos/svc/v1/svc.proto

package svcv1

import (
	context "context"

	v1 "github.com/cerbos/cerbos/api/genpb/cerbos/request/v1"
	v11 "github.com/cerbos/cerbos/api/genpb/cerbos/response/v1"
	grpc "google.golang.org/grpc"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	CerbosService_CheckResourceSet_FullMethodName   = "/cerbos.svc.v1.CerbosService/CheckResourceSet"
	CerbosService_CheckResourceBatch_FullMethodName = "/cerbos.svc.v1.CerbosService/CheckResourceBatch"
	CerbosService_CheckResources_FullMethodName     = "/cerbos.svc.v1.CerbosService/CheckResources"
	CerbosService_ServerInfo_FullMethodName         = "/cerbos.svc.v1.CerbosService/ServerInfo"
	CerbosService_PlanResources_FullMethodName      = "/cerbos.svc.v1.CerbosService/PlanResources"
)

// CerbosServiceClient is the client API for CerbosService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type CerbosServiceClient interface {
	CheckResourceSet(ctx context.Context, in *v1.CheckResourceSetRequest, opts ...grpc.CallOption) (*v11.CheckResourceSetResponse, error)
	CheckResourceBatch(ctx context.Context, in *v1.CheckResourceBatchRequest, opts ...grpc.CallOption) (*v11.CheckResourceBatchResponse, error)
	CheckResources(ctx context.Context, in *v1.CheckResourcesRequest, opts ...grpc.CallOption) (*v11.CheckResourcesResponse, error)
	ServerInfo(ctx context.Context, in *v1.ServerInfoRequest, opts ...grpc.CallOption) (*v11.ServerInfoResponse, error)
	PlanResources(ctx context.Context, in *v1.PlanResourcesRequest, opts ...grpc.CallOption) (*v11.PlanResourcesResponse, error)
}

type cerbosServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewCerbosServiceClient(cc grpc.ClientConnInterface) CerbosServiceClient {
	_ = "STUB: not implemented"
	return *new(CerbosServiceClient)
}

func (c *cerbosServiceClient) CheckResourceSet(ctx context.Context, in *v1.CheckResourceSetRequest, opts ...grpc.CallOption) (*v11.CheckResourceSetResponse, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

func (c *cerbosServiceClient) CheckResourceBatch(ctx context.Context, in *v1.CheckResourceBatchRequest, opts ...grpc.CallOption) (*v11.CheckResourceBatchResponse, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

func (c *cerbosServiceClient) CheckResources(ctx context.Context, in *v1.CheckResourcesRequest, opts ...grpc.CallOption) (*v11.CheckResourcesResponse, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

func (c *cerbosServiceClient) ServerInfo(ctx context.Context, in *v1.ServerInfoRequest, opts ...grpc.CallOption) (*v11.ServerInfoResponse, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

func (c *cerbosServiceClient) PlanResources(ctx context.Context, in *v1.PlanResourcesRequest, opts ...grpc.CallOption) (*v11.PlanResourcesResponse, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

// CerbosServiceServer is the server API for CerbosService service.
// All implementations must embed UnimplementedCerbosServiceServer
// for forward compatibility.
type CerbosServiceServer interface {
	CheckResourceSet(context.Context, *v1.CheckResourceSetRequest) (*v11.CheckResourceSetResponse, error)
	CheckResourceBatch(context.Context, *v1.CheckResourceBatchRequest) (*v11.CheckResourceBatchResponse, error)
	CheckResources(context.Context, *v1.CheckResourcesRequest) (*v11.CheckResourcesResponse, error)
	ServerInfo(context.Context, *v1.ServerInfoRequest) (*v11.ServerInfoResponse, error)
	PlanResources(context.Context, *v1.PlanResourcesRequest) (*v11.PlanResourcesResponse, error)
	mustEmbedUnimplementedCerbosServiceServer()
}

// UnimplementedCerbosServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedCerbosServiceServer struct{}

func (UnimplementedCerbosServiceServer) CheckResourceSet(context.Context, *v1.CheckResourceSetRequest) (*v11.CheckResourceSetResponse, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

func (UnimplementedCerbosServiceServer) CheckResourceBatch(context.Context, *v1.CheckResourceBatchRequest) (*v11.CheckResourceBatchResponse, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

func (UnimplementedCerbosServiceServer) CheckResources(context.Context, *v1.CheckResourcesRequest) (*v11.CheckResourcesResponse, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

func (UnimplementedCerbosServiceServer) ServerInfo(context.Context, *v1.ServerInfoRequest) (*v11.ServerInfoResponse, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

func (UnimplementedCerbosServiceServer) PlanResources(context.Context, *v1.PlanResourcesRequest) (*v11.PlanResourcesResponse, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

func (UnimplementedCerbosServiceServer) mustEmbedUnimplementedCerbosServiceServer() {
	_ = "STUB: not implemented"
	return
}
func (UnimplementedCerbosServiceServer) testEmbeddedByValue() { _ = "STUB: not implemented"; return }

// UnsafeCerbosServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to CerbosServiceServer will
// result in compilation errors.
type UnsafeCerbosServiceServer interface {
	mustEmbedUnimplementedCerbosServiceServer()
}

func RegisterCerbosServiceServer(s grpc.ServiceRegistrar, srv CerbosServiceServer) {
	_ = "STUB: not implemented"
	// If the following call panics, it indicates UnimplementedCerbosServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	return
}

func _CerbosService_CheckResourceSet_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

func _CerbosService_CheckResourceBatch_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

func _CerbosService_CheckResources_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

func _CerbosService_ServerInfo_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

func _CerbosService_PlanResources_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

// CerbosService_ServiceDesc is the grpc.ServiceDesc for CerbosService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var CerbosService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "cerbos.svc.v1.CerbosService",
	HandlerType: (*CerbosServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "CheckResourceSet",
			Handler:    _CerbosService_CheckResourceSet_Handler,
		},
		{
			MethodName: "CheckResourceBatch",
			Handler:    _CerbosService_CheckResourceBatch_Handler,
		},
		{
			MethodName: "CheckResources",
			Handler:    _CerbosService_CheckResources_Handler,
		},
		{
			MethodName: "ServerInfo",
			Handler:    _CerbosService_ServerInfo_Handler,
		},
		{
			MethodName: "PlanResources",
			Handler:    _CerbosService_PlanResources_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "cerbos/svc/v1/svc.proto",
}

const (
	CerbosAdminService_AddOrUpdatePolicy_FullMethodName   = "/cerbos.svc.v1.CerbosAdminService/AddOrUpdatePolicy"
	CerbosAdminService_InspectPolicies_FullMethodName     = "/cerbos.svc.v1.CerbosAdminService/InspectPolicies"
	CerbosAdminService_ListPolicies_FullMethodName        = "/cerbos.svc.v1.CerbosAdminService/ListPolicies"
	CerbosAdminService_GetPolicy_FullMethodName           = "/cerbos.svc.v1.CerbosAdminService/GetPolicy"
	CerbosAdminService_DeletePolicy_FullMethodName        = "/cerbos.svc.v1.CerbosAdminService/DeletePolicy"
	CerbosAdminService_DisablePolicy_FullMethodName       = "/cerbos.svc.v1.CerbosAdminService/DisablePolicy"
	CerbosAdminService_EnablePolicy_FullMethodName        = "/cerbos.svc.v1.CerbosAdminService/EnablePolicy"
	CerbosAdminService_ListAuditLogEntries_FullMethodName = "/cerbos.svc.v1.CerbosAdminService/ListAuditLogEntries"
	CerbosAdminService_AddOrUpdateSchema_FullMethodName   = "/cerbos.svc.v1.CerbosAdminService/AddOrUpdateSchema"
	CerbosAdminService_ListSchemas_FullMethodName         = "/cerbos.svc.v1.CerbosAdminService/ListSchemas"
	CerbosAdminService_GetSchema_FullMethodName           = "/cerbos.svc.v1.CerbosAdminService/GetSchema"
	CerbosAdminService_DeleteSchema_FullMethodName        = "/cerbos.svc.v1.CerbosAdminService/DeleteSchema"
	CerbosAdminService_ReloadStore_FullMethodName         = "/cerbos.svc.v1.CerbosAdminService/ReloadStore"
	CerbosAdminService_PurgeStoreRevisions_FullMethodName = "/cerbos.svc.v1.CerbosAdminService/PurgeStoreRevisions"
)

// CerbosAdminServiceClient is the client API for CerbosAdminService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type CerbosAdminServiceClient interface {
	AddOrUpdatePolicy(ctx context.Context, in *v1.AddOrUpdatePolicyRequest, opts ...grpc.CallOption) (*v11.AddOrUpdatePolicyResponse, error)
	InspectPolicies(ctx context.Context, in *v1.InspectPoliciesRequest, opts ...grpc.CallOption) (*v11.InspectPoliciesResponse, error)
	ListPolicies(ctx context.Context, in *v1.ListPoliciesRequest, opts ...grpc.CallOption) (*v11.ListPoliciesResponse, error)
	GetPolicy(ctx context.Context, in *v1.GetPolicyRequest, opts ...grpc.CallOption) (*v11.GetPolicyResponse, error)
	DeletePolicy(ctx context.Context, in *v1.DeletePolicyRequest, opts ...grpc.CallOption) (*v11.DeletePolicyResponse, error)
	DisablePolicy(ctx context.Context, in *v1.DisablePolicyRequest, opts ...grpc.CallOption) (*v11.DisablePolicyResponse, error)
	EnablePolicy(ctx context.Context, in *v1.EnablePolicyRequest, opts ...grpc.CallOption) (*v11.EnablePolicyResponse, error)
	ListAuditLogEntries(ctx context.Context, in *v1.ListAuditLogEntriesRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[v11.ListAuditLogEntriesResponse], error)
	AddOrUpdateSchema(ctx context.Context, in *v1.AddOrUpdateSchemaRequest, opts ...grpc.CallOption) (*v11.AddOrUpdateSchemaResponse, error)
	ListSchemas(ctx context.Context, in *v1.ListSchemasRequest, opts ...grpc.CallOption) (*v11.ListSchemasResponse, error)
	GetSchema(ctx context.Context, in *v1.GetSchemaRequest, opts ...grpc.CallOption) (*v11.GetSchemaResponse, error)
	DeleteSchema(ctx context.Context, in *v1.DeleteSchemaRequest, opts ...grpc.CallOption) (*v11.DeleteSchemaResponse, error)
	ReloadStore(ctx context.Context, in *v1.ReloadStoreRequest, opts ...grpc.CallOption) (*v11.ReloadStoreResponse, error)
	PurgeStoreRevisions(ctx context.Context, in *v1.PurgeStoreRevisionsRequest, opts ...grpc.CallOption) (*v11.PurgeStoreRevisionsResponse, error)
}

type cerbosAdminServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewCerbosAdminServiceClient(cc grpc.ClientConnInterface) CerbosAdminServiceClient {
	_ = "STUB: not implemented"
	return *new(CerbosAdminServiceClient)
}

func (c *cerbosAdminServiceClient) AddOrUpdatePolicy(ctx context.Context, in *v1.AddOrUpdatePolicyRequest, opts ...grpc.CallOption) (*v11.AddOrUpdatePolicyResponse, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

func (c *cerbosAdminServiceClient) InspectPolicies(ctx context.Context, in *v1.InspectPoliciesRequest, opts ...grpc.CallOption) (*v11.InspectPoliciesResponse, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

func (c *cerbosAdminServiceClient) ListPolicies(ctx context.Context, in *v1.ListPoliciesRequest, opts ...grpc.CallOption) (*v11.ListPoliciesResponse, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

func (c *cerbosAdminServiceClient) GetPolicy(ctx context.Context, in *v1.GetPolicyRequest, opts ...grpc.CallOption) (*v11.GetPolicyResponse, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

func (c *cerbosAdminServiceClient) DeletePolicy(ctx context.Context, in *v1.DeletePolicyRequest, opts ...grpc.CallOption) (*v11.DeletePolicyResponse, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

func (c *cerbosAdminServiceClient) DisablePolicy(ctx context.Context, in *v1.DisablePolicyRequest, opts ...grpc.CallOption) (*v11.DisablePolicyResponse, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

func (c *cerbosAdminServiceClient) EnablePolicy(ctx context.Context, in *v1.EnablePolicyRequest, opts ...grpc.CallOption) (*v11.EnablePolicyResponse, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

func (c *cerbosAdminServiceClient) ListAuditLogEntries(ctx context.Context, in *v1.ListAuditLogEntriesRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[v11.ListAuditLogEntriesResponse], error) {
	_ = "STUB: not implemented"
	return nil, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type CerbosAdminService_ListAuditLogEntriesClient = grpc.ServerStreamingClient[v11.ListAuditLogEntriesResponse]

func (c *cerbosAdminServiceClient) AddOrUpdateSchema(ctx context.Context, in *v1.AddOrUpdateSchemaRequest, opts ...grpc.CallOption) (*v11.AddOrUpdateSchemaResponse, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

func (c *cerbosAdminServiceClient) ListSchemas(ctx context.Context, in *v1.ListSchemasRequest, opts ...grpc.CallOption) (*v11.ListSchemasResponse, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

func (c *cerbosAdminServiceClient) GetSchema(ctx context.Context, in *v1.GetSchemaRequest, opts ...grpc.CallOption) (*v11.GetSchemaResponse, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

func (c *cerbosAdminServiceClient) DeleteSchema(ctx context.Context, in *v1.DeleteSchemaRequest, opts ...grpc.CallOption) (*v11.DeleteSchemaResponse, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

func (c *cerbosAdminServiceClient) ReloadStore(ctx context.Context, in *v1.ReloadStoreRequest, opts ...grpc.CallOption) (*v11.ReloadStoreResponse, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

func (c *cerbosAdminServiceClient) PurgeStoreRevisions(ctx context.Context, in *v1.PurgeStoreRevisionsRequest, opts ...grpc.CallOption) (*v11.PurgeStoreRevisionsResponse, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

// CerbosAdminServiceServer is the server API for CerbosAdminService service.
// All implementations must embed UnimplementedCerbosAdminServiceServer
// for forward compatibility.
type CerbosAdminServiceServer interface {
	AddOrUpdatePolicy(context.Context, *v1.AddOrUpdatePolicyRequest) (*v11.AddOrUpdatePolicyResponse, error)
	InspectPolicies(context.Context, *v1.InspectPoliciesRequest) (*v11.InspectPoliciesResponse, error)
	ListPolicies(context.Context, *v1.ListPoliciesRequest) (*v11.ListPoliciesResponse, error)
	GetPolicy(context.Context, *v1.GetPolicyRequest) (*v11.GetPolicyResponse, error)
	DeletePolicy(context.Context, *v1.DeletePolicyRequest) (*v11.DeletePolicyResponse, error)
	DisablePolicy(context.Context, *v1.DisablePolicyRequest) (*v11.DisablePolicyResponse, error)
	EnablePolicy(context.Context, *v1.EnablePolicyRequest) (*v11.EnablePolicyResponse, error)
	ListAuditLogEntries(*v1.ListAuditLogEntriesRequest, grpc.ServerStreamingServer[v11.ListAuditLogEntriesResponse]) error
	AddOrUpdateSchema(context.Context, *v1.AddOrUpdateSchemaRequest) (*v11.AddOrUpdateSchemaResponse, error)
	ListSchemas(context.Context, *v1.ListSchemasRequest) (*v11.ListSchemasResponse, error)
	GetSchema(context.Context, *v1.GetSchemaRequest) (*v11.GetSchemaResponse, error)
	DeleteSchema(context.Context, *v1.DeleteSchemaRequest) (*v11.DeleteSchemaResponse, error)
	ReloadStore(context.Context, *v1.ReloadStoreRequest) (*v11.ReloadStoreResponse, error)
	PurgeStoreRevisions(context.Context, *v1.PurgeStoreRevisionsRequest) (*v11.PurgeStoreRevisionsResponse, error)
	mustEmbedUnimplementedCerbosAdminServiceServer()
}

// UnimplementedCerbosAdminServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedCerbosAdminServiceServer struct{}

func (UnimplementedCerbosAdminServiceServer) AddOrUpdatePolicy(context.Context, *v1.AddOrUpdatePolicyRequest) (*v11.AddOrUpdatePolicyResponse, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

func (UnimplementedCerbosAdminServiceServer) InspectPolicies(context.Context, *v1.InspectPoliciesRequest) (*v11.InspectPoliciesResponse, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

func (UnimplementedCerbosAdminServiceServer) ListPolicies(context.Context, *v1.ListPoliciesRequest) (*v11.ListPoliciesResponse, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

func (UnimplementedCerbosAdminServiceServer) GetPolicy(context.Context, *v1.GetPolicyRequest) (*v11.GetPolicyResponse, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

func (UnimplementedCerbosAdminServiceServer) DeletePolicy(context.Context, *v1.DeletePolicyRequest) (*v11.DeletePolicyResponse, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

func (UnimplementedCerbosAdminServiceServer) DisablePolicy(context.Context, *v1.DisablePolicyRequest) (*v11.DisablePolicyResponse, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

func (UnimplementedCerbosAdminServiceServer) EnablePolicy(context.Context, *v1.EnablePolicyRequest) (*v11.EnablePolicyResponse, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

func (UnimplementedCerbosAdminServiceServer) ListAuditLogEntries(*v1.ListAuditLogEntriesRequest, grpc.ServerStreamingServer[v11.ListAuditLogEntriesResponse]) error {
	_ = "STUB: not implemented"
	return nil
}

func (UnimplementedCerbosAdminServiceServer) AddOrUpdateSchema(context.Context, *v1.AddOrUpdateSchemaRequest) (*v11.AddOrUpdateSchemaResponse, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

func (UnimplementedCerbosAdminServiceServer) ListSchemas(context.Context, *v1.ListSchemasRequest) (*v11.ListSchemasResponse, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

func (UnimplementedCerbosAdminServiceServer) GetSchema(context.Context, *v1.GetSchemaRequest) (*v11.GetSchemaResponse, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

func (UnimplementedCerbosAdminServiceServer) DeleteSchema(context.Context, *v1.DeleteSchemaRequest) (*v11.DeleteSchemaResponse, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

func (UnimplementedCerbosAdminServiceServer) ReloadStore(context.Context, *v1.ReloadStoreRequest) (*v11.ReloadStoreResponse, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

func (UnimplementedCerbosAdminServiceServer) PurgeStoreRevisions(context.Context, *v1.PurgeStoreRevisionsRequest) (*v11.PurgeStoreRevisionsResponse, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

func (UnimplementedCerbosAdminServiceServer) mustEmbedUnimplementedCerbosAdminServiceServer() {
	_ = "STUB: not implemented"
	return
}
func (UnimplementedCerbosAdminServiceServer) testEmbeddedByValue() {
	_ = "STUB: not implemented"
	return
}

// UnsafeCerbosAdminServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to CerbosAdminServiceServer will
// result in compilation errors.
type UnsafeCerbosAdminServiceServer interface {
	mustEmbedUnimplementedCerbosAdminServiceServer()
}

func RegisterCerbosAdminServiceServer(s grpc.ServiceRegistrar, srv CerbosAdminServiceServer) {
	_ = "STUB: not implemented"
	// If the following call panics, it indicates UnimplementedCerbosAdminServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	return
}

func _CerbosAdminService_AddOrUpdatePolicy_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

func _CerbosAdminService_InspectPolicies_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

func _CerbosAdminService_ListPolicies_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

func _CerbosAdminService_GetPolicy_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

func _CerbosAdminService_DeletePolicy_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

func _CerbosAdminService_DisablePolicy_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

func _CerbosAdminService_EnablePolicy_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

func _CerbosAdminService_ListAuditLogEntries_Handler(srv interface{}, stream grpc.ServerStream) error {
	_ = "STUB: not implemented"
	return nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type CerbosAdminService_ListAuditLogEntriesServer = grpc.ServerStreamingServer[v11.ListAuditLogEntriesResponse]

func _CerbosAdminService_AddOrUpdateSchema_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

func _CerbosAdminService_ListSchemas_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

func _CerbosAdminService_GetSchema_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

func _CerbosAdminService_DeleteSchema_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

func _CerbosAdminService_ReloadStore_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

func _CerbosAdminService_PurgeStoreRevisions_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

// CerbosAdminService_ServiceDesc is the grpc.ServiceDesc for CerbosAdminService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var CerbosAdminService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "cerbos.svc.v1.CerbosAdminService",
	HandlerType: (*CerbosAdminServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "AddOrUpdatePolicy",
			Handler:    _CerbosAdminService_AddOrUpdatePolicy_Handler,
		},
		{
			MethodName: "InspectPolicies",
			Handler:    _CerbosAdminService_InspectPolicies_Handler,
		},
		{
			MethodName: "ListPolicies",
			Handler:    _CerbosAdminService_ListPolicies_Handler,
		},
		{
			MethodName: "GetPolicy",
			Handler:    _CerbosAdminService_GetPolicy_Handler,
		},
		{
			MethodName: "DeletePolicy",
			Handler:    _CerbosAdminService_DeletePolicy_Handler,
		},
		{
			MethodName: "DisablePolicy",
			Handler:    _CerbosAdminService_DisablePolicy_Handler,
		},
		{
			MethodName: "EnablePolicy",
			Handler:    _CerbosAdminService_EnablePolicy_Handler,
		},
		{
			MethodName: "AddOrUpdateSchema",
			Handler:    _CerbosAdminService_AddOrUpdateSchema_Handler,
		},
		{
			MethodName: "ListSchemas",
			Handler:    _CerbosAdminService_ListSchemas_Handler,
		},
		{
			MethodName: "GetSchema",
			Handler:    _CerbosAdminService_GetSchema_Handler,
		},
		{
			MethodName: "DeleteSchema",
			Handler:    _CerbosAdminService_DeleteSchema_Handler,
		},
		{
			MethodName: "ReloadStore",
			Handler:    _CerbosAdminService_ReloadStore_Handler,
		},
		{
			MethodName: "PurgeStoreRevisions",
			Handler:    _CerbosAdminService_PurgeStoreRevisions_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "ListAuditLogEntries",
			Handler:       _CerbosAdminService_ListAuditLogEntries_Handler,
			ServerStreams: true,
		},
	},
	Metadata: "cerbos/svc/v1/svc.proto",
}

const (
	CerbosPlaygroundService_PlaygroundValidate_FullMethodName = "/cerbos.svc.v1.CerbosPlaygroundService/PlaygroundValidate"
	CerbosPlaygroundService_PlaygroundTest_FullMethodName     = "/cerbos.svc.v1.CerbosPlaygroundService/PlaygroundTest"
	CerbosPlaygroundService_PlaygroundEvaluate_FullMethodName = "/cerbos.svc.v1.CerbosPlaygroundService/PlaygroundEvaluate"
	CerbosPlaygroundService_PlaygroundProxy_FullMethodName    = "/cerbos.svc.v1.CerbosPlaygroundService/PlaygroundProxy"
)

// CerbosPlaygroundServiceClient is the client API for CerbosPlaygroundService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type CerbosPlaygroundServiceClient interface {
	PlaygroundValidate(ctx context.Context, in *v1.PlaygroundValidateRequest, opts ...grpc.CallOption) (*v11.PlaygroundValidateResponse, error)
	PlaygroundTest(ctx context.Context, in *v1.PlaygroundTestRequest, opts ...grpc.CallOption) (*v11.PlaygroundTestResponse, error)
	PlaygroundEvaluate(ctx context.Context, in *v1.PlaygroundEvaluateRequest, opts ...grpc.CallOption) (*v11.PlaygroundEvaluateResponse, error)
	PlaygroundProxy(ctx context.Context, in *v1.PlaygroundProxyRequest, opts ...grpc.CallOption) (*v11.PlaygroundProxyResponse, error)
}

type cerbosPlaygroundServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewCerbosPlaygroundServiceClient(cc grpc.ClientConnInterface) CerbosPlaygroundServiceClient {
	_ = "STUB: not implemented"
	return *new(CerbosPlaygroundServiceClient)
}

func (c *cerbosPlaygroundServiceClient) PlaygroundValidate(ctx context.Context, in *v1.PlaygroundValidateRequest, opts ...grpc.CallOption) (*v11.PlaygroundValidateResponse, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

func (c *cerbosPlaygroundServiceClient) PlaygroundTest(ctx context.Context, in *v1.PlaygroundTestRequest, opts ...grpc.CallOption) (*v11.PlaygroundTestResponse, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

func (c *cerbosPlaygroundServiceClient) PlaygroundEvaluate(ctx context.Context, in *v1.PlaygroundEvaluateRequest, opts ...grpc.CallOption) (*v11.PlaygroundEvaluateResponse, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

func (c *cerbosPlaygroundServiceClient) PlaygroundProxy(ctx context.Context, in *v1.PlaygroundProxyRequest, opts ...grpc.CallOption) (*v11.PlaygroundProxyResponse, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

// CerbosPlaygroundServiceServer is the server API for CerbosPlaygroundService service.
// All implementations must embed UnimplementedCerbosPlaygroundServiceServer
// for forward compatibility.
type CerbosPlaygroundServiceServer interface {
	PlaygroundValidate(context.Context, *v1.PlaygroundValidateRequest) (*v11.PlaygroundValidateResponse, error)
	PlaygroundTest(context.Context, *v1.PlaygroundTestRequest) (*v11.PlaygroundTestResponse, error)
	PlaygroundEvaluate(context.Context, *v1.PlaygroundEvaluateRequest) (*v11.PlaygroundEvaluateResponse, error)
	PlaygroundProxy(context.Context, *v1.PlaygroundProxyRequest) (*v11.PlaygroundProxyResponse, error)
	mustEmbedUnimplementedCerbosPlaygroundServiceServer()
}

// UnimplementedCerbosPlaygroundServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedCerbosPlaygroundServiceServer struct{}

func (UnimplementedCerbosPlaygroundServiceServer) PlaygroundValidate(context.Context, *v1.PlaygroundValidateRequest) (*v11.PlaygroundValidateResponse, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

func (UnimplementedCerbosPlaygroundServiceServer) PlaygroundTest(context.Context, *v1.PlaygroundTestRequest) (*v11.PlaygroundTestResponse, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

func (UnimplementedCerbosPlaygroundServiceServer) PlaygroundEvaluate(context.Context, *v1.PlaygroundEvaluateRequest) (*v11.PlaygroundEvaluateResponse, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

func (UnimplementedCerbosPlaygroundServiceServer) PlaygroundProxy(context.Context, *v1.PlaygroundProxyRequest) (*v11.PlaygroundProxyResponse, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

func (UnimplementedCerbosPlaygroundServiceServer) mustEmbedUnimplementedCerbosPlaygroundServiceServer() {
	_ = "STUB: not implemented"
	return
}

func (UnimplementedCerbosPlaygroundServiceServer) testEmbeddedByValue() {
	_ = "STUB: not implemented"

	// UnsafeCerbosPlaygroundServiceServer may be embedded to opt out of forward compatibility for this service.
	// Use of this interface is not recommended, as added methods to CerbosPlaygroundServiceServer will
	// result in compilation errors.
	return
}

type UnsafeCerbosPlaygroundServiceServer interface {
	mustEmbedUnimplementedCerbosPlaygroundServiceServer()
}

func RegisterCerbosPlaygroundServiceServer(s grpc.ServiceRegistrar, srv CerbosPlaygroundServiceServer) {
	_ = "STUB: not implemented"
	// If the following call panics, it indicates UnimplementedCerbosPlaygroundServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	return
}

func _CerbosPlaygroundService_PlaygroundValidate_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

func _CerbosPlaygroundService_PlaygroundTest_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

func _CerbosPlaygroundService_PlaygroundEvaluate_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

func _CerbosPlaygroundService_PlaygroundProxy_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

// CerbosPlaygroundService_ServiceDesc is the grpc.ServiceDesc for CerbosPlaygroundService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var CerbosPlaygroundService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "cerbos.svc.v1.CerbosPlaygroundService",
	HandlerType: (*CerbosPlaygroundServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "PlaygroundValidate",
			Handler:    _CerbosPlaygroundService_PlaygroundValidate_Handler,
		},
		{
			MethodName: "PlaygroundTest",
			Handler:    _CerbosPlaygroundService_PlaygroundTest_Handler,
		},
		{
			MethodName: "PlaygroundEvaluate",
			Handler:    _CerbosPlaygroundService_PlaygroundEvaluate_Handler,
		},
		{
			MethodName: "PlaygroundProxy",
			Handler:    _CerbosPlaygroundService_PlaygroundProxy_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "cerbos/svc/v1/svc.proto",
}
