// Copyright 2021-2026 Zenauth Ltd.
// SPDX-License-Identifier: Apache-2.0

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: cerbos/effect/v1/effect.proto

package effectv1

import (
	sync "sync"

	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Effect int32

const (
	Effect_EFFECT_UNSPECIFIED Effect = 0
	Effect_EFFECT_ALLOW       Effect = 1
	Effect_EFFECT_DENY        Effect = 2
	Effect_EFFECT_NO_MATCH    Effect = 3
)

// Enum value maps for Effect.
var (
	Effect_name = map[int32]string{
		0: "EFFECT_UNSPECIFIED",
		1: "EFFECT_ALLOW",
		2: "EFFECT_DENY",
		3: "EFFECT_NO_MATCH",
	}
	Effect_value = map[string]int32{
		"EFFECT_UNSPECIFIED": 0,
		"EFFECT_ALLOW":       1,
		"EFFECT_DENY":        2,
		"EFFECT_NO_MATCH":    3,
	}
)

func (x Effect) Enum() *Effect { _ = "STUB: not implemented"; return nil }

func (x Effect) String() string { _ = "STUB: not implemented"; return "" }

func (Effect) Descriptor() protoreflect.EnumDescriptor {
	_ = "STUB: not implemented"
	return *new(protoreflect.EnumDescriptor)
}

func (Effect) Type() protoreflect.EnumType {
	_ = "STUB: not implemented"
	return *new(protoreflect.EnumType)
}

func (x Effect) Number() protoreflect.EnumNumber {
	_ = "STUB: not implemented"
	return *new(protoreflect.EnumNumber)
}

// Deprecated: Use Effect.Descriptor instead.
func (Effect) EnumDescriptor() ([]byte, []int) { _ = "STUB: not implemented"; return nil, nil }

var File_cerbos_effect_v1_effect_proto protoreflect.FileDescriptor

const file_cerbos_effect_v1_effect_proto_rawDesc = "" +
	"\n" +
	"\x1dcerbos/effect/v1/effect.proto\x12\x10cerbos.effect.v1*X\n" +
	"\x06Effect\x12\x16\n" +
	"\x12EFFECT_UNSPECIFIED\x10\x00\x12\x10\n" +
	"\fEFFECT_ALLOW\x10\x01\x12\x0f\n" +
	"\vEFFECT_DENY\x10\x02\x12\x13\n" +
	"\x0fEFFECT_NO_MATCH\x10\x03Bo\n" +
	"\x18dev.cerbos.api.v1.effectZ<github.com/cerbos/cerbos/api/genpb/cerbos/effect/v1;effectv1\xaa\x02\x14Cerbos.Api.V1.Effectb\x06proto3"

var (
	file_cerbos_effect_v1_effect_proto_rawDescOnce sync.Once
	file_cerbos_effect_v1_effect_proto_rawDescData []byte
)

func file_cerbos_effect_v1_effect_proto_rawDescGZIP() []byte { _ = "STUB: not implemented"; return nil }

var file_cerbos_effect_v1_effect_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_cerbos_effect_v1_effect_proto_goTypes = []any{
	(Effect)(0), // 0: cerbos.effect.v1.Effect
}
var file_cerbos_effect_v1_effect_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init()                                    { file_cerbos_effect_v1_effect_proto_init() }
func file_cerbos_effect_v1_effect_proto_init() { _ = "STUB: not implemented"; return }
