// Code generated by protoc-gen-go-hashpb. DO NOT EDIT.
// protoc-gen-go-hashpb v0.5.0

package telemetryv1

import (
	hash "hash"
	sync "sync"

	durationpb "google.golang.org/protobuf/types/known/durationpb"
)

var hashpb_bufPool = sync.Pool{
	New: func() any { return new([10]byte) },
}

var hashpb_stringKeyPool = sync.Pool{
	New: func() any { return make([]string, 0, 32) },
}

var hashpb_int32KeyPool = sync.Pool{
	New: func() any { return make([]int32, 0, 32) },
}

var hashpb_int64KeyPool = sync.Pool{
	New: func() any { return make([]int64, 0, 32) },
}

var hashpb_uint32KeyPool = sync.Pool{
	New: func() any { return make([]uint32, 0, 32) },
}

var hashpb_uint64KeyPool = sync.Pool{
	New: func() any { return make([]uint64, 0, 32) },
}

func cerbos_telemetry_v1_Event_ApiActivity_hashpb_sum(m *Event_ApiActivity, hasher hash.Hash, ignore map[string]struct{}, b *[10]byte) {
	_ = "STUB: not implemented"
	return
}

func cerbos_telemetry_v1_Event_CountStat_hashpb_sum(m *Event_CountStat, hasher hash.Hash, ignore map[string]struct{}, b *[10]byte) {
	_ = "STUB: not implemented"
	return
}

func cerbos_telemetry_v1_Event_hashpb_sum(m *Event, hasher hash.Hash, ignore map[string]struct{}, b *[10]byte) {
	_ = "STUB: not implemented"
	return
}

func cerbos_telemetry_v1_ServerLaunch_Cerbos_hashpb_sum(m *ServerLaunch_Cerbos, hasher hash.Hash, ignore map[string]struct{}, b *[10]byte) {
	_ = "STUB: not implemented"
	return
}

func cerbos_telemetry_v1_ServerLaunch_Features_AdminApi_hashpb_sum(m *ServerLaunch_Features_AdminApi, hasher hash.Hash, ignore map[string]struct{}, b *[10]byte) {
	_ = "STUB: not implemented"
	return
}

func cerbos_telemetry_v1_ServerLaunch_Features_Audit_hashpb_sum(m *ServerLaunch_Features_Audit, hasher hash.Hash, ignore map[string]struct{}, b *[10]byte) {
	_ = "STUB: not implemented"
	return
}

func cerbos_telemetry_v1_ServerLaunch_Features_Schema_hashpb_sum(m *ServerLaunch_Features_Schema, hasher hash.Hash, ignore map[string]struct{}, b *[10]byte) {
	_ = "STUB: not implemented"
	return
}

func cerbos_telemetry_v1_ServerLaunch_Features_Storage_Blob_hashpb_sum(m *ServerLaunch_Features_Storage_Blob, hasher hash.Hash, ignore map[string]struct{}, b *[10]byte) {
	_ = "STUB: not implemented"
	return
}

func cerbos_telemetry_v1_ServerLaunch_Features_Storage_Bundle_hashpb_sum(m *ServerLaunch_Features_Storage_Bundle, hasher hash.Hash, ignore map[string]struct{}, b *[10]byte) {
	_ = "STUB: not implemented"
	return
}

func cerbos_telemetry_v1_ServerLaunch_Features_Storage_Disk_hashpb_sum(m *ServerLaunch_Features_Storage_Disk, hasher hash.Hash, ignore map[string]struct{}, b *[10]byte) {
	_ = "STUB: not implemented"
	return
}

func cerbos_telemetry_v1_ServerLaunch_Features_Storage_Git_hashpb_sum(m *ServerLaunch_Features_Storage_Git, hasher hash.Hash, ignore map[string]struct{}, b *[10]byte) {
	_ = "STUB: not implemented"
	return
}

func cerbos_telemetry_v1_ServerLaunch_Features_Storage_hashpb_sum(m *ServerLaunch_Features_Storage, hasher hash.Hash, ignore map[string]struct{}, b *[10]byte) {
	_ = "STUB: not implemented"
	return
}

func cerbos_telemetry_v1_ServerLaunch_Features_hashpb_sum(m *ServerLaunch_Features, hasher hash.Hash, ignore map[string]struct{}, b *[10]byte) {
	_ = "STUB: not implemented"
	return
}

func cerbos_telemetry_v1_ServerLaunch_Source_hashpb_sum(m *ServerLaunch_Source, hasher hash.Hash, ignore map[string]struct{}, b *[10]byte) {
	_ = "STUB: not implemented"
	return
}

func cerbos_telemetry_v1_ServerLaunch_Stats_Policy_hashpb_sum(m *ServerLaunch_Stats_Policy, hasher hash.Hash, ignore map[string]struct{}, b *[10]byte) {
	_ = "STUB: not implemented"
	return
}

func cerbos_telemetry_v1_ServerLaunch_Stats_Schema_hashpb_sum(m *ServerLaunch_Stats_Schema, hasher hash.Hash, ignore map[string]struct{}, b *[10]byte) {
	_ = "STUB: not implemented"
	return
}

func cerbos_telemetry_v1_ServerLaunch_Stats_hashpb_sum(m *ServerLaunch_Stats, hasher hash.Hash, ignore map[string]struct{}, b *[10]byte) {
	_ = "STUB: not implemented"
	return
}

func cerbos_telemetry_v1_ServerLaunch_hashpb_sum(m *ServerLaunch, hasher hash.Hash, ignore map[string]struct{}, b *[10]byte) {
	_ = "STUB: not implemented"
	return
}

func cerbos_telemetry_v1_ServerStop_hashpb_sum(m *ServerStop, hasher hash.Hash, ignore map[string]struct{}, b *[10]byte) {
	_ = "STUB: not implemented"
	return
}

func google_protobuf_Duration_hashpb_sum(m *durationpb.Duration, hasher hash.Hash, ignore map[string]struct{}, b *[10]byte) {
	_ = "STUB: not implemented"
	return
}
