// Code generated by protoc-gen-go-vtproto. DO NOT EDIT.
// protoc-gen-go-vtproto version: v0.6.1-0.20250313105119-ba97887b0a25
// source: cerbos/telemetry/v1/telemetry.proto

package telemetryv1

import (
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

func (m *ServerLaunch_Cerbos) MarshalVT() (dAtA []byte, err error) {
	_ = "STUB: not implemented"
	return nil, nil
}

func (m *ServerLaunch_Cerbos) MarshalToVT(dAtA []byte) (int, error) {
	_ = "STUB: not implemented"
	return 0, nil
}

func (m *ServerLaunch_Cerbos) MarshalToSizedBufferVT(dAtA []byte) (int, error) {
	_ = "STUB: not implemented"
	return 0, nil
}

func (m *ServerLaunch_Source) MarshalVT() (dAtA []byte, err error) {
	_ = "STUB: not implemented"
	return nil, nil
}

func (m *ServerLaunch_Source) MarshalToVT(dAtA []byte) (int, error) {
	_ = "STUB: not implemented"
	return 0, nil
}

func (m *ServerLaunch_Source) MarshalToSizedBufferVT(dAtA []byte) (int, error) {
	_ = "STUB: not implemented"
	return 0, nil
}

func (m *ServerLaunch_Features_Audit) MarshalVT() (dAtA []byte, err error) {
	_ = "STUB: not implemented"
	return nil, nil
}

func (m *ServerLaunch_Features_Audit) MarshalToVT(dAtA []byte) (int, error) {
	_ = "STUB: not implemented"
	return 0, nil
}

func (m *ServerLaunch_Features_Audit) MarshalToSizedBufferVT(dAtA []byte) (int, error) {
	_ = "STUB: not implemented"
	return 0, nil
}

func (m *ServerLaunch_Features_Schema) MarshalVT() (dAtA []byte, err error) {
	_ = "STUB: not implemented"
	return nil, nil
}

func (m *ServerLaunch_Features_Schema) MarshalToVT(dAtA []byte) (int, error) {
	_ = "STUB: not implemented"
	return 0, nil
}

func (m *ServerLaunch_Features_Schema) MarshalToSizedBufferVT(dAtA []byte) (int, error) {
	_ = "STUB: not implemented"
	return 0, nil
}

func (m *ServerLaunch_Features_AdminApi) MarshalVT() (dAtA []byte, err error) {
	_ = "STUB: not implemented"
	return nil, nil
}

func (m *ServerLaunch_Features_AdminApi) MarshalToVT(dAtA []byte) (int, error) {
	_ = "STUB: not implemented"
	return 0, nil
}

func (m *ServerLaunch_Features_AdminApi) MarshalToSizedBufferVT(dAtA []byte) (int, error) {
	_ = "STUB: not implemented"
	return 0, nil
}

func (m *ServerLaunch_Features_Storage_Disk) MarshalVT() (dAtA []byte, err error) {
	_ = "STUB: not implemented"
	return nil, nil
}

func (m *ServerLaunch_Features_Storage_Disk) MarshalToVT(dAtA []byte) (int, error) {
	_ = "STUB: not implemented"
	return 0, nil
}

func (m *ServerLaunch_Features_Storage_Disk) MarshalToSizedBufferVT(dAtA []byte) (int, error) {
	_ = "STUB: not implemented"
	return 0, nil
}

func (m *ServerLaunch_Features_Storage_Git) MarshalVT() (dAtA []byte, err error) {
	_ = "STUB: not implemented"
	return nil, nil
}

func (m *ServerLaunch_Features_Storage_Git) MarshalToVT(dAtA []byte) (int, error) {
	_ = "STUB: not implemented"
	return 0, nil
}

func (m *ServerLaunch_Features_Storage_Git) MarshalToSizedBufferVT(dAtA []byte) (int, error) {
	_ = "STUB: not implemented"
	return 0, nil
}

func (m *ServerLaunch_Features_Storage_Blob) MarshalVT() (dAtA []byte, err error) {
	_ = "STUB: not implemented"
	return nil, nil
}

func (m *ServerLaunch_Features_Storage_Blob) MarshalToVT(dAtA []byte) (int, error) {
	_ = "STUB: not implemented"
	return 0, nil
}

func (m *ServerLaunch_Features_Storage_Blob) MarshalToSizedBufferVT(dAtA []byte) (int, error) {
	_ = "STUB: not implemented"
	return 0, nil
}

func (m *ServerLaunch_Features_Storage_Bundle) MarshalVT() (dAtA []byte, err error) {
	_ = "STUB: not implemented"
	return nil, nil
}

func (m *ServerLaunch_Features_Storage_Bundle) MarshalToVT(dAtA []byte) (int, error) {
	_ = "STUB: not implemented"
	return 0, nil
}

func (m *ServerLaunch_Features_Storage_Bundle) MarshalToSizedBufferVT(dAtA []byte) (int, error) {
	_ = "STUB: not implemented"
	return 0, nil
}

func (m *ServerLaunch_Features_Storage) MarshalVT() (dAtA []byte, err error) {
	_ = "STUB: not implemented"
	return nil, nil
}

func (m *ServerLaunch_Features_Storage) MarshalToVT(dAtA []byte) (int, error) {
	_ = "STUB: not implemented"
	return 0, nil
}

func (m *ServerLaunch_Features_Storage) MarshalToSizedBufferVT(dAtA []byte) (int, error) {
	_ = "STUB: not implemented"
	return 0, nil
}

func (m *ServerLaunch_Features_Storage_Disk_) MarshalToVT(dAtA []byte) (int, error) {
	_ = "STUB: not implemented"
	return 0, nil
}

func (m *ServerLaunch_Features_Storage_Disk_) MarshalToSizedBufferVT(dAtA []byte) (int, error) {
	_ = "STUB: not implemented"
	return 0, nil
}

func (m *ServerLaunch_Features_Storage_Git_) MarshalToVT(dAtA []byte) (int, error) {
	_ = "STUB: not implemented"
	return 0, nil
}

func (m *ServerLaunch_Features_Storage_Git_) MarshalToSizedBufferVT(dAtA []byte) (int, error) {
	_ = "STUB: not implemented"
	return 0, nil
}

func (m *ServerLaunch_Features_Storage_Blob_) MarshalToVT(dAtA []byte) (int, error) {
	_ = "STUB: not implemented"
	return 0, nil
}

func (m *ServerLaunch_Features_Storage_Blob_) MarshalToSizedBufferVT(dAtA []byte) (int, error) {
	_ = "STUB: not implemented"
	return 0, nil
}

func (m *ServerLaunch_Features_Storage_Bundle_) MarshalToVT(dAtA []byte) (int, error) {
	_ = "STUB: not implemented"
	return 0, nil
}

func (m *ServerLaunch_Features_Storage_Bundle_) MarshalToSizedBufferVT(dAtA []byte) (int, error) {
	_ = "STUB: not implemented"
	return 0, nil
}

func (m *ServerLaunch_Features) MarshalVT() (dAtA []byte, err error) {
	_ = "STUB: not implemented"
	return nil, nil
}

func (m *ServerLaunch_Features) MarshalToVT(dAtA []byte) (int, error) {
	_ = "STUB: not implemented"
	return 0, nil
}

func (m *ServerLaunch_Features) MarshalToSizedBufferVT(dAtA []byte) (int, error) {
	_ = "STUB: not implemented"
	return 0, nil
}

func (m *ServerLaunch_Stats_Policy) MarshalVT() (dAtA []byte, err error) {
	_ = "STUB: not implemented"
	return nil, nil
}

func (m *ServerLaunch_Stats_Policy) MarshalToVT(dAtA []byte) (int, error) {
	_ = "STUB: not implemented"
	return 0, nil
}

func (m *ServerLaunch_Stats_Policy) MarshalToSizedBufferVT(dAtA []byte) (int, error) {
	_ = "STUB: not implemented"
	return 0, nil
}

func (m *ServerLaunch_Stats_Schema) MarshalVT() (dAtA []byte, err error) {
	_ = "STUB: not implemented"
	return nil, nil
}

func (m *ServerLaunch_Stats_Schema) MarshalToVT(dAtA []byte) (int, error) {
	_ = "STUB: not implemented"
	return 0, nil
}

func (m *ServerLaunch_Stats_Schema) MarshalToSizedBufferVT(dAtA []byte) (int, error) {
	_ = "STUB: not implemented"
	return 0, nil
}

func (m *ServerLaunch_Stats) MarshalVT() (dAtA []byte, err error) {
	_ = "STUB: not implemented"
	return nil, nil
}

func (m *ServerLaunch_Stats) MarshalToVT(dAtA []byte) (int, error) {
	_ = "STUB: not implemented"
	return 0, nil
}

func (m *ServerLaunch_Stats) MarshalToSizedBufferVT(dAtA []byte) (int, error) {
	_ = "STUB: not implemented"
	return 0, nil
}

func (m *ServerLaunch) MarshalVT() (dAtA []byte, err error) {
	_ = "STUB: not implemented"
	return nil, nil
}

func (m *ServerLaunch) MarshalToVT(dAtA []byte) (int, error) {
	_ = "STUB: not implemented"
	return 0, nil
}

func (m *ServerLaunch) MarshalToSizedBufferVT(dAtA []byte) (int, error) {
	_ = "STUB: not implemented"
	return 0, nil
}

func (m *ServerStop) MarshalVT() (dAtA []byte, err error) {
	_ = "STUB: not implemented"
	return nil, nil
}

func (m *ServerStop) MarshalToVT(dAtA []byte) (int, error) {
	_ = "STUB: not implemented"
	return 0, nil
}

func (m *ServerStop) MarshalToSizedBufferVT(dAtA []byte) (int, error) {
	_ = "STUB: not implemented"
	return 0, nil
}

func (m *Event_CountStat) MarshalVT() (dAtA []byte, err error) {
	_ = "STUB: not implemented"
	return nil, nil
}

func (m *Event_CountStat) MarshalToVT(dAtA []byte) (int, error) {
	_ = "STUB: not implemented"
	return 0, nil
}

func (m *Event_CountStat) MarshalToSizedBufferVT(dAtA []byte) (int, error) {
	_ = "STUB: not implemented"
	return 0, nil
}

func (m *Event_ApiActivity) MarshalVT() (dAtA []byte, err error) {
	_ = "STUB: not implemented"
	return nil, nil
}

func (m *Event_ApiActivity) MarshalToVT(dAtA []byte) (int, error) {
	_ = "STUB: not implemented"
	return 0, nil
}

func (m *Event_ApiActivity) MarshalToSizedBufferVT(dAtA []byte) (int, error) {
	_ = "STUB: not implemented"
	return 0, nil
}

func (m *Event) MarshalVT() (dAtA []byte, err error) { _ = "STUB: not implemented"; return nil, nil }

func (m *Event) MarshalToVT(dAtA []byte) (int, error) { _ = "STUB: not implemented"; return 0, nil }

func (m *Event) MarshalToSizedBufferVT(dAtA []byte) (int, error) {
	_ = "STUB: not implemented"
	return 0, nil
}

func (m *Event_ApiActivity_) MarshalToVT(dAtA []byte) (int, error) {
	_ = "STUB: not implemented"
	return 0, nil
}

func (m *Event_ApiActivity_) MarshalToSizedBufferVT(dAtA []byte) (int, error) {
	_ = "STUB: not implemented"
	return 0, nil
}

func (m *ServerLaunch_Cerbos) SizeVT() (n int) { _ = "STUB: not implemented"; return 0 }

func (m *ServerLaunch_Source) SizeVT() (n int) { _ = "STUB: not implemented"; return 0 }

func (m *ServerLaunch_Features_Audit) SizeVT() (n int) { _ = "STUB: not implemented"; return 0 }

func (m *ServerLaunch_Features_Schema) SizeVT() (n int) { _ = "STUB: not implemented"; return 0 }

func (m *ServerLaunch_Features_AdminApi) SizeVT() (n int) { _ = "STUB: not implemented"; return 0 }

func (m *ServerLaunch_Features_Storage_Disk) SizeVT() (n int) { _ = "STUB: not implemented"; return 0 }

func (m *ServerLaunch_Features_Storage_Git) SizeVT() (n int) { _ = "STUB: not implemented"; return 0 }

func (m *ServerLaunch_Features_Storage_Blob) SizeVT() (n int) { _ = "STUB: not implemented"; return 0 }

func (m *ServerLaunch_Features_Storage_Bundle) SizeVT() (n int) {
	_ = "STUB: not implemented"
	return 0
}

func (m *ServerLaunch_Features_Storage) SizeVT() (n int) { _ = "STUB: not implemented"; return 0 }

func (m *ServerLaunch_Features_Storage_Disk_) SizeVT() (n int) { _ = "STUB: not implemented"; return 0 }

func (m *ServerLaunch_Features_Storage_Git_) SizeVT() (n int) { _ = "STUB: not implemented"; return 0 }

func (m *ServerLaunch_Features_Storage_Blob_) SizeVT() (n int) { _ = "STUB: not implemented"; return 0 }

func (m *ServerLaunch_Features_Storage_Bundle_) SizeVT() (n int) {
	_ = "STUB: not implemented"
	return 0
}

func (m *ServerLaunch_Features) SizeVT() (n int) { _ = "STUB: not implemented"; return 0 }

func (m *ServerLaunch_Stats_Policy) SizeVT() (n int) { _ = "STUB: not implemented"; return 0 }

func (m *ServerLaunch_Stats_Schema) SizeVT() (n int) { _ = "STUB: not implemented"; return 0 }

func (m *ServerLaunch_Stats) SizeVT() (n int) { _ = "STUB: not implemented"; return 0 }

func (m *ServerLaunch) SizeVT() (n int) { _ = "STUB: not implemented"; return 0 }

func (m *ServerStop) SizeVT() (n int) { _ = "STUB: not implemented"; return 0 }

func (m *Event_CountStat) SizeVT() (n int) { _ = "STUB: not implemented"; return 0 }

func (m *Event_ApiActivity) SizeVT() (n int) { _ = "STUB: not implemented"; return 0 }

func (m *Event) SizeVT() (n int) { _ = "STUB: not implemented"; return 0 }

func (m *Event_ApiActivity_) SizeVT() (n int) { _ = "STUB: not implemented"; return 0 }

func (m *ServerLaunch_Cerbos) UnmarshalVT(dAtA []byte) error { _ = "STUB: not implemented"; return nil }

func (m *ServerLaunch_Source) UnmarshalVT(dAtA []byte) error { _ = "STUB: not implemented"; return nil }

func (m *ServerLaunch_Features_Audit) UnmarshalVT(dAtA []byte) error {
	_ = "STUB: not implemented"
	return nil
}

func (m *ServerLaunch_Features_Schema) UnmarshalVT(dAtA []byte) error {
	_ = "STUB: not implemented"
	return nil
}

func (m *ServerLaunch_Features_AdminApi) UnmarshalVT(dAtA []byte) error {
	_ = "STUB: not implemented"
	return nil
}

func (m *ServerLaunch_Features_Storage_Disk) UnmarshalVT(dAtA []byte) error {
	_ = "STUB: not implemented"
	return nil
}

func (m *ServerLaunch_Features_Storage_Git) UnmarshalVT(dAtA []byte) error {
	_ = "STUB: not implemented"
	return nil
}

func (m *ServerLaunch_Features_Storage_Blob) UnmarshalVT(dAtA []byte) error {
	_ = "STUB: not implemented"
	return nil
}

func (m *ServerLaunch_Features_Storage_Bundle) UnmarshalVT(dAtA []byte) error {
	_ = "STUB: not implemented"
	return nil
}

func (m *ServerLaunch_Features_Storage) UnmarshalVT(dAtA []byte) error {
	_ = "STUB: not implemented"
	return nil
}

func (m *ServerLaunch_Features) UnmarshalVT(dAtA []byte) error {
	_ = "STUB: not implemented"
	return nil
}

func (m *ServerLaunch_Stats_Policy) UnmarshalVT(dAtA []byte) error {
	_ = "STUB: not implemented"
	return nil
}

func (m *ServerLaunch_Stats_Schema) UnmarshalVT(dAtA []byte) error {
	_ = "STUB: not implemented"
	return nil
}

func (m *ServerLaunch_Stats) UnmarshalVT(dAtA []byte) error { _ = "STUB: not implemented"; return nil }

func (m *ServerLaunch) UnmarshalVT(dAtA []byte) error { _ = "STUB: not implemented"; return nil }

func (m *ServerStop) UnmarshalVT(dAtA []byte) error { _ = "STUB: not implemented"; return nil }

func (m *Event_CountStat) UnmarshalVT(dAtA []byte) error { _ = "STUB: not implemented"; return nil }

func (m *Event_ApiActivity) UnmarshalVT(dAtA []byte) error { _ = "STUB: not implemented"; return nil }

func (m *Event) UnmarshalVT(dAtA []byte) error { _ = "STUB: not implemented"; return nil }
