// Code generated by protoc-gen-go-hashpb. DO NOT EDIT.
// protoc-gen-go-hashpb v0.5.0
// Source: cerbos/private/v1/test.proto

package privatev1

import (
	hash "hash"
)

// HashPB computes a hash of the message using the given hash function
// The ignore set must contain fully-qualified field names (pkg.msg.field) that should be ignored from the hash
func (m *InspectTestCase) HashPB(hasher hash.Hash, ignore map[string]struct{}) {
	_ = "STUB: not implemented"
	return
}

// HashPB computes a hash of the message using the given hash function
// The ignore set must contain fully-qualified field names (pkg.msg.field) that should be ignored from the hash
func (m *InspectTestCase_CompileErrors) HashPB(hasher hash.Hash, ignore map[string]struct{}) {
	_ = "STUB: not implemented"
	return
}

// HashPB computes a hash of the message using the given hash function
// The ignore set must contain fully-qualified field names (pkg.msg.field) that should be ignored from the hash
func (m *InspectTestCase_PoliciesExpectation) HashPB(hasher hash.Hash, ignore map[string]struct{}) {
	_ = "STUB: not implemented"
	return
}

// HashPB computes a hash of the message using the given hash function
// The ignore set must contain fully-qualified field names (pkg.msg.field) that should be ignored from the hash
func (m *InspectTestCase_PolicySetsExpectation) HashPB(hasher hash.Hash, ignore map[string]struct{}) {
	_ = "STUB: not implemented"
	return
}

// HashPB computes a hash of the message using the given hash function
// The ignore set must contain fully-qualified field names (pkg.msg.field) that should be ignored from the hash
func (m *InspectTestCase_RuleTablesExpectation) HashPB(hasher hash.Hash, ignore map[string]struct{}) {
	_ = "STUB: not implemented"
	return
}

// HashPB computes a hash of the message using the given hash function
// The ignore set must contain fully-qualified field names (pkg.msg.field) that should be ignored from the hash
func (m *BlobClonerTestCase) HashPB(hasher hash.Hash, ignore map[string]struct{}) {
	_ = "STUB: not implemented"
	return
}

// HashPB computes a hash of the message using the given hash function
// The ignore set must contain fully-qualified field names (pkg.msg.field) that should be ignored from the hash
func (m *BlobClonerTestCase_File) HashPB(hasher hash.Hash, ignore map[string]struct{}) {
	_ = "STUB: not implemented"
	return
}

// HashPB computes a hash of the message using the given hash function
// The ignore set must contain fully-qualified field names (pkg.msg.field) that should be ignored from the hash
func (m *BlobClonerTestCase_File_AddOrUpdate) HashPB(hasher hash.Hash, ignore map[string]struct{}) {
	_ = "STUB: not implemented"
	return
}

// HashPB computes a hash of the message using the given hash function
// The ignore set must contain fully-qualified field names (pkg.msg.field) that should be ignored from the hash
func (m *BlobClonerTestCase_File_Delete) HashPB(hasher hash.Hash, ignore map[string]struct{}) {
	_ = "STUB: not implemented"
	return
}

// HashPB computes a hash of the message using the given hash function
// The ignore set must contain fully-qualified field names (pkg.msg.field) that should be ignored from the hash
func (m *BlobClonerTestCase_Step) HashPB(hasher hash.Hash, ignore map[string]struct{}) {
	_ = "STUB: not implemented"
	return
}

// HashPB computes a hash of the message using the given hash function
// The ignore set must contain fully-qualified field names (pkg.msg.field) that should be ignored from the hash
func (m *BlobClonerTestCase_Step_Differences) HashPB(hasher hash.Hash, ignore map[string]struct{}) {
	_ = "STUB: not implemented"
	return
}

// HashPB computes a hash of the message using the given hash function
// The ignore set must contain fully-qualified field names (pkg.msg.field) that should be ignored from the hash
func (m *BlobClonerTestCase_Step_Expectation) HashPB(hasher hash.Hash, ignore map[string]struct{}) {
	_ = "STUB: not implemented"
	return
}

// HashPB computes a hash of the message using the given hash function
// The ignore set must contain fully-qualified field names (pkg.msg.field) that should be ignored from the hash
func (m *BlobClonerTestCase_Step_Expectation_Files) HashPB(hasher hash.Hash, ignore map[string]struct{}) {
	_ = "STUB: not implemented"
	return
}

// HashPB computes a hash of the message using the given hash function
// The ignore set must contain fully-qualified field names (pkg.msg.field) that should be ignored from the hash
func (m *BlobClonerTestCase_Step_Expectation_Info) HashPB(hasher hash.Hash, ignore map[string]struct{}) {
	_ = "STUB: not implemented"
	return
}

// HashPB computes a hash of the message using the given hash function
// The ignore set must contain fully-qualified field names (pkg.msg.field) that should be ignored from the hash
func (m *EngineTestCase) HashPB(hasher hash.Hash, ignore map[string]struct{}) {
	_ = "STUB: not implemented"
	return
}

// HashPB computes a hash of the message using the given hash function
// The ignore set must contain fully-qualified field names (pkg.msg.field) that should be ignored from the hash
func (m *ServerTestCase) HashPB(hasher hash.Hash, ignore map[string]struct{}) {
	_ = "STUB: not implemented"
	return
}

// HashPB computes a hash of the message using the given hash function
// The ignore set must contain fully-qualified field names (pkg.msg.field) that should be ignored from the hash
func (m *ServerTestCase_AccessEvaluationCall) HashPB(hasher hash.Hash, ignore map[string]struct{}) {
	_ = "STUB: not implemented"
	return
}

// HashPB computes a hash of the message using the given hash function
// The ignore set must contain fully-qualified field names (pkg.msg.field) that should be ignored from the hash
func (m *ServerTestCase_AccessEvaluationBatchCall) HashPB(hasher hash.Hash, ignore map[string]struct{}) {
	_ = "STUB: not implemented"
	return
}

// HashPB computes a hash of the message using the given hash function
// The ignore set must contain fully-qualified field names (pkg.msg.field) that should be ignored from the hash
func (m *ServerTestCase_PlanResourcesCall) HashPB(hasher hash.Hash, ignore map[string]struct{}) {
	_ = "STUB: not implemented"
	return
}

// HashPB computes a hash of the message using the given hash function
// The ignore set must contain fully-qualified field names (pkg.msg.field) that should be ignored from the hash
func (m *ServerTestCase_CheckResourceSetCall) HashPB(hasher hash.Hash, ignore map[string]struct{}) {
	_ = "STUB: not implemented"
	return
}

// HashPB computes a hash of the message using the given hash function
// The ignore set must contain fully-qualified field names (pkg.msg.field) that should be ignored from the hash
func (m *ServerTestCase_CheckResourceBatchCall) HashPB(hasher hash.Hash, ignore map[string]struct{}) {
	_ = "STUB: not implemented"
	return
}

// HashPB computes a hash of the message using the given hash function
// The ignore set must contain fully-qualified field names (pkg.msg.field) that should be ignored from the hash
func (m *ServerTestCase_CheckResourcesCall) HashPB(hasher hash.Hash, ignore map[string]struct{}) {
	_ = "STUB: not implemented"
	return
}

// HashPB computes a hash of the message using the given hash function
// The ignore set must contain fully-qualified field names (pkg.msg.field) that should be ignored from the hash
func (m *ServerTestCase_PlaygroundValidateCall) HashPB(hasher hash.Hash, ignore map[string]struct{}) {
	_ = "STUB: not implemented"
	return
}

// HashPB computes a hash of the message using the given hash function
// The ignore set must contain fully-qualified field names (pkg.msg.field) that should be ignored from the hash
func (m *ServerTestCase_PlaygroundTestCall) HashPB(hasher hash.Hash, ignore map[string]struct{}) {
	_ = "STUB: not implemented"
	return
}

// HashPB computes a hash of the message using the given hash function
// The ignore set must contain fully-qualified field names (pkg.msg.field) that should be ignored from the hash
func (m *ServerTestCase_PlaygroundEvaluateCall) HashPB(hasher hash.Hash, ignore map[string]struct{}) {
	_ = "STUB: not implemented"
	return
}

// HashPB computes a hash of the message using the given hash function
// The ignore set must contain fully-qualified field names (pkg.msg.field) that should be ignored from the hash
func (m *ServerTestCase_PlaygroundProxyCall) HashPB(hasher hash.Hash, ignore map[string]struct{}) {
	_ = "STUB: not implemented"
	return
}

// HashPB computes a hash of the message using the given hash function
// The ignore set must contain fully-qualified field names (pkg.msg.field) that should be ignored from the hash
func (m *ServerTestCase_AdminAddOrUpdatePolicyCall) HashPB(hasher hash.Hash, ignore map[string]struct{}) {
	_ = "STUB: not implemented"
	return
}

// HashPB computes a hash of the message using the given hash function
// The ignore set must contain fully-qualified field names (pkg.msg.field) that should be ignored from the hash
func (m *ServerTestCase_AdminAddOrUpdateSchemaCall) HashPB(hasher hash.Hash, ignore map[string]struct{}) {
	_ = "STUB: not implemented"
	return
}

// HashPB computes a hash of the message using the given hash function
// The ignore set must contain fully-qualified field names (pkg.msg.field) that should be ignored from the hash
func (m *ServerTestCase_Status) HashPB(hasher hash.Hash, ignore map[string]struct{}) {
	_ = "STUB: not implemented"
	return
}

// HashPB computes a hash of the message using the given hash function
// The ignore set must contain fully-qualified field names (pkg.msg.field) that should be ignored from the hash
func (m *IndexBuilderTestCase) HashPB(hasher hash.Hash, ignore map[string]struct{}) {
	_ = "STUB: not implemented"
	return
}

// HashPB computes a hash of the message using the given hash function
// The ignore set must contain fully-qualified field names (pkg.msg.field) that should be ignored from the hash
func (m *IndexBuilderTestCase_CompilationUnit) HashPB(hasher hash.Hash, ignore map[string]struct{}) {
	_ = "STUB: not implemented"
	return
}

// HashPB computes a hash of the message using the given hash function
// The ignore set must contain fully-qualified field names (pkg.msg.field) that should be ignored from the hash
func (m *CompileTestCase) HashPB(hasher hash.Hash, ignore map[string]struct{}) {
	_ = "STUB: not implemented"
	return
}

// HashPB computes a hash of the message using the given hash function
// The ignore set must contain fully-qualified field names (pkg.msg.field) that should be ignored from the hash
func (m *CompileTestCase_Variables) HashPB(hasher hash.Hash, ignore map[string]struct{}) {
	_ = "STUB: not implemented"
	return
}

// HashPB computes a hash of the message using the given hash function
// The ignore set must contain fully-qualified field names (pkg.msg.field) that should be ignored from the hash
func (m *CompileTestCase_Variables_DerivedRole) HashPB(hasher hash.Hash, ignore map[string]struct{}) {
	_ = "STUB: not implemented"
	return
}

// HashPB computes a hash of the message using the given hash function
// The ignore set must contain fully-qualified field names (pkg.msg.field) that should be ignored from the hash
func (m *CelTestCase) HashPB(hasher hash.Hash, ignore map[string]struct{}) {
	_ = "STUB: not implemented"
	return
}

// HashPB computes a hash of the message using the given hash function
// The ignore set must contain fully-qualified field names (pkg.msg.field) that should be ignored from the hash
func (m *SchemaTestCase) HashPB(hasher hash.Hash, ignore map[string]struct{}) {
	_ = "STUB: not implemented"
	return
}

// HashPB computes a hash of the message using the given hash function
// The ignore set must contain fully-qualified field names (pkg.msg.field) that should be ignored from the hash
func (m *ValidationErrContainer) HashPB(hasher hash.Hash, ignore map[string]struct{}) {
	_ = "STUB: not implemented"
	return
}

// HashPB computes a hash of the message using the given hash function
// The ignore set must contain fully-qualified field names (pkg.msg.field) that should be ignored from the hash
func (m *QueryPlannerTestSuite) HashPB(hasher hash.Hash, ignore map[string]struct{}) {
	_ = "STUB: not implemented"
	return
}

// HashPB computes a hash of the message using the given hash function
// The ignore set must contain fully-qualified field names (pkg.msg.field) that should be ignored from the hash
func (m *QueryPlannerTestSuite_Test) HashPB(hasher hash.Hash, ignore map[string]struct{}) {
	_ = "STUB: not implemented"
	return
}

// HashPB computes a hash of the message using the given hash function
// The ignore set must contain fully-qualified field names (pkg.msg.field) that should be ignored from the hash
func (m *VerifyTestSuiteRunGetTestsTestCase) HashPB(hasher hash.Hash, ignore map[string]struct{}) {
	_ = "STUB: not implemented"
	return
}

// HashPB computes a hash of the message using the given hash function
// The ignore set must contain fully-qualified field names (pkg.msg.field) that should be ignored from the hash
func (m *QueryPlannerFilterTestCase) HashPB(hasher hash.Hash, ignore map[string]struct{}) {
	_ = "STUB: not implemented"
	return
}

// HashPB computes a hash of the message using the given hash function
// The ignore set must contain fully-qualified field names (pkg.msg.field) that should be ignored from the hash
func (m *VerifyTestCase) HashPB(hasher hash.Hash, ignore map[string]struct{}) {
	_ = "STUB: not implemented"
	return
}

// HashPB computes a hash of the message using the given hash function
// The ignore set must contain fully-qualified field names (pkg.msg.field) that should be ignored from the hash
func (m *VerifyTestCase_Config) HashPB(hasher hash.Hash, ignore map[string]struct{}) {
	_ = "STUB: not implemented"
	return
}

// HashPB computes a hash of the message using the given hash function
// The ignore set must contain fully-qualified field names (pkg.msg.field) that should be ignored from the hash
func (m *ProtoYamlTestCase) HashPB(hasher hash.Hash, ignore map[string]struct{}) {
	_ = "STUB: not implemented"
	return
}

// HashPB computes a hash of the message using the given hash function
// The ignore set must contain fully-qualified field names (pkg.msg.field) that should be ignored from the hash
func (m *ProtoYamlTestCase_Want) HashPB(hasher hash.Hash, ignore map[string]struct{}) {
	_ = "STUB: not implemented"
	return
}

// HashPB computes a hash of the message using the given hash function
// The ignore set must contain fully-qualified field names (pkg.msg.field) that should be ignored from the hash
func (m *WellKnownTypes) HashPB(hasher hash.Hash, ignore map[string]struct{}) {
	_ = "STUB: not implemented"
	return
}

// HashPB computes a hash of the message using the given hash function
// The ignore set must contain fully-qualified field names (pkg.msg.field) that should be ignored from the hash
func (m *WellKnownTypes_Nested) HashPB(hasher hash.Hash, ignore map[string]struct{}) {
	_ = "STUB: not implemented"
	return
}

// HashPB computes a hash of the message using the given hash function
// The ignore set must contain fully-qualified field names (pkg.msg.field) that should be ignored from the hash
func (m *TestTracesWrapper) HashPB(hasher hash.Hash, ignore map[string]struct{}) {
	_ = "STUB: not implemented"
	return
}
