// Code generated by protoc-gen-go-hashpb. DO NOT EDIT.
// protoc-gen-go-hashpb v0.5.0

package policyv1

import (
	hash "hash"
	sync "sync"

	v1 "github.com/cerbos/cerbos/api/genpb/cerbos/engine/v1"
	structpb "google.golang.org/protobuf/types/known/structpb"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	wrapperspb "google.golang.org/protobuf/types/known/wrapperspb"
)

var hashpb_bufPool = sync.Pool{
	New: func() any { return new([10]byte) },
}

var hashpb_stringKeyPool = sync.Pool{
	New: func() any { return make([]string, 0, 32) },
}

var hashpb_int32KeyPool = sync.Pool{
	New: func() any { return make([]int32, 0, 32) },
}

var hashpb_int64KeyPool = sync.Pool{
	New: func() any { return make([]int64, 0, 32) },
}

var hashpb_uint32KeyPool = sync.Pool{
	New: func() any { return make([]uint32, 0, 32) },
}

var hashpb_uint64KeyPool = sync.Pool{
	New: func() any { return make([]uint64, 0, 32) },
}

func cerbos_engine_v1_AuxData_hashpb_sum(m *v1.AuxData, hasher hash.Hash, ignore map[string]struct{}, b *[10]byte) {
	_ = "STUB: not implemented"
	return
}

func cerbos_engine_v1_CheckInput_hashpb_sum(m *v1.CheckInput, hasher hash.Hash, ignore map[string]struct{}, b *[10]byte) {
	_ = "STUB: not implemented"
	return
}

func cerbos_engine_v1_OutputEntry_hashpb_sum(m *v1.OutputEntry, hasher hash.Hash, ignore map[string]struct{}, b *[10]byte) {
	_ = "STUB: not implemented"
	return
}

func cerbos_engine_v1_Principal_hashpb_sum(m *v1.Principal, hasher hash.Hash, ignore map[string]struct{}, b *[10]byte) {
	_ = "STUB: not implemented"
	return
}

func cerbos_engine_v1_Resource_hashpb_sum(m *v1.Resource, hasher hash.Hash, ignore map[string]struct{}, b *[10]byte) {
	_ = "STUB: not implemented"
	return
}

func cerbos_engine_v1_TraceBatch_hashpb_sum(m *v1.TraceBatch, hasher hash.Hash, ignore map[string]struct{}, b *[10]byte) {
	_ = "STUB: not implemented"
	return
}

func cerbos_engine_v1_TraceEntry_hashpb_sum(m *v1.TraceEntry, hasher hash.Hash, ignore map[string]struct{}, b *[10]byte) {
	_ = "STUB: not implemented"
	return
}

func cerbos_engine_v1_Trace_Component_Variable_hashpb_sum(m *v1.Trace_Component_Variable, hasher hash.Hash, ignore map[string]struct{}, b *[10]byte) {
	_ = "STUB: not implemented"
	return
}

func cerbos_engine_v1_Trace_Component_hashpb_sum(m *v1.Trace_Component, hasher hash.Hash, ignore map[string]struct{}, b *[10]byte) {
	_ = "STUB: not implemented"
	return
}

func cerbos_engine_v1_Trace_Event_hashpb_sum(m *v1.Trace_Event, hasher hash.Hash, ignore map[string]struct{}, b *[10]byte) {
	_ = "STUB: not implemented"
	return
}

func cerbos_engine_v1_Trace_hashpb_sum(m *v1.Trace, hasher hash.Hash, ignore map[string]struct{}, b *[10]byte) {
	_ = "STUB: not implemented"
	return
}

func cerbos_policy_v1_Condition_hashpb_sum(m *Condition, hasher hash.Hash, ignore map[string]struct{}, b *[10]byte) {
	_ = "STUB: not implemented"
	return
}

func cerbos_policy_v1_Constants_hashpb_sum(m *Constants, hasher hash.Hash, ignore map[string]struct{}, b *[10]byte) {
	_ = "STUB: not implemented"
	return
}

func cerbos_policy_v1_DerivedRoles_hashpb_sum(m *DerivedRoles, hasher hash.Hash, ignore map[string]struct{}, b *[10]byte) {
	_ = "STUB: not implemented"
	return
}

func cerbos_policy_v1_ExportConstants_hashpb_sum(m *ExportConstants, hasher hash.Hash, ignore map[string]struct{}, b *[10]byte) {
	_ = "STUB: not implemented"
	return
}

func cerbos_policy_v1_ExportVariables_hashpb_sum(m *ExportVariables, hasher hash.Hash, ignore map[string]struct{}, b *[10]byte) {
	_ = "STUB: not implemented"
	return
}

func cerbos_policy_v1_Match_ExprList_hashpb_sum(m *Match_ExprList, hasher hash.Hash, ignore map[string]struct{}, b *[10]byte) {
	_ = "STUB: not implemented"
	return
}

func cerbos_policy_v1_Match_hashpb_sum(m *Match, hasher hash.Hash, ignore map[string]struct{}, b *[10]byte) {
	_ = "STUB: not implemented"
	return
}

func cerbos_policy_v1_Metadata_hashpb_sum(m *Metadata, hasher hash.Hash, ignore map[string]struct{}, b *[10]byte) {
	_ = "STUB: not implemented"
	return
}

func cerbos_policy_v1_Output_When_hashpb_sum(m *Output_When, hasher hash.Hash, ignore map[string]struct{}, b *[10]byte) {
	_ = "STUB: not implemented"
	return
}

func cerbos_policy_v1_Output_hashpb_sum(m *Output, hasher hash.Hash, ignore map[string]struct{}, b *[10]byte) {
	_ = "STUB: not implemented"
	return
}

func cerbos_policy_v1_Policy_hashpb_sum(m *Policy, hasher hash.Hash, ignore map[string]struct{}, b *[10]byte) {
	_ = "STUB: not implemented"
	return
}

func cerbos_policy_v1_PrincipalPolicy_hashpb_sum(m *PrincipalPolicy, hasher hash.Hash, ignore map[string]struct{}, b *[10]byte) {
	_ = "STUB: not implemented"
	return
}

func cerbos_policy_v1_PrincipalRule_Action_hashpb_sum(m *PrincipalRule_Action, hasher hash.Hash, ignore map[string]struct{}, b *[10]byte) {
	_ = "STUB: not implemented"
	return
}

func cerbos_policy_v1_PrincipalRule_hashpb_sum(m *PrincipalRule, hasher hash.Hash, ignore map[string]struct{}, b *[10]byte) {
	_ = "STUB: not implemented"
	return
}

func cerbos_policy_v1_ResourcePolicy_hashpb_sum(m *ResourcePolicy, hasher hash.Hash, ignore map[string]struct{}, b *[10]byte) {
	_ = "STUB: not implemented"
	return
}

func cerbos_policy_v1_ResourceRule_hashpb_sum(m *ResourceRule, hasher hash.Hash, ignore map[string]struct{}, b *[10]byte) {
	_ = "STUB: not implemented"
	return
}

func cerbos_policy_v1_RoleDef_hashpb_sum(m *RoleDef, hasher hash.Hash, ignore map[string]struct{}, b *[10]byte) {
	_ = "STUB: not implemented"
	return
}

func cerbos_policy_v1_RolePolicy_hashpb_sum(m *RolePolicy, hasher hash.Hash, ignore map[string]struct{}, b *[10]byte) {
	_ = "STUB: not implemented"
	return
}

func cerbos_policy_v1_RoleRule_hashpb_sum(m *RoleRule, hasher hash.Hash, ignore map[string]struct{}, b *[10]byte) {
	_ = "STUB: not implemented"
	return
}

func cerbos_policy_v1_Schemas_IgnoreWhen_hashpb_sum(m *Schemas_IgnoreWhen, hasher hash.Hash, ignore map[string]struct{}, b *[10]byte) {
	_ = "STUB: not implemented"
	return
}

func cerbos_policy_v1_Schemas_Schema_hashpb_sum(m *Schemas_Schema, hasher hash.Hash, ignore map[string]struct{}, b *[10]byte) {
	_ = "STUB: not implemented"
	return
}

func cerbos_policy_v1_Schemas_hashpb_sum(m *Schemas, hasher hash.Hash, ignore map[string]struct{}, b *[10]byte) {
	_ = "STUB: not implemented"
	return
}

func cerbos_policy_v1_SourceAttributes_hashpb_sum(m *SourceAttributes, hasher hash.Hash, ignore map[string]struct{}, b *[10]byte) {
	_ = "STUB: not implemented"
	return
}

func cerbos_policy_v1_TestFixtureGroup_Principals_hashpb_sum(m *TestFixtureGroup_Principals, hasher hash.Hash, ignore map[string]struct{}, b *[10]byte) {
	_ = "STUB: not implemented"
	return
}

func cerbos_policy_v1_TestFixtureGroup_Resources_hashpb_sum(m *TestFixtureGroup_Resources, hasher hash.Hash, ignore map[string]struct{}, b *[10]byte) {
	_ = "STUB: not implemented"
	return
}

func cerbos_policy_v1_TestFixtureGroup_hashpb_sum(m *TestFixtureGroup, hasher hash.Hash, ignore map[string]struct{}, b *[10]byte) {
	_ = "STUB: not implemented"
	return
}

func cerbos_policy_v1_TestFixture_hashpb_sum(m *TestFixture, hasher hash.Hash, ignore map[string]struct{}, b *[10]byte) {
	_ = "STUB: not implemented"
	return
}

func cerbos_policy_v1_TestOptions_hashpb_sum(m *TestOptions, hasher hash.Hash, ignore map[string]struct{}, b *[10]byte) {
	_ = "STUB: not implemented"
	return
}

func cerbos_policy_v1_TestResults_Action_hashpb_sum(m *TestResults_Action, hasher hash.Hash, ignore map[string]struct{}, b *[10]byte) {
	_ = "STUB: not implemented"
	return
}

func cerbos_policy_v1_TestResults_Details_hashpb_sum(m *TestResults_Details, hasher hash.Hash, ignore map[string]struct{}, b *[10]byte) {
	_ = "STUB: not implemented"
	return
}

func cerbos_policy_v1_TestResults_Failure_hashpb_sum(m *TestResults_Failure, hasher hash.Hash, ignore map[string]struct{}, b *[10]byte) {
	_ = "STUB: not implemented"
	return
}

func cerbos_policy_v1_TestResults_OutputFailure_EvaluationError_hashpb_sum(m *TestResults_OutputFailure_EvaluationError, hasher hash.Hash, ignore map[string]struct{}, b *[10]byte) {
	_ = "STUB: not implemented"
	return
}

func cerbos_policy_v1_TestResults_OutputFailure_MismatchedValue_hashpb_sum(m *TestResults_OutputFailure_MismatchedValue, hasher hash.Hash, ignore map[string]struct{}, b *[10]byte) {
	_ = "STUB: not implemented"
	return
}

func cerbos_policy_v1_TestResults_OutputFailure_MissingValue_hashpb_sum(m *TestResults_OutputFailure_MissingValue, hasher hash.Hash, ignore map[string]struct{}, b *[10]byte) {
	_ = "STUB: not implemented"
	return
}

func cerbos_policy_v1_TestResults_OutputFailure_hashpb_sum(m *TestResults_OutputFailure, hasher hash.Hash, ignore map[string]struct{}, b *[10]byte) {
	_ = "STUB: not implemented"
	return
}

func cerbos_policy_v1_TestResults_Principal_hashpb_sum(m *TestResults_Principal, hasher hash.Hash, ignore map[string]struct{}, b *[10]byte) {
	_ = "STUB: not implemented"
	return
}

func cerbos_policy_v1_TestResults_Resource_hashpb_sum(m *TestResults_Resource, hasher hash.Hash, ignore map[string]struct{}, b *[10]byte) {
	_ = "STUB: not implemented"
	return
}

func cerbos_policy_v1_TestResults_Success_hashpb_sum(m *TestResults_Success, hasher hash.Hash, ignore map[string]struct{}, b *[10]byte) {
	_ = "STUB: not implemented"
	return
}

func cerbos_policy_v1_TestResults_Suite_hashpb_sum(m *TestResults_Suite, hasher hash.Hash, ignore map[string]struct{}, b *[10]byte) {
	_ = "STUB: not implemented"
	return
}

func cerbos_policy_v1_TestResults_Summary_hashpb_sum(m *TestResults_Summary, hasher hash.Hash, ignore map[string]struct{}, b *[10]byte) {
	_ = "STUB: not implemented"
	return
}

func cerbos_policy_v1_TestResults_Tally_hashpb_sum(m *TestResults_Tally, hasher hash.Hash, ignore map[string]struct{}, b *[10]byte) {
	_ = "STUB: not implemented"
	return
}

func cerbos_policy_v1_TestResults_TestCase_hashpb_sum(m *TestResults_TestCase, hasher hash.Hash, ignore map[string]struct{}, b *[10]byte) {
	_ = "STUB: not implemented"
	return
}

func cerbos_policy_v1_TestResults_hashpb_sum(m *TestResults, hasher hash.Hash, ignore map[string]struct{}, b *[10]byte) {
	_ = "STUB: not implemented"
	return
}

func cerbos_policy_v1_TestSuite_hashpb_sum(m *TestSuite, hasher hash.Hash, ignore map[string]struct{}, b *[10]byte) {
	_ = "STUB: not implemented"
	return
}

func cerbos_policy_v1_TestTable_Expectation_hashpb_sum(m *TestTable_Expectation, hasher hash.Hash, ignore map[string]struct{}, b *[10]byte) {
	_ = "STUB: not implemented"
	return
}

func cerbos_policy_v1_TestTable_Input_hashpb_sum(m *TestTable_Input, hasher hash.Hash, ignore map[string]struct{}, b *[10]byte) {
	_ = "STUB: not implemented"
	return
}

func cerbos_policy_v1_TestTable_OutputExpectations_hashpb_sum(m *TestTable_OutputExpectations, hasher hash.Hash, ignore map[string]struct{}, b *[10]byte) {
	_ = "STUB: not implemented"
	return
}

func cerbos_policy_v1_TestTable_hashpb_sum(m *TestTable, hasher hash.Hash, ignore map[string]struct{}, b *[10]byte) {
	_ = "STUB: not implemented"
	return
}

func cerbos_policy_v1_Test_OutputEntries_hashpb_sum(m *Test_OutputEntries, hasher hash.Hash, ignore map[string]struct{}, b *[10]byte) {
	_ = "STUB: not implemented"
	return
}

func cerbos_policy_v1_Test_TestName_hashpb_sum(m *Test_TestName, hasher hash.Hash, ignore map[string]struct{}, b *[10]byte) {
	_ = "STUB: not implemented"
	return
}

func cerbos_policy_v1_Test_hashpb_sum(m *Test, hasher hash.Hash, ignore map[string]struct{}, b *[10]byte) {
	_ = "STUB: not implemented"
	return
}

func cerbos_policy_v1_Variables_hashpb_sum(m *Variables, hasher hash.Hash, ignore map[string]struct{}, b *[10]byte) {
	_ = "STUB: not implemented"
	return
}

func google_protobuf_ListValue_hashpb_sum(m *structpb.ListValue, hasher hash.Hash, ignore map[string]struct{}, b *[10]byte) {
	_ = "STUB: not implemented"
	return
}

func google_protobuf_Struct_hashpb_sum(m *structpb.Struct, hasher hash.Hash, ignore map[string]struct{}, b *[10]byte) {
	_ = "STUB: not implemented"
	return
}

func google_protobuf_Timestamp_hashpb_sum(m *timestamppb.Timestamp, hasher hash.Hash, ignore map[string]struct{}, b *[10]byte) {
	_ = "STUB: not implemented"
	return
}

func google_protobuf_UInt64Value_hashpb_sum(m *wrapperspb.UInt64Value, hasher hash.Hash, ignore map[string]struct{}, b *[10]byte) {
	_ = "STUB: not implemented"
	return
}

func google_protobuf_Value_hashpb_sum(m *structpb.Value, hasher hash.Hash, ignore map[string]struct{}, b *[10]byte) {
	_ = "STUB: not implemented"
	return
}
