// Code generated by protoc-gen-go-vtproto. DO NOT EDIT.
// protoc-gen-go-vtproto version: v0.6.1-0.20250313105119-ba97887b0a25
// source: cerbos/source/v1/source.proto

package sourcev1

import (
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

func (m *Position) MarshalVT() (dAtA []byte, err error) { _ = "STUB: not implemented"; return nil, nil }

func (m *Position) MarshalToVT(dAtA []byte) (int, error) { _ = "STUB: not implemented"; return 0, nil }

func (m *Position) MarshalToSizedBufferVT(dAtA []byte) (int, error) {
	_ = "STUB: not implemented"
	return 0, nil
}

func (m *Error) MarshalVT() (dAtA []byte, err error) { _ = "STUB: not implemented"; return nil, nil }

func (m *Error) MarshalToVT(dAtA []byte) (int, error) { _ = "STUB: not implemented"; return 0, nil }

func (m *Error) MarshalToSizedBufferVT(dAtA []byte) (int, error) {
	_ = "STUB: not implemented"
	return 0, nil
}

func (m *StartPosition) MarshalVT() (dAtA []byte, err error) {
	_ = "STUB: not implemented"
	return nil, nil
}

func (m *StartPosition) MarshalToVT(dAtA []byte) (int, error) {
	_ = "STUB: not implemented"
	return 0, nil
}

func (m *StartPosition) MarshalToSizedBufferVT(dAtA []byte) (int, error) {
	_ = "STUB: not implemented"
	return 0, nil
}

func (m *SourceContext) MarshalVT() (dAtA []byte, err error) {
	_ = "STUB: not implemented"
	return nil, nil
}

func (m *SourceContext) MarshalToVT(dAtA []byte) (int, error) {
	_ = "STUB: not implemented"
	return 0, nil
}

func (m *SourceContext) MarshalToSizedBufferVT(dAtA []byte) (int, error) {
	_ = "STUB: not implemented"
	return 0, nil
}

func (m *PolicyWrapper) MarshalVT() (dAtA []byte, err error) {
	_ = "STUB: not implemented"
	return nil, nil
}

func (m *PolicyWrapper) MarshalToVT(dAtA []byte) (int, error) {
	_ = "STUB: not implemented"
	return 0, nil
}

func (m *PolicyWrapper) MarshalToSizedBufferVT(dAtA []byte) (int, error) {
	_ = "STUB: not implemented"
	return 0, nil
}

func (m *Position) SizeVT() (n int) { _ = "STUB: not implemented"; return 0 }

func (m *Error) SizeVT() (n int) { _ = "STUB: not implemented"; return 0 }

func (m *StartPosition) SizeVT() (n int) { _ = "STUB: not implemented"; return 0 }

func (m *SourceContext) SizeVT() (n int) { _ = "STUB: not implemented"; return 0 }

func (m *PolicyWrapper) SizeVT() (n int) { _ = "STUB: not implemented"; return 0 }

func (m *Position) UnmarshalVT(dAtA []byte) error { _ = "STUB: not implemented"; return nil }

func (m *Error) UnmarshalVT(dAtA []byte) error { _ = "STUB: not implemented"; return nil }

func (m *StartPosition) UnmarshalVT(dAtA []byte) error { _ = "STUB: not implemented"; return nil }

func (m *SourceContext) UnmarshalVT(dAtA []byte) error { _ = "STUB: not implemented"; return nil }

func (m *PolicyWrapper) UnmarshalVT(dAtA []byte) error { _ = "STUB: not implemented"; return nil }
