// Code generated by protoc-gen-go-hashpb. DO NOT EDIT.
// protoc-gen-go-hashpb v0.5.0
// Source: cerbos/source/v1/source.proto

package sourcev1

import (
	hash "hash"
)

// HashPB computes a hash of the message using the given hash function
// The ignore set must contain fully-qualified field names (pkg.msg.field) that should be ignored from the hash
func (m *Position) HashPB(hasher hash.Hash, ignore map[string]struct{}) {
	_ = "STUB: not implemented"
	return
}

// HashPB computes a hash of the message using the given hash function
// The ignore set must contain fully-qualified field names (pkg.msg.field) that should be ignored from the hash
func (m *Error) HashPB(hasher hash.Hash, ignore map[string]struct{}) {
	_ = "STUB: not implemented"
	return
}

// HashPB computes a hash of the message using the given hash function
// The ignore set must contain fully-qualified field names (pkg.msg.field) that should be ignored from the hash
func (m *StartPosition) HashPB(hasher hash.Hash, ignore map[string]struct{}) {
	_ = "STUB: not implemented"
	return
}

// HashPB computes a hash of the message using the given hash function
// The ignore set must contain fully-qualified field names (pkg.msg.field) that should be ignored from the hash
func (m *SourceContext) HashPB(hasher hash.Hash, ignore map[string]struct{}) {
	_ = "STUB: not implemented"
	return
}

// HashPB computes a hash of the message using the given hash function
// The ignore set must contain fully-qualified field names (pkg.msg.field) that should be ignored from the hash
func (m *PolicyWrapper) HashPB(hasher hash.Hash, ignore map[string]struct{}) {
	_ = "STUB: not implemented"
	return
}
