// Copyright 2021-2026 Zenauth Ltd.
// SPDX-License-Identifier: Apache-2.0

// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.2
// - protoc             (unknown)
// source: authzen/authorization/v1/svc.proto

package authorizationv1

import (
	context "context"

	grpc "google.golang.org/grpc"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	AuthorizationService_Metadata_FullMethodName              = "/authzen.authorization.v1.AuthorizationService/Metadata"
	AuthorizationService_AccessEvaluation_FullMethodName      = "/authzen.authorization.v1.AuthorizationService/AccessEvaluation"
	AuthorizationService_AccessEvaluationBatch_FullMethodName = "/authzen.authorization.v1.AuthorizationService/AccessEvaluationBatch"
)

// AuthorizationServiceClient is the client API for AuthorizationService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// AuthZEN Authorization Service
type AuthorizationServiceClient interface {
	// Metadata returns the Policy Decision Point metadata
	Metadata(ctx context.Context, in *MetadataRequest, opts ...grpc.CallOption) (*MetadataResponse, error)
	// Evaluate performs an access evaluation
	AccessEvaluation(ctx context.Context, in *AccessEvaluationRequest, opts ...grpc.CallOption) (*AccessEvaluationResponse, error)
	// Evaluate performs an access evaluation
	AccessEvaluationBatch(ctx context.Context, in *AccessEvaluationBatchRequest, opts ...grpc.CallOption) (*AccessEvaluationBatchResponse, error)
}

type authorizationServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewAuthorizationServiceClient(cc grpc.ClientConnInterface) AuthorizationServiceClient {
	_ = "STUB: not implemented"
	return *new(AuthorizationServiceClient)
}

func (c *authorizationServiceClient) Metadata(ctx context.Context, in *MetadataRequest, opts ...grpc.CallOption) (*MetadataResponse, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

func (c *authorizationServiceClient) AccessEvaluation(ctx context.Context, in *AccessEvaluationRequest, opts ...grpc.CallOption) (*AccessEvaluationResponse, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

func (c *authorizationServiceClient) AccessEvaluationBatch(ctx context.Context, in *AccessEvaluationBatchRequest, opts ...grpc.CallOption) (*AccessEvaluationBatchResponse, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

// AuthorizationServiceServer is the server API for AuthorizationService service.
// All implementations must embed UnimplementedAuthorizationServiceServer
// for forward compatibility.
//
// AuthZEN Authorization Service
type AuthorizationServiceServer interface {
	// Metadata returns the Policy Decision Point metadata
	Metadata(context.Context, *MetadataRequest) (*MetadataResponse, error)
	// Evaluate performs an access evaluation
	AccessEvaluation(context.Context, *AccessEvaluationRequest) (*AccessEvaluationResponse, error)
	// Evaluate performs an access evaluation
	AccessEvaluationBatch(context.Context, *AccessEvaluationBatchRequest) (*AccessEvaluationBatchResponse, error)
	mustEmbedUnimplementedAuthorizationServiceServer()
}

// UnimplementedAuthorizationServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedAuthorizationServiceServer struct{}

func (UnimplementedAuthorizationServiceServer) Metadata(context.Context, *MetadataRequest) (*MetadataResponse, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

func (UnimplementedAuthorizationServiceServer) AccessEvaluation(context.Context, *AccessEvaluationRequest) (*AccessEvaluationResponse, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

func (UnimplementedAuthorizationServiceServer) AccessEvaluationBatch(context.Context, *AccessEvaluationBatchRequest) (*AccessEvaluationBatchResponse, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

func (UnimplementedAuthorizationServiceServer) mustEmbedUnimplementedAuthorizationServiceServer() {
	_ = "STUB: not implemented"
	return
}
func (UnimplementedAuthorizationServiceServer) testEmbeddedByValue() {
	_ = "STUB: not implemented"
	return
}

// UnsafeAuthorizationServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to AuthorizationServiceServer will
// result in compilation errors.
type UnsafeAuthorizationServiceServer interface {
	mustEmbedUnimplementedAuthorizationServiceServer()
}

func RegisterAuthorizationServiceServer(s grpc.ServiceRegistrar, srv AuthorizationServiceServer) {
	_ = "STUB: not implemented"
	// If the following call panics, it indicates UnimplementedAuthorizationServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	return
}

func _AuthorizationService_Metadata_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

func _AuthorizationService_AccessEvaluation_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

func _AuthorizationService_AccessEvaluationBatch_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

// AuthorizationService_ServiceDesc is the grpc.ServiceDesc for AuthorizationService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var AuthorizationService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "authzen.authorization.v1.AuthorizationService",
	HandlerType: (*AuthorizationServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Metadata",
			Handler:    _AuthorizationService_Metadata_Handler,
		},
		{
			MethodName: "AccessEvaluation",
			Handler:    _AuthorizationService_AccessEvaluation_Handler,
		},
		{
			MethodName: "AccessEvaluationBatch",
			Handler:    _AuthorizationService_AccessEvaluationBatch_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "authzen/authorization/v1/svc.proto",
}
