// Code generated by protoc-gen-go-hashpb. DO NOT EDIT.
// protoc-gen-go-hashpb v0.5.0
// Source: cerbos/request/v1/request.proto

package requestv1

import (
	hash "hash"
)

// HashPB computes a hash of the message using the given hash function
// The ignore set must contain fully-qualified field names (pkg.msg.field) that should be ignored from the hash
func (m *PlanResourcesRequest) HashPB(hasher hash.Hash, ignore map[string]struct{}) {
	_ = "STUB: not implemented"
	return
}

// HashPB computes a hash of the message using the given hash function
// The ignore set must contain fully-qualified field names (pkg.msg.field) that should be ignored from the hash
func (m *CheckResourceSetRequest) HashPB(hasher hash.Hash, ignore map[string]struct{}) {
	_ = "STUB: not implemented"
	return
}

// HashPB computes a hash of the message using the given hash function
// The ignore set must contain fully-qualified field names (pkg.msg.field) that should be ignored from the hash
func (m *ResourceSet) HashPB(hasher hash.Hash, ignore map[string]struct{}) {
	_ = "STUB: not implemented"
	return
}

// HashPB computes a hash of the message using the given hash function
// The ignore set must contain fully-qualified field names (pkg.msg.field) that should be ignored from the hash
func (m *AttributesMap) HashPB(hasher hash.Hash, ignore map[string]struct{}) {
	_ = "STUB: not implemented"
	return
}

// HashPB computes a hash of the message using the given hash function
// The ignore set must contain fully-qualified field names (pkg.msg.field) that should be ignored from the hash
func (m *CheckResourceBatchRequest) HashPB(hasher hash.Hash, ignore map[string]struct{}) {
	_ = "STUB: not implemented"
	return
}

// HashPB computes a hash of the message using the given hash function
// The ignore set must contain fully-qualified field names (pkg.msg.field) that should be ignored from the hash
func (m *CheckResourceBatchRequest_BatchEntry) HashPB(hasher hash.Hash, ignore map[string]struct{}) {
	_ = "STUB: not implemented"
	return
}

// HashPB computes a hash of the message using the given hash function
// The ignore set must contain fully-qualified field names (pkg.msg.field) that should be ignored from the hash
func (m *CheckResourcesRequest) HashPB(hasher hash.Hash, ignore map[string]struct{}) {
	_ = "STUB: not implemented"
	return
}

// HashPB computes a hash of the message using the given hash function
// The ignore set must contain fully-qualified field names (pkg.msg.field) that should be ignored from the hash
func (m *CheckResourcesRequest_ResourceEntry) HashPB(hasher hash.Hash, ignore map[string]struct{}) {
	_ = "STUB: not implemented"
	return
}

// HashPB computes a hash of the message using the given hash function
// The ignore set must contain fully-qualified field names (pkg.msg.field) that should be ignored from the hash
func (m *AuxData) HashPB(hasher hash.Hash, ignore map[string]struct{}) {
	_ = "STUB: not implemented"
	return
}

// HashPB computes a hash of the message using the given hash function
// The ignore set must contain fully-qualified field names (pkg.msg.field) that should be ignored from the hash
func (m *AuxData_JWT) HashPB(hasher hash.Hash, ignore map[string]struct{}) {
	_ = "STUB: not implemented"
	return
}

// HashPB computes a hash of the message using the given hash function
// The ignore set must contain fully-qualified field names (pkg.msg.field) that should be ignored from the hash
func (m *File) HashPB(hasher hash.Hash, ignore map[string]struct{}) {
	_ = "STUB: not implemented"
	return
}

// HashPB computes a hash of the message using the given hash function
// The ignore set must contain fully-qualified field names (pkg.msg.field) that should be ignored from the hash
func (m *PlaygroundValidateRequest) HashPB(hasher hash.Hash, ignore map[string]struct{}) {
	_ = "STUB: not implemented"
	return
}

// HashPB computes a hash of the message using the given hash function
// The ignore set must contain fully-qualified field names (pkg.msg.field) that should be ignored from the hash
func (m *PlaygroundTestRequest) HashPB(hasher hash.Hash, ignore map[string]struct{}) {
	_ = "STUB: not implemented"
	return
}

// HashPB computes a hash of the message using the given hash function
// The ignore set must contain fully-qualified field names (pkg.msg.field) that should be ignored from the hash
func (m *PlaygroundEvaluateRequest) HashPB(hasher hash.Hash, ignore map[string]struct{}) {
	_ = "STUB: not implemented"
	return
}

// HashPB computes a hash of the message using the given hash function
// The ignore set must contain fully-qualified field names (pkg.msg.field) that should be ignored from the hash
func (m *PlaygroundProxyRequest) HashPB(hasher hash.Hash, ignore map[string]struct{}) {
	_ = "STUB: not implemented"
	return
}

// HashPB computes a hash of the message using the given hash function
// The ignore set must contain fully-qualified field names (pkg.msg.field) that should be ignored from the hash
func (m *AddOrUpdatePolicyRequest) HashPB(hasher hash.Hash, ignore map[string]struct{}) {
	_ = "STUB: not implemented"
	return
}

// HashPB computes a hash of the message using the given hash function
// The ignore set must contain fully-qualified field names (pkg.msg.field) that should be ignored from the hash
func (m *ListAuditLogEntriesRequest) HashPB(hasher hash.Hash, ignore map[string]struct{}) {
	_ = "STUB: not implemented"
	return
}

// HashPB computes a hash of the message using the given hash function
// The ignore set must contain fully-qualified field names (pkg.msg.field) that should be ignored from the hash
func (m *ListAuditLogEntriesRequest_TimeRange) HashPB(hasher hash.Hash, ignore map[string]struct{}) {
	_ = "STUB: not implemented"
	return
}

// HashPB computes a hash of the message using the given hash function
// The ignore set must contain fully-qualified field names (pkg.msg.field) that should be ignored from the hash
func (m *ListPoliciesRequest) HashPB(hasher hash.Hash, ignore map[string]struct{}) {
	_ = "STUB: not implemented"
	return
}

// HashPB computes a hash of the message using the given hash function
// The ignore set must contain fully-qualified field names (pkg.msg.field) that should be ignored from the hash
func (m *GetPolicyRequest) HashPB(hasher hash.Hash, ignore map[string]struct{}) {
	_ = "STUB: not implemented"
	return
}

// HashPB computes a hash of the message using the given hash function
// The ignore set must contain fully-qualified field names (pkg.msg.field) that should be ignored from the hash
func (m *DeletePolicyRequest) HashPB(hasher hash.Hash, ignore map[string]struct{}) {
	_ = "STUB: not implemented"
	return
}

// HashPB computes a hash of the message using the given hash function
// The ignore set must contain fully-qualified field names (pkg.msg.field) that should be ignored from the hash
func (m *DisablePolicyRequest) HashPB(hasher hash.Hash, ignore map[string]struct{}) {
	_ = "STUB: not implemented"
	return
}

// HashPB computes a hash of the message using the given hash function
// The ignore set must contain fully-qualified field names (pkg.msg.field) that should be ignored from the hash
func (m *EnablePolicyRequest) HashPB(hasher hash.Hash, ignore map[string]struct{}) {
	_ = "STUB: not implemented"
	return
}

// HashPB computes a hash of the message using the given hash function
// The ignore set must contain fully-qualified field names (pkg.msg.field) that should be ignored from the hash
func (m *InspectPoliciesRequest) HashPB(hasher hash.Hash, ignore map[string]struct{}) {
	_ = "STUB: not implemented"
	return
}

// HashPB computes a hash of the message using the given hash function
// The ignore set must contain fully-qualified field names (pkg.msg.field) that should be ignored from the hash
func (m *AddOrUpdateSchemaRequest) HashPB(hasher hash.Hash, ignore map[string]struct{}) {
	_ = "STUB: not implemented"
	return
}

// HashPB computes a hash of the message using the given hash function
// The ignore set must contain fully-qualified field names (pkg.msg.field) that should be ignored from the hash
func (m *GetSchemaRequest) HashPB(hasher hash.Hash, ignore map[string]struct{}) {
	_ = "STUB: not implemented"
	return
}

// HashPB computes a hash of the message using the given hash function
// The ignore set must contain fully-qualified field names (pkg.msg.field) that should be ignored from the hash
func (m *DeleteSchemaRequest) HashPB(hasher hash.Hash, ignore map[string]struct{}) {
	_ = "STUB: not implemented"
	return
}

// HashPB computes a hash of the message using the given hash function
// The ignore set must contain fully-qualified field names (pkg.msg.field) that should be ignored from the hash
func (m *ReloadStoreRequest) HashPB(hasher hash.Hash, ignore map[string]struct{}) {
	_ = "STUB: not implemented"
	return
}

// HashPB computes a hash of the message using the given hash function
// The ignore set must contain fully-qualified field names (pkg.msg.field) that should be ignored from the hash
func (m *PurgeStoreRevisionsRequest) HashPB(hasher hash.Hash, ignore map[string]struct{}) {
	_ = "STUB: not implemented"
	return
}
