// Code generated by protoc-gen-go-hashpb. DO NOT EDIT.
// protoc-gen-go-hashpb v0.5.0

package runtimev1

import (
	hash "hash"
	sync "sync"

	v1 "github.com/cerbos/cerbos/api/genpb/cerbos/policy/v1"
	v11 "github.com/cerbos/cerbos/api/genpb/cerbos/source/v1"
	v1alpha1 "google.golang.org/genproto/googleapis/api/expr/v1alpha1"
	durationpb "google.golang.org/protobuf/types/known/durationpb"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
	structpb "google.golang.org/protobuf/types/known/structpb"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
)

var hashpb_bufPool = sync.Pool{
	New: func() any { return new([10]byte) },
}

var hashpb_stringKeyPool = sync.Pool{
	New: func() any { return make([]string, 0, 32) },
}

var hashpb_int32KeyPool = sync.Pool{
	New: func() any { return make([]int32, 0, 32) },
}

var hashpb_int64KeyPool = sync.Pool{
	New: func() any { return make([]int64, 0, 32) },
}

var hashpb_uint32KeyPool = sync.Pool{
	New: func() any { return make([]uint32, 0, 32) },
}

var hashpb_uint64KeyPool = sync.Pool{
	New: func() any { return make([]uint64, 0, 32) },
}

func cerbos_policy_v1_Schemas_IgnoreWhen_hashpb_sum(m *v1.Schemas_IgnoreWhen, hasher hash.Hash, ignore map[string]struct{}, b *[10]byte) {
	_ = "STUB: not implemented"
	return
}

func cerbos_policy_v1_Schemas_Schema_hashpb_sum(m *v1.Schemas_Schema, hasher hash.Hash, ignore map[string]struct{}, b *[10]byte) {
	_ = "STUB: not implemented"
	return
}

func cerbos_policy_v1_Schemas_hashpb_sum(m *v1.Schemas, hasher hash.Hash, ignore map[string]struct{}, b *[10]byte) {
	_ = "STUB: not implemented"
	return
}

func cerbos_policy_v1_SourceAttributes_hashpb_sum(m *v1.SourceAttributes, hasher hash.Hash, ignore map[string]struct{}, b *[10]byte) {
	_ = "STUB: not implemented"
	return
}

func cerbos_runtime_v1_BitmapIndex_AllowActions_hashpb_sum(m *BitmapIndex_AllowActions, hasher hash.Hash, ignore map[string]struct{}, b *[10]byte) {
	_ = "STUB: not implemented"
	return
}

func cerbos_runtime_v1_BitmapIndex_Binding_hashpb_sum(m *BitmapIndex_Binding, hasher hash.Hash, ignore map[string]struct{}, b *[10]byte) {
	_ = "STUB: not implemented"
	return
}

func cerbos_runtime_v1_BitmapIndex_Entry_hashpb_sum(m *BitmapIndex_Entry, hasher hash.Hash, ignore map[string]struct{}, b *[10]byte) {
	_ = "STUB: not implemented"
	return
}

func cerbos_runtime_v1_BitmapIndex_FunctionalCore_hashpb_sum(m *BitmapIndex_FunctionalCore, hasher hash.Hash, ignore map[string]struct{}, b *[10]byte) {
	_ = "STUB: not implemented"
	return
}

func cerbos_runtime_v1_BitmapIndex_GlobDimension_hashpb_sum(m *BitmapIndex_GlobDimension, hasher hash.Hash, ignore map[string]struct{}, b *[10]byte) {
	_ = "STUB: not implemented"
	return
}

func cerbos_runtime_v1_BitmapIndex_Parents_hashpb_sum(m *BitmapIndex_Parents, hasher hash.Hash, ignore map[string]struct{}, b *[10]byte) {
	_ = "STUB: not implemented"
	return
}

func cerbos_runtime_v1_BitmapIndex_RoleParents_hashpb_sum(m *BitmapIndex_RoleParents, hasher hash.Hash, ignore map[string]struct{}, b *[10]byte) {
	_ = "STUB: not implemented"
	return
}

func cerbos_runtime_v1_BitmapIndex_hashpb_sum(m *BitmapIndex, hasher hash.Hash, ignore map[string]struct{}, b *[10]byte) {
	_ = "STUB: not implemented"
	return
}

func cerbos_runtime_v1_CompileErrors_Err_hashpb_sum(m *CompileErrors_Err, hasher hash.Hash, ignore map[string]struct{}, b *[10]byte) {
	_ = "STUB: not implemented"
	return
}

func cerbos_runtime_v1_CompileErrors_hashpb_sum(m *CompileErrors, hasher hash.Hash, ignore map[string]struct{}, b *[10]byte) {
	_ = "STUB: not implemented"
	return
}

func cerbos_runtime_v1_Condition_ExprList_hashpb_sum(m *Condition_ExprList, hasher hash.Hash, ignore map[string]struct{}, b *[10]byte) {
	_ = "STUB: not implemented"
	return
}

func cerbos_runtime_v1_Condition_hashpb_sum(m *Condition, hasher hash.Hash, ignore map[string]struct{}, b *[10]byte) {
	_ = "STUB: not implemented"
	return
}

func cerbos_runtime_v1_Errors_hashpb_sum(m *Errors, hasher hash.Hash, ignore map[string]struct{}, b *[10]byte) {
	_ = "STUB: not implemented"
	return
}

func cerbos_runtime_v1_Expr_hashpb_sum(m *Expr, hasher hash.Hash, ignore map[string]struct{}, b *[10]byte) {
	_ = "STUB: not implemented"
	return
}

func cerbos_runtime_v1_IndexBuildErrors_Disabled_hashpb_sum(m *IndexBuildErrors_Disabled, hasher hash.Hash, ignore map[string]struct{}, b *[10]byte) {
	_ = "STUB: not implemented"
	return
}

func cerbos_runtime_v1_IndexBuildErrors_DuplicateDef_hashpb_sum(m *IndexBuildErrors_DuplicateDef, hasher hash.Hash, ignore map[string]struct{}, b *[10]byte) {
	_ = "STUB: not implemented"
	return
}

func cerbos_runtime_v1_IndexBuildErrors_LoadFailure_hashpb_sum(m *IndexBuildErrors_LoadFailure, hasher hash.Hash, ignore map[string]struct{}, b *[10]byte) {
	_ = "STUB: not implemented"
	return
}

func cerbos_runtime_v1_IndexBuildErrors_MissingImport_hashpb_sum(m *IndexBuildErrors_MissingImport, hasher hash.Hash, ignore map[string]struct{}, b *[10]byte) {
	_ = "STUB: not implemented"
	return
}

func cerbos_runtime_v1_IndexBuildErrors_MissingScope_hashpb_sum(m *IndexBuildErrors_MissingScope, hasher hash.Hash, ignore map[string]struct{}, b *[10]byte) {
	_ = "STUB: not implemented"
	return
}

func cerbos_runtime_v1_IndexBuildErrors_ScopePermissionsConflicts_hashpb_sum(m *IndexBuildErrors_ScopePermissionsConflicts, hasher hash.Hash, ignore map[string]struct{}, b *[10]byte) {
	_ = "STUB: not implemented"
	return
}

func cerbos_runtime_v1_IndexBuildErrors_hashpb_sum(m *IndexBuildErrors, hasher hash.Hash, ignore map[string]struct{}, b *[10]byte) {
	_ = "STUB: not implemented"
	return
}

func cerbos_runtime_v1_Output_When_hashpb_sum(m *Output_When, hasher hash.Hash, ignore map[string]struct{}, b *[10]byte) {
	_ = "STUB: not implemented"
	return
}

func cerbos_runtime_v1_Output_hashpb_sum(m *Output, hasher hash.Hash, ignore map[string]struct{}, b *[10]byte) {
	_ = "STUB: not implemented"
	return
}

func cerbos_runtime_v1_RuleTableMetadata_hashpb_sum(m *RuleTableMetadata, hasher hash.Hash, ignore map[string]struct{}, b *[10]byte) {
	_ = "STUB: not implemented"
	return
}

func cerbos_runtime_v1_RuleTable_JSONSchema_hashpb_sum(m *RuleTable_JSONSchema, hasher hash.Hash, ignore map[string]struct{}, b *[10]byte) {
	_ = "STUB: not implemented"
	return
}

func cerbos_runtime_v1_RuleTable_Manifest_hashpb_sum(m *RuleTable_Manifest, hasher hash.Hash, ignore map[string]struct{}, b *[10]byte) {
	_ = "STUB: not implemented"
	return
}

func cerbos_runtime_v1_RuleTable_PolicyDerivedRoles_hashpb_sum(m *RuleTable_PolicyDerivedRoles, hasher hash.Hash, ignore map[string]struct{}, b *[10]byte) {
	_ = "STUB: not implemented"
	return
}

func cerbos_runtime_v1_RuleTable_RoleParentRoles_ParentRoles_hashpb_sum(m *RuleTable_RoleParentRoles_ParentRoles, hasher hash.Hash, ignore map[string]struct{}, b *[10]byte) {
	_ = "STUB: not implemented"
	return
}

func cerbos_runtime_v1_RuleTable_RoleParentRoles_hashpb_sum(m *RuleTable_RoleParentRoles, hasher hash.Hash, ignore map[string]struct{}, b *[10]byte) {
	_ = "STUB: not implemented"
	return
}

func cerbos_runtime_v1_RuleTable_RuleRow_AllowActions_hashpb_sum(m *RuleTable_RuleRow_AllowActions, hasher hash.Hash, ignore map[string]struct{}, b *[10]byte) {
	_ = "STUB: not implemented"
	return
}

func cerbos_runtime_v1_RuleTable_RuleRow_Params_hashpb_sum(m *RuleTable_RuleRow_Params, hasher hash.Hash, ignore map[string]struct{}, b *[10]byte) {
	_ = "STUB: not implemented"
	return
}

func cerbos_runtime_v1_RuleTable_RuleRow_hashpb_sum(m *RuleTable_RuleRow, hasher hash.Hash, ignore map[string]struct{}, b *[10]byte) {
	_ = "STUB: not implemented"
	return
}

func cerbos_runtime_v1_RuleTable_hashpb_sum(m *RuleTable, hasher hash.Hash, ignore map[string]struct{}, b *[10]byte) {
	_ = "STUB: not implemented"
	return
}

func cerbos_runtime_v1_RunnableDerivedRole_hashpb_sum(m *RunnableDerivedRole, hasher hash.Hash, ignore map[string]struct{}, b *[10]byte) {
	_ = "STUB: not implemented"
	return
}

func cerbos_runtime_v1_RunnableDerivedRolesSet_Metadata_hashpb_sum(m *RunnableDerivedRolesSet_Metadata, hasher hash.Hash, ignore map[string]struct{}, b *[10]byte) {
	_ = "STUB: not implemented"
	return
}

func cerbos_runtime_v1_RunnableDerivedRolesSet_hashpb_sum(m *RunnableDerivedRolesSet, hasher hash.Hash, ignore map[string]struct{}, b *[10]byte) {
	_ = "STUB: not implemented"
	return
}

func cerbos_runtime_v1_RunnablePolicySet_hashpb_sum(m *RunnablePolicySet, hasher hash.Hash, ignore map[string]struct{}, b *[10]byte) {
	_ = "STUB: not implemented"
	return
}

func cerbos_runtime_v1_RunnablePrincipalPolicySet_Metadata_hashpb_sum(m *RunnablePrincipalPolicySet_Metadata, hasher hash.Hash, ignore map[string]struct{}, b *[10]byte) {
	_ = "STUB: not implemented"
	return
}

func cerbos_runtime_v1_RunnablePrincipalPolicySet_Policy_ActionRule_hashpb_sum(m *RunnablePrincipalPolicySet_Policy_ActionRule, hasher hash.Hash, ignore map[string]struct{}, b *[10]byte) {
	_ = "STUB: not implemented"
	return
}

func cerbos_runtime_v1_RunnablePrincipalPolicySet_Policy_ResourceRules_hashpb_sum(m *RunnablePrincipalPolicySet_Policy_ResourceRules, hasher hash.Hash, ignore map[string]struct{}, b *[10]byte) {
	_ = "STUB: not implemented"
	return
}

func cerbos_runtime_v1_RunnablePrincipalPolicySet_Policy_hashpb_sum(m *RunnablePrincipalPolicySet_Policy, hasher hash.Hash, ignore map[string]struct{}, b *[10]byte) {
	_ = "STUB: not implemented"
	return
}

func cerbos_runtime_v1_RunnablePrincipalPolicySet_hashpb_sum(m *RunnablePrincipalPolicySet, hasher hash.Hash, ignore map[string]struct{}, b *[10]byte) {
	_ = "STUB: not implemented"
	return
}

func cerbos_runtime_v1_RunnableResourcePolicySet_Metadata_hashpb_sum(m *RunnableResourcePolicySet_Metadata, hasher hash.Hash, ignore map[string]struct{}, b *[10]byte) {
	_ = "STUB: not implemented"
	return
}

func cerbos_runtime_v1_RunnableResourcePolicySet_Policy_Rule_hashpb_sum(m *RunnableResourcePolicySet_Policy_Rule, hasher hash.Hash, ignore map[string]struct{}, b *[10]byte) {
	_ = "STUB: not implemented"
	return
}

func cerbos_runtime_v1_RunnableResourcePolicySet_Policy_hashpb_sum(m *RunnableResourcePolicySet_Policy, hasher hash.Hash, ignore map[string]struct{}, b *[10]byte) {
	_ = "STUB: not implemented"
	return
}

func cerbos_runtime_v1_RunnableResourcePolicySet_hashpb_sum(m *RunnableResourcePolicySet, hasher hash.Hash, ignore map[string]struct{}, b *[10]byte) {
	_ = "STUB: not implemented"
	return
}

func cerbos_runtime_v1_RunnableRolePolicySet_Metadata_hashpb_sum(m *RunnableRolePolicySet_Metadata, hasher hash.Hash, ignore map[string]struct{}, b *[10]byte) {
	_ = "STUB: not implemented"
	return
}

func cerbos_runtime_v1_RunnableRolePolicySet_RuleList_hashpb_sum(m *RunnableRolePolicySet_RuleList, hasher hash.Hash, ignore map[string]struct{}, b *[10]byte) {
	_ = "STUB: not implemented"
	return
}

func cerbos_runtime_v1_RunnableRolePolicySet_Rule_hashpb_sum(m *RunnableRolePolicySet_Rule, hasher hash.Hash, ignore map[string]struct{}, b *[10]byte) {
	_ = "STUB: not implemented"
	return
}

func cerbos_runtime_v1_RunnableRolePolicySet_hashpb_sum(m *RunnableRolePolicySet, hasher hash.Hash, ignore map[string]struct{}, b *[10]byte) {
	_ = "STUB: not implemented"
	return
}

func cerbos_runtime_v1_RunnableVariablesSet_Metadata_hashpb_sum(m *RunnableVariablesSet_Metadata, hasher hash.Hash, ignore map[string]struct{}, b *[10]byte) {
	_ = "STUB: not implemented"
	return
}

func cerbos_runtime_v1_RunnableVariablesSet_hashpb_sum(m *RunnableVariablesSet, hasher hash.Hash, ignore map[string]struct{}, b *[10]byte) {
	_ = "STUB: not implemented"
	return
}

func cerbos_runtime_v1_Variable_hashpb_sum(m *Variable, hasher hash.Hash, ignore map[string]struct{}, b *[10]byte) {
	_ = "STUB: not implemented"
	return
}

func cerbos_source_v1_Error_hashpb_sum(m *v11.Error, hasher hash.Hash, ignore map[string]struct{}, b *[10]byte) {
	_ = "STUB: not implemented"
	return
}

func cerbos_source_v1_Position_hashpb_sum(m *v11.Position, hasher hash.Hash, ignore map[string]struct{}, b *[10]byte) {
	_ = "STUB: not implemented"
	return
}

func google_api_expr_v1alpha1_CheckedExpr_hashpb_sum(m *v1alpha1.CheckedExpr, hasher hash.Hash, ignore map[string]struct{}, b *[10]byte) {
	_ = "STUB: not implemented"
	return
}

func google_api_expr_v1alpha1_Constant_hashpb_sum(m *v1alpha1.Constant, hasher hash.Hash, ignore map[string]struct{}, b *[10]byte) {
	_ = "STUB: not implemented"
	return
}

func google_api_expr_v1alpha1_Expr_Call_hashpb_sum(m *v1alpha1.Expr_Call, hasher hash.Hash, ignore map[string]struct{}, b *[10]byte) {
	_ = "STUB: not implemented"
	return
}

func google_api_expr_v1alpha1_Expr_Comprehension_hashpb_sum(m *v1alpha1.Expr_Comprehension, hasher hash.Hash, ignore map[string]struct{}, b *[10]byte) {
	_ = "STUB: not implemented"
	return
}

func google_api_expr_v1alpha1_Expr_CreateList_hashpb_sum(m *v1alpha1.Expr_CreateList, hasher hash.Hash, ignore map[string]struct{}, b *[10]byte) {
	_ = "STUB: not implemented"
	return
}

func google_api_expr_v1alpha1_Expr_CreateStruct_Entry_hashpb_sum(m *v1alpha1.Expr_CreateStruct_Entry, hasher hash.Hash, ignore map[string]struct{}, b *[10]byte) {
	_ = "STUB: not implemented"
	return
}

func google_api_expr_v1alpha1_Expr_CreateStruct_hashpb_sum(m *v1alpha1.Expr_CreateStruct, hasher hash.Hash, ignore map[string]struct{}, b *[10]byte) {
	_ = "STUB: not implemented"
	return
}

func google_api_expr_v1alpha1_Expr_Ident_hashpb_sum(m *v1alpha1.Expr_Ident, hasher hash.Hash, ignore map[string]struct{}, b *[10]byte) {
	_ = "STUB: not implemented"
	return
}

func google_api_expr_v1alpha1_Expr_Select_hashpb_sum(m *v1alpha1.Expr_Select, hasher hash.Hash, ignore map[string]struct{}, b *[10]byte) {
	_ = "STUB: not implemented"
	return
}

func google_api_expr_v1alpha1_Expr_hashpb_sum(m *v1alpha1.Expr, hasher hash.Hash, ignore map[string]struct{}, b *[10]byte) {
	_ = "STUB: not implemented"
	return
}

func google_api_expr_v1alpha1_Reference_hashpb_sum(m *v1alpha1.Reference, hasher hash.Hash, ignore map[string]struct{}, b *[10]byte) {
	_ = "STUB: not implemented"
	return
}

func google_api_expr_v1alpha1_SourceInfo_Extension_Version_hashpb_sum(m *v1alpha1.SourceInfo_Extension_Version, hasher hash.Hash, ignore map[string]struct{}, b *[10]byte) {
	_ = "STUB: not implemented"
	return
}

func google_api_expr_v1alpha1_SourceInfo_Extension_hashpb_sum(m *v1alpha1.SourceInfo_Extension, hasher hash.Hash, ignore map[string]struct{}, b *[10]byte) {
	_ = "STUB: not implemented"
	return
}

func google_api_expr_v1alpha1_SourceInfo_hashpb_sum(m *v1alpha1.SourceInfo, hasher hash.Hash, ignore map[string]struct{}, b *[10]byte) {
	_ = "STUB: not implemented"
	return
}

func google_api_expr_v1alpha1_Type_AbstractType_hashpb_sum(m *v1alpha1.Type_AbstractType, hasher hash.Hash, ignore map[string]struct{}, b *[10]byte) {
	_ = "STUB: not implemented"
	return
}

func google_api_expr_v1alpha1_Type_FunctionType_hashpb_sum(m *v1alpha1.Type_FunctionType, hasher hash.Hash, ignore map[string]struct{}, b *[10]byte) {
	_ = "STUB: not implemented"
	return
}

func google_api_expr_v1alpha1_Type_ListType_hashpb_sum(m *v1alpha1.Type_ListType, hasher hash.Hash, ignore map[string]struct{}, b *[10]byte) {
	_ = "STUB: not implemented"
	return
}

func google_api_expr_v1alpha1_Type_MapType_hashpb_sum(m *v1alpha1.Type_MapType, hasher hash.Hash, ignore map[string]struct{}, b *[10]byte) {
	_ = "STUB: not implemented"
	return
}

func google_api_expr_v1alpha1_Type_hashpb_sum(m *v1alpha1.Type, hasher hash.Hash, ignore map[string]struct{}, b *[10]byte) {
	_ = "STUB: not implemented"
	return
}

func google_protobuf_Duration_hashpb_sum(m *durationpb.Duration, hasher hash.Hash, ignore map[string]struct{}, b *[10]byte) {
	_ = "STUB: not implemented"
	return
}

func google_protobuf_Empty_hashpb_sum(m *emptypb.Empty, hasher hash.Hash, ignore map[string]struct{}, b *[10]byte) {
	_ = "STUB: not implemented"
	return
}

func google_protobuf_ListValue_hashpb_sum(m *structpb.ListValue, hasher hash.Hash, ignore map[string]struct{}, b *[10]byte) {
	_ = "STUB: not implemented"
	return
}

func google_protobuf_Struct_hashpb_sum(m *structpb.Struct, hasher hash.Hash, ignore map[string]struct{}, b *[10]byte) {
	_ = "STUB: not implemented"
	return
}

func google_protobuf_Timestamp_hashpb_sum(m *timestamppb.Timestamp, hasher hash.Hash, ignore map[string]struct{}, b *[10]byte) {
	_ = "STUB: not implemented"
	return
}

func google_protobuf_Value_hashpb_sum(m *structpb.Value, hasher hash.Hash, ignore map[string]struct{}, b *[10]byte) {
	_ = "STUB: not implemented"
	return
}
