// Code generated by protoc-gen-go-vtproto. DO NOT EDIT.
// protoc-gen-go-vtproto version: v0.6.1-0.20250313105119-ba97887b0a25
// source: cerbos/runtime/v1/runtime.proto

package runtimev1

import (
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

func (m *RunnablePolicySet) MarshalVT() (dAtA []byte, err error) {
	_ = "STUB: not implemented"
	return nil, nil
}

func (m *RunnablePolicySet) MarshalToVT(dAtA []byte) (int, error) {
	_ = "STUB: not implemented"
	return 0, nil
}

func (m *RunnablePolicySet) MarshalToSizedBufferVT(dAtA []byte) (int, error) {
	_ = "STUB: not implemented"
	return 0, nil
}

func (m *RunnablePolicySet_ResourcePolicy) MarshalToVT(dAtA []byte) (int, error) {
	_ = "STUB: not implemented"
	return 0, nil
}

func (m *RunnablePolicySet_ResourcePolicy) MarshalToSizedBufferVT(dAtA []byte) (int, error) {
	_ = "STUB: not implemented"
	return 0, nil
}

func (m *RunnablePolicySet_PrincipalPolicy) MarshalToVT(dAtA []byte) (int, error) {
	_ = "STUB: not implemented"
	return 0, nil
}

func (m *RunnablePolicySet_PrincipalPolicy) MarshalToSizedBufferVT(dAtA []byte) (int, error) {
	_ = "STUB: not implemented"
	return 0, nil
}

func (m *RunnablePolicySet_DerivedRoles) MarshalToVT(dAtA []byte) (int, error) {
	_ = "STUB: not implemented"
	return 0, nil
}

func (m *RunnablePolicySet_DerivedRoles) MarshalToSizedBufferVT(dAtA []byte) (int, error) {
	_ = "STUB: not implemented"
	return 0, nil
}

func (m *RunnablePolicySet_Variables) MarshalToVT(dAtA []byte) (int, error) {
	_ = "STUB: not implemented"
	return 0, nil
}

func (m *RunnablePolicySet_Variables) MarshalToSizedBufferVT(dAtA []byte) (int, error) {
	_ = "STUB: not implemented"
	return 0, nil
}

func (m *RunnablePolicySet_RolePolicy) MarshalToVT(dAtA []byte) (int, error) {
	_ = "STUB: not implemented"
	return 0, nil
}

func (m *RunnablePolicySet_RolePolicy) MarshalToSizedBufferVT(dAtA []byte) (int, error) {
	_ = "STUB: not implemented"
	return 0, nil
}

func (m *RuleTable_RuleRow_AllowActions) MarshalVT() (dAtA []byte, err error) {
	_ = "STUB: not implemented"
	return nil, nil
}

func (m *RuleTable_RuleRow_AllowActions) MarshalToVT(dAtA []byte) (int, error) {
	_ = "STUB: not implemented"
	return 0, nil
}

func (m *RuleTable_RuleRow_AllowActions) MarshalToSizedBufferVT(dAtA []byte) (int, error) {
	_ = "STUB: not implemented"
	return 0, nil
}

func (m *RuleTable_RuleRow_Params) MarshalVT() (dAtA []byte, err error) {
	_ = "STUB: not implemented"
	return nil, nil
}

func (m *RuleTable_RuleRow_Params) MarshalToVT(dAtA []byte) (int, error) {
	_ = "STUB: not implemented"
	return 0, nil
}

func (m *RuleTable_RuleRow_Params) MarshalToSizedBufferVT(dAtA []byte) (int, error) {
	_ = "STUB: not implemented"
	return 0, nil
}

func (m *RuleTable_RuleRow) MarshalVT() (dAtA []byte, err error) {
	_ = "STUB: not implemented"
	return nil, nil
}

func (m *RuleTable_RuleRow) MarshalToVT(dAtA []byte) (int, error) {
	_ = "STUB: not implemented"
	return 0, nil
}

func (m *RuleTable_RuleRow) MarshalToSizedBufferVT(dAtA []byte) (int, error) {
	_ = "STUB: not implemented"
	return 0, nil
}

func (m *RuleTable_RuleRow_Action) MarshalToVT(dAtA []byte) (int, error) {
	_ = "STUB: not implemented"
	return 0, nil
}

func (m *RuleTable_RuleRow_Action) MarshalToSizedBufferVT(dAtA []byte) (int, error) {
	_ = "STUB: not implemented"
	return 0, nil
}

func (m *RuleTable_RuleRow_AllowActions_) MarshalToVT(dAtA []byte) (int, error) {
	_ = "STUB: not implemented"
	return 0, nil
}

func (m *RuleTable_RuleRow_AllowActions_) MarshalToSizedBufferVT(dAtA []byte) (int, error) {
	_ = "STUB: not implemented"
	return 0, nil
}

func (m *RuleTable_RoleParentRoles_ParentRoles) MarshalVT() (dAtA []byte, err error) {
	_ = "STUB: not implemented"
	return nil, nil
}

func (m *RuleTable_RoleParentRoles_ParentRoles) MarshalToVT(dAtA []byte) (int, error) {
	_ = "STUB: not implemented"
	return 0, nil
}

func (m *RuleTable_RoleParentRoles_ParentRoles) MarshalToSizedBufferVT(dAtA []byte) (int, error) {
	_ = "STUB: not implemented"
	return 0, nil
}

func (m *RuleTable_RoleParentRoles) MarshalVT() (dAtA []byte, err error) {
	_ = "STUB: not implemented"
	return nil, nil
}

func (m *RuleTable_RoleParentRoles) MarshalToVT(dAtA []byte) (int, error) {
	_ = "STUB: not implemented"
	return 0, nil
}

func (m *RuleTable_RoleParentRoles) MarshalToSizedBufferVT(dAtA []byte) (int, error) {
	_ = "STUB: not implemented"
	return 0, nil
}

func (m *RuleTable_PolicyDerivedRoles) MarshalVT() (dAtA []byte, err error) {
	_ = "STUB: not implemented"
	return nil, nil
}

func (m *RuleTable_PolicyDerivedRoles) MarshalToVT(dAtA []byte) (int, error) {
	_ = "STUB: not implemented"
	return 0, nil
}

func (m *RuleTable_PolicyDerivedRoles) MarshalToSizedBufferVT(dAtA []byte) (int, error) {
	_ = "STUB: not implemented"
	return 0, nil
}

func (m *RuleTable_JSONSchema) MarshalVT() (dAtA []byte, err error) {
	_ = "STUB: not implemented"
	return nil, nil
}

func (m *RuleTable_JSONSchema) MarshalToVT(dAtA []byte) (int, error) {
	_ = "STUB: not implemented"
	return 0, nil
}

func (m *RuleTable_JSONSchema) MarshalToSizedBufferVT(dAtA []byte) (int, error) {
	_ = "STUB: not implemented"
	return 0, nil
}

func (m *RuleTable_Manifest) MarshalVT() (dAtA []byte, err error) {
	_ = "STUB: not implemented"
	return nil, nil
}

func (m *RuleTable_Manifest) MarshalToVT(dAtA []byte) (int, error) {
	_ = "STUB: not implemented"
	return 0, nil
}

func (m *RuleTable_Manifest) MarshalToSizedBufferVT(dAtA []byte) (int, error) {
	_ = "STUB: not implemented"
	return 0, nil
}

func (m *RuleTable) MarshalVT() (dAtA []byte, err error) {
	_ = "STUB: not implemented"
	return nil, nil
}

func (m *RuleTable) MarshalToVT(dAtA []byte) (int, error) { _ = "STUB: not implemented"; return 0, nil }

func (m *RuleTable) MarshalToSizedBufferVT(dAtA []byte) (int, error) {
	_ = "STUB: not implemented"
	return 0, nil
}

func (m *RuleTableMetadata) MarshalVT() (dAtA []byte, err error) {
	_ = "STUB: not implemented"
	return nil, nil
}

func (m *RuleTableMetadata) MarshalToVT(dAtA []byte) (int, error) {
	_ = "STUB: not implemented"
	return 0, nil
}

func (m *RuleTableMetadata) MarshalToSizedBufferVT(dAtA []byte) (int, error) {
	_ = "STUB: not implemented"
	return 0, nil
}

func (m *RuleTableMetadata_Resource) MarshalToVT(dAtA []byte) (int, error) {
	_ = "STUB: not implemented"
	return 0, nil
}

func (m *RuleTableMetadata_Resource) MarshalToSizedBufferVT(dAtA []byte) (int, error) {
	_ = "STUB: not implemented"
	return 0, nil
}

func (m *RuleTableMetadata_Role) MarshalToVT(dAtA []byte) (int, error) {
	_ = "STUB: not implemented"
	return 0, nil
}

func (m *RuleTableMetadata_Role) MarshalToSizedBufferVT(dAtA []byte) (int, error) {
	_ = "STUB: not implemented"
	return 0, nil
}

func (m *RuleTableMetadata_Principal) MarshalToVT(dAtA []byte) (int, error) {
	_ = "STUB: not implemented"
	return 0, nil
}

func (m *RuleTableMetadata_Principal) MarshalToSizedBufferVT(dAtA []byte) (int, error) {
	_ = "STUB: not implemented"
	return 0, nil
}

func (m *RunnableRolePolicySet_Metadata) MarshalVT() (dAtA []byte, err error) {
	_ = "STUB: not implemented"
	return nil, nil
}

func (m *RunnableRolePolicySet_Metadata) MarshalToVT(dAtA []byte) (int, error) {
	_ = "STUB: not implemented"
	return 0, nil
}

func (m *RunnableRolePolicySet_Metadata) MarshalToSizedBufferVT(dAtA []byte) (int, error) {
	_ = "STUB: not implemented"
	return 0, nil
}

func (m *RunnableRolePolicySet_Rule) MarshalVT() (dAtA []byte, err error) {
	_ = "STUB: not implemented"
	return nil, nil
}

func (m *RunnableRolePolicySet_Rule) MarshalToVT(dAtA []byte) (int, error) {
	_ = "STUB: not implemented"
	return 0, nil
}

func (m *RunnableRolePolicySet_Rule) MarshalToSizedBufferVT(dAtA []byte) (int, error) {
	_ = "STUB: not implemented"
	return 0, nil
}

func (m *RunnableRolePolicySet_RuleList) MarshalVT() (dAtA []byte, err error) {
	_ = "STUB: not implemented"
	return nil, nil
}

func (m *RunnableRolePolicySet_RuleList) MarshalToVT(dAtA []byte) (int, error) {
	_ = "STUB: not implemented"
	return 0, nil
}

func (m *RunnableRolePolicySet_RuleList) MarshalToSizedBufferVT(dAtA []byte) (int, error) {
	_ = "STUB: not implemented"
	return 0, nil
}

func (m *RunnableRolePolicySet) MarshalVT() (dAtA []byte, err error) {
	_ = "STUB: not implemented"
	return nil, nil
}

func (m *RunnableRolePolicySet) MarshalToVT(dAtA []byte) (int, error) {
	_ = "STUB: not implemented"
	return 0, nil
}

func (m *RunnableRolePolicySet) MarshalToSizedBufferVT(dAtA []byte) (int, error) {
	_ = "STUB: not implemented"
	return 0, nil
}

func (m *RunnableResourcePolicySet_Metadata) MarshalVT() (dAtA []byte, err error) {
	_ = "STUB: not implemented"
	return nil, nil
}

func (m *RunnableResourcePolicySet_Metadata) MarshalToVT(dAtA []byte) (int, error) {
	_ = "STUB: not implemented"
	return 0, nil
}

func (m *RunnableResourcePolicySet_Metadata) MarshalToSizedBufferVT(dAtA []byte) (int, error) {
	_ = "STUB: not implemented"
	return 0, nil
}

func (m *RunnableResourcePolicySet_Policy_Rule) MarshalVT() (dAtA []byte, err error) {
	_ = "STUB: not implemented"
	return nil, nil
}

func (m *RunnableResourcePolicySet_Policy_Rule) MarshalToVT(dAtA []byte) (int, error) {
	_ = "STUB: not implemented"
	return 0, nil
}

func (m *RunnableResourcePolicySet_Policy_Rule) MarshalToSizedBufferVT(dAtA []byte) (int, error) {
	_ = "STUB: not implemented"
	return 0, nil
}

func (m *RunnableResourcePolicySet_Policy) MarshalVT() (dAtA []byte, err error) {
	_ = "STUB: not implemented"
	return nil, nil
}

func (m *RunnableResourcePolicySet_Policy) MarshalToVT(dAtA []byte) (int, error) {
	_ = "STUB: not implemented"
	return 0, nil
}

func (m *RunnableResourcePolicySet_Policy) MarshalToSizedBufferVT(dAtA []byte) (int, error) {
	_ = "STUB: not implemented"
	return 0, nil
}

func (m *RunnableResourcePolicySet) MarshalVT() (dAtA []byte, err error) {
	_ = "STUB: not implemented"
	return nil, nil
}

func (m *RunnableResourcePolicySet) MarshalToVT(dAtA []byte) (int, error) {
	_ = "STUB: not implemented"
	return 0, nil
}

func (m *RunnableResourcePolicySet) MarshalToSizedBufferVT(dAtA []byte) (int, error) {
	_ = "STUB: not implemented"
	return 0, nil
}

func (m *RunnableDerivedRole) MarshalVT() (dAtA []byte, err error) {
	_ = "STUB: not implemented"
	return nil, nil
}

func (m *RunnableDerivedRole) MarshalToVT(dAtA []byte) (int, error) {
	_ = "STUB: not implemented"
	return 0, nil
}

func (m *RunnableDerivedRole) MarshalToSizedBufferVT(dAtA []byte) (int, error) {
	_ = "STUB: not implemented"
	return 0, nil
}

func (m *RunnableDerivedRolesSet_Metadata) MarshalVT() (dAtA []byte, err error) {
	_ = "STUB: not implemented"
	return nil, nil
}

func (m *RunnableDerivedRolesSet_Metadata) MarshalToVT(dAtA []byte) (int, error) {
	_ = "STUB: not implemented"
	return 0, nil
}

func (m *RunnableDerivedRolesSet_Metadata) MarshalToSizedBufferVT(dAtA []byte) (int, error) {
	_ = "STUB: not implemented"
	return 0, nil
}

func (m *RunnableDerivedRolesSet) MarshalVT() (dAtA []byte, err error) {
	_ = "STUB: not implemented"
	return nil, nil
}

func (m *RunnableDerivedRolesSet) MarshalToVT(dAtA []byte) (int, error) {
	_ = "STUB: not implemented"
	return 0, nil
}

func (m *RunnableDerivedRolesSet) MarshalToSizedBufferVT(dAtA []byte) (int, error) {
	_ = "STUB: not implemented"
	return 0, nil
}

func (m *RunnableVariablesSet_Metadata) MarshalVT() (dAtA []byte, err error) {
	_ = "STUB: not implemented"
	return nil, nil
}

func (m *RunnableVariablesSet_Metadata) MarshalToVT(dAtA []byte) (int, error) {
	_ = "STUB: not implemented"
	return 0, nil
}

func (m *RunnableVariablesSet_Metadata) MarshalToSizedBufferVT(dAtA []byte) (int, error) {
	_ = "STUB: not implemented"
	return 0, nil
}

func (m *RunnableVariablesSet) MarshalVT() (dAtA []byte, err error) {
	_ = "STUB: not implemented"
	return nil, nil
}

func (m *RunnableVariablesSet) MarshalToVT(dAtA []byte) (int, error) {
	_ = "STUB: not implemented"
	return 0, nil
}

func (m *RunnableVariablesSet) MarshalToSizedBufferVT(dAtA []byte) (int, error) {
	_ = "STUB: not implemented"
	return 0, nil
}

func (m *RunnablePrincipalPolicySet_Metadata) MarshalVT() (dAtA []byte, err error) {
	_ = "STUB: not implemented"
	return nil, nil
}

func (m *RunnablePrincipalPolicySet_Metadata) MarshalToVT(dAtA []byte) (int, error) {
	_ = "STUB: not implemented"
	return 0, nil
}

func (m *RunnablePrincipalPolicySet_Metadata) MarshalToSizedBufferVT(dAtA []byte) (int, error) {
	_ = "STUB: not implemented"
	return 0, nil
}

func (m *RunnablePrincipalPolicySet_Policy_ActionRule) MarshalVT() (dAtA []byte, err error) {
	_ = "STUB: not implemented"
	return nil, nil
}

func (m *RunnablePrincipalPolicySet_Policy_ActionRule) MarshalToVT(dAtA []byte) (int, error) {
	_ = "STUB: not implemented"
	return 0, nil
}

func (m *RunnablePrincipalPolicySet_Policy_ActionRule) MarshalToSizedBufferVT(dAtA []byte) (int, error) {
	_ = "STUB: not implemented"
	return 0, nil
}

func (m *RunnablePrincipalPolicySet_Policy_ResourceRules) MarshalVT() (dAtA []byte, err error) {
	_ = "STUB: not implemented"
	return nil, nil
}

func (m *RunnablePrincipalPolicySet_Policy_ResourceRules) MarshalToVT(dAtA []byte) (int, error) {
	_ = "STUB: not implemented"
	return 0, nil
}

func (m *RunnablePrincipalPolicySet_Policy_ResourceRules) MarshalToSizedBufferVT(dAtA []byte) (int, error) {
	_ = "STUB: not implemented"
	return 0, nil
}

func (m *RunnablePrincipalPolicySet_Policy) MarshalVT() (dAtA []byte, err error) {
	_ = "STUB: not implemented"
	return nil, nil
}

func (m *RunnablePrincipalPolicySet_Policy) MarshalToVT(dAtA []byte) (int, error) {
	_ = "STUB: not implemented"
	return 0, nil
}

func (m *RunnablePrincipalPolicySet_Policy) MarshalToSizedBufferVT(dAtA []byte) (int, error) {
	_ = "STUB: not implemented"
	return 0, nil
}

func (m *RunnablePrincipalPolicySet) MarshalVT() (dAtA []byte, err error) {
	_ = "STUB: not implemented"
	return nil, nil
}

func (m *RunnablePrincipalPolicySet) MarshalToVT(dAtA []byte) (int, error) {
	_ = "STUB: not implemented"
	return 0, nil
}

func (m *RunnablePrincipalPolicySet) MarshalToSizedBufferVT(dAtA []byte) (int, error) {
	_ = "STUB: not implemented"
	return 0, nil
}

func (m *Expr) MarshalVT() (dAtA []byte, err error) { _ = "STUB: not implemented"; return nil, nil }

func (m *Expr) MarshalToVT(dAtA []byte) (int, error) { _ = "STUB: not implemented"; return 0, nil }

func (m *Expr) MarshalToSizedBufferVT(dAtA []byte) (int, error) {
	_ = "STUB: not implemented"
	return 0, nil
}

func (m *Output_When) MarshalVT() (dAtA []byte, err error) {
	_ = "STUB: not implemented"
	return nil, nil
}

func (m *Output_When) MarshalToVT(dAtA []byte) (int, error) {
	_ = "STUB: not implemented"
	return 0, nil
}

func (m *Output_When) MarshalToSizedBufferVT(dAtA []byte) (int, error) {
	_ = "STUB: not implemented"
	return 0, nil
}

func (m *Output) MarshalVT() (dAtA []byte, err error) { _ = "STUB: not implemented"; return nil, nil }

func (m *Output) MarshalToVT(dAtA []byte) (int, error) { _ = "STUB: not implemented"; return 0, nil }

func (m *Output) MarshalToSizedBufferVT(dAtA []byte) (int, error) {
	_ = "STUB: not implemented"
	return 0, nil
}

func (m *Variable) MarshalVT() (dAtA []byte, err error) { _ = "STUB: not implemented"; return nil, nil }

func (m *Variable) MarshalToVT(dAtA []byte) (int, error) { _ = "STUB: not implemented"; return 0, nil }

func (m *Variable) MarshalToSizedBufferVT(dAtA []byte) (int, error) {
	_ = "STUB: not implemented"
	return 0, nil
}

func (m *Condition_ExprList) MarshalVT() (dAtA []byte, err error) {
	_ = "STUB: not implemented"
	return nil, nil
}

func (m *Condition_ExprList) MarshalToVT(dAtA []byte) (int, error) {
	_ = "STUB: not implemented"
	return 0, nil
}

func (m *Condition_ExprList) MarshalToSizedBufferVT(dAtA []byte) (int, error) {
	_ = "STUB: not implemented"
	return 0, nil
}

func (m *Condition) MarshalVT() (dAtA []byte, err error) {
	_ = "STUB: not implemented"
	return nil, nil
}

func (m *Condition) MarshalToVT(dAtA []byte) (int, error) { _ = "STUB: not implemented"; return 0, nil }

func (m *Condition) MarshalToSizedBufferVT(dAtA []byte) (int, error) {
	_ = "STUB: not implemented"
	return 0, nil
}

func (m *Condition_All) MarshalToVT(dAtA []byte) (int, error) {
	_ = "STUB: not implemented"
	return 0, nil
}

func (m *Condition_All) MarshalToSizedBufferVT(dAtA []byte) (int, error) {
	_ = "STUB: not implemented"
	return 0, nil
}

func (m *Condition_Any) MarshalToVT(dAtA []byte) (int, error) {
	_ = "STUB: not implemented"
	return 0, nil
}

func (m *Condition_Any) MarshalToSizedBufferVT(dAtA []byte) (int, error) {
	_ = "STUB: not implemented"
	return 0, nil
}

func (m *Condition_None) MarshalToVT(dAtA []byte) (int, error) {
	_ = "STUB: not implemented"
	return 0, nil
}

func (m *Condition_None) MarshalToSizedBufferVT(dAtA []byte) (int, error) {
	_ = "STUB: not implemented"
	return 0, nil
}

func (m *Condition_Expr) MarshalToVT(dAtA []byte) (int, error) {
	_ = "STUB: not implemented"
	return 0, nil
}

func (m *Condition_Expr) MarshalToSizedBufferVT(dAtA []byte) (int, error) {
	_ = "STUB: not implemented"
	return 0, nil
}

func (m *CompileErrors_Err) MarshalVT() (dAtA []byte, err error) {
	_ = "STUB: not implemented"
	return nil, nil
}

func (m *CompileErrors_Err) MarshalToVT(dAtA []byte) (int, error) {
	_ = "STUB: not implemented"
	return 0, nil
}

func (m *CompileErrors_Err) MarshalToSizedBufferVT(dAtA []byte) (int, error) {
	_ = "STUB: not implemented"
	return 0, nil
}

func (m *CompileErrors) MarshalVT() (dAtA []byte, err error) {
	_ = "STUB: not implemented"
	return nil, nil
}

func (m *CompileErrors) MarshalToVT(dAtA []byte) (int, error) {
	_ = "STUB: not implemented"
	return 0, nil
}

func (m *CompileErrors) MarshalToSizedBufferVT(dAtA []byte) (int, error) {
	_ = "STUB: not implemented"
	return 0, nil
}

func (m *IndexBuildErrors_DuplicateDef) MarshalVT() (dAtA []byte, err error) {
	_ = "STUB: not implemented"
	return nil, nil
}

func (m *IndexBuildErrors_DuplicateDef) MarshalToVT(dAtA []byte) (int, error) {
	_ = "STUB: not implemented"
	return 0, nil
}

func (m *IndexBuildErrors_DuplicateDef) MarshalToSizedBufferVT(dAtA []byte) (int, error) {
	_ = "STUB: not implemented"
	return 0, nil
}

func (m *IndexBuildErrors_MissingImport) MarshalVT() (dAtA []byte, err error) {
	_ = "STUB: not implemented"
	return nil, nil
}

func (m *IndexBuildErrors_MissingImport) MarshalToVT(dAtA []byte) (int, error) {
	_ = "STUB: not implemented"
	return 0, nil
}

func (m *IndexBuildErrors_MissingImport) MarshalToSizedBufferVT(dAtA []byte) (int, error) {
	_ = "STUB: not implemented"
	return 0, nil
}

func (m *IndexBuildErrors_MissingScope) MarshalVT() (dAtA []byte, err error) {
	_ = "STUB: not implemented"
	return nil, nil
}

func (m *IndexBuildErrors_MissingScope) MarshalToVT(dAtA []byte) (int, error) {
	_ = "STUB: not implemented"
	return 0, nil
}

func (m *IndexBuildErrors_MissingScope) MarshalToSizedBufferVT(dAtA []byte) (int, error) {
	_ = "STUB: not implemented"
	return 0, nil
}

func (m *IndexBuildErrors_ScopePermissionsConflicts) MarshalVT() (dAtA []byte, err error) {
	_ = "STUB: not implemented"
	return nil, nil
}

func (m *IndexBuildErrors_ScopePermissionsConflicts) MarshalToVT(dAtA []byte) (int, error) {
	_ = "STUB: not implemented"
	return 0, nil
}

func (m *IndexBuildErrors_ScopePermissionsConflicts) MarshalToSizedBufferVT(dAtA []byte) (int, error) {
	_ = "STUB: not implemented"
	return 0, nil
}

func (m *IndexBuildErrors_LoadFailure) MarshalVT() (dAtA []byte, err error) {
	_ = "STUB: not implemented"
	return nil, nil
}

func (m *IndexBuildErrors_LoadFailure) MarshalToVT(dAtA []byte) (int, error) {
	_ = "STUB: not implemented"
	return 0, nil
}

func (m *IndexBuildErrors_LoadFailure) MarshalToSizedBufferVT(dAtA []byte) (int, error) {
	_ = "STUB: not implemented"
	return 0, nil
}

func (m *IndexBuildErrors_Disabled) MarshalVT() (dAtA []byte, err error) {
	_ = "STUB: not implemented"
	return nil, nil
}

func (m *IndexBuildErrors_Disabled) MarshalToVT(dAtA []byte) (int, error) {
	_ = "STUB: not implemented"
	return 0, nil
}

func (m *IndexBuildErrors_Disabled) MarshalToSizedBufferVT(dAtA []byte) (int, error) {
	_ = "STUB: not implemented"
	return 0, nil
}

func (m *IndexBuildErrors) MarshalVT() (dAtA []byte, err error) {
	_ = "STUB: not implemented"
	return nil, nil
}

func (m *IndexBuildErrors) MarshalToVT(dAtA []byte) (int, error) {
	_ = "STUB: not implemented"
	return 0, nil
}

func (m *IndexBuildErrors) MarshalToSizedBufferVT(dAtA []byte) (int, error) {
	_ = "STUB: not implemented"
	return 0, nil
}

func (m *Errors) MarshalVT() (dAtA []byte, err error) { _ = "STUB: not implemented"; return nil, nil }

func (m *Errors) MarshalToVT(dAtA []byte) (int, error) { _ = "STUB: not implemented"; return 0, nil }

func (m *Errors) MarshalToSizedBufferVT(dAtA []byte) (int, error) {
	_ = "STUB: not implemented"
	return 0, nil
}

func (m *Errors_IndexBuildErrors) MarshalToVT(dAtA []byte) (int, error) {
	_ = "STUB: not implemented"
	return 0, nil
}

func (m *Errors_IndexBuildErrors) MarshalToSizedBufferVT(dAtA []byte) (int, error) {
	_ = "STUB: not implemented"
	return 0, nil
}

func (m *Errors_CompileErrors) MarshalToVT(dAtA []byte) (int, error) {
	_ = "STUB: not implemented"
	return 0, nil
}

func (m *Errors_CompileErrors) MarshalToSizedBufferVT(dAtA []byte) (int, error) {
	_ = "STUB: not implemented"
	return 0, nil
}

func (m *BitmapIndex_Entry) MarshalVT() (dAtA []byte, err error) {
	_ = "STUB: not implemented"
	return nil, nil
}

func (m *BitmapIndex_Entry) MarshalToVT(dAtA []byte) (int, error) {
	_ = "STUB: not implemented"
	return 0, nil
}

func (m *BitmapIndex_Entry) MarshalToSizedBufferVT(dAtA []byte) (int, error) {
	_ = "STUB: not implemented"
	return 0, nil
}

func (m *BitmapIndex_GlobDimension) MarshalVT() (dAtA []byte, err error) {
	_ = "STUB: not implemented"
	return nil, nil
}

func (m *BitmapIndex_GlobDimension) MarshalToVT(dAtA []byte) (int, error) {
	_ = "STUB: not implemented"
	return 0, nil
}

func (m *BitmapIndex_GlobDimension) MarshalToSizedBufferVT(dAtA []byte) (int, error) {
	_ = "STUB: not implemented"
	return 0, nil
}

func (m *BitmapIndex_AllowActions) MarshalVT() (dAtA []byte, err error) {
	_ = "STUB: not implemented"
	return nil, nil
}

func (m *BitmapIndex_AllowActions) MarshalToVT(dAtA []byte) (int, error) {
	_ = "STUB: not implemented"
	return 0, nil
}

func (m *BitmapIndex_AllowActions) MarshalToSizedBufferVT(dAtA []byte) (int, error) {
	_ = "STUB: not implemented"
	return 0, nil
}

func (m *BitmapIndex_Binding) MarshalVT() (dAtA []byte, err error) {
	_ = "STUB: not implemented"
	return nil, nil
}

func (m *BitmapIndex_Binding) MarshalToVT(dAtA []byte) (int, error) {
	_ = "STUB: not implemented"
	return 0, nil
}

func (m *BitmapIndex_Binding) MarshalToSizedBufferVT(dAtA []byte) (int, error) {
	_ = "STUB: not implemented"
	return 0, nil
}

func (m *BitmapIndex_Binding_Action) MarshalToVT(dAtA []byte) (int, error) {
	_ = "STUB: not implemented"
	return 0, nil
}

func (m *BitmapIndex_Binding_Action) MarshalToSizedBufferVT(dAtA []byte) (int, error) {
	_ = "STUB: not implemented"
	return 0, nil
}

func (m *BitmapIndex_Binding_AllowActions) MarshalToVT(dAtA []byte) (int, error) {
	_ = "STUB: not implemented"
	return 0, nil
}

func (m *BitmapIndex_Binding_AllowActions) MarshalToSizedBufferVT(dAtA []byte) (int, error) {
	_ = "STUB: not implemented"
	return 0, nil
}

func (m *BitmapIndex_FunctionalCore) MarshalVT() (dAtA []byte, err error) {
	_ = "STUB: not implemented"
	return nil, nil
}

func (m *BitmapIndex_FunctionalCore) MarshalToVT(dAtA []byte) (int, error) {
	_ = "STUB: not implemented"
	return 0, nil
}

func (m *BitmapIndex_FunctionalCore) MarshalToSizedBufferVT(dAtA []byte) (int, error) {
	_ = "STUB: not implemented"
	return 0, nil
}

func (m *BitmapIndex_Parents) MarshalVT() (dAtA []byte, err error) {
	_ = "STUB: not implemented"
	return nil, nil
}

func (m *BitmapIndex_Parents) MarshalToVT(dAtA []byte) (int, error) {
	_ = "STUB: not implemented"
	return 0, nil
}

func (m *BitmapIndex_Parents) MarshalToSizedBufferVT(dAtA []byte) (int, error) {
	_ = "STUB: not implemented"
	return 0, nil
}

func (m *BitmapIndex_RoleParents) MarshalVT() (dAtA []byte, err error) {
	_ = "STUB: not implemented"
	return nil, nil
}

func (m *BitmapIndex_RoleParents) MarshalToVT(dAtA []byte) (int, error) {
	_ = "STUB: not implemented"
	return 0, nil
}

func (m *BitmapIndex_RoleParents) MarshalToSizedBufferVT(dAtA []byte) (int, error) {
	_ = "STUB: not implemented"
	return 0, nil
}

func (m *BitmapIndex) MarshalVT() (dAtA []byte, err error) {
	_ = "STUB: not implemented"
	return nil, nil
}

func (m *BitmapIndex) MarshalToVT(dAtA []byte) (int, error) {
	_ = "STUB: not implemented"
	return 0, nil
}

func (m *BitmapIndex) MarshalToSizedBufferVT(dAtA []byte) (int, error) {
	_ = "STUB: not implemented"
	return 0, nil
}

func (m *RunnablePolicySet) SizeVT() (n int) { _ = "STUB: not implemented"; return 0 }

func (m *RunnablePolicySet_ResourcePolicy) SizeVT() (n int) { _ = "STUB: not implemented"; return 0 }

func (m *RunnablePolicySet_PrincipalPolicy) SizeVT() (n int) { _ = "STUB: not implemented"; return 0 }

func (m *RunnablePolicySet_DerivedRoles) SizeVT() (n int) { _ = "STUB: not implemented"; return 0 }

func (m *RunnablePolicySet_Variables) SizeVT() (n int) { _ = "STUB: not implemented"; return 0 }

func (m *RunnablePolicySet_RolePolicy) SizeVT() (n int) { _ = "STUB: not implemented"; return 0 }

func (m *RuleTable_RuleRow_AllowActions) SizeVT() (n int) { _ = "STUB: not implemented"; return 0 }

func (m *RuleTable_RuleRow_Params) SizeVT() (n int) { _ = "STUB: not implemented"; return 0 }

func (m *RuleTable_RuleRow) SizeVT() (n int) { _ = "STUB: not implemented"; return 0 }

func (m *RuleTable_RuleRow_Action) SizeVT() (n int) { _ = "STUB: not implemented"; return 0 }

func (m *RuleTable_RuleRow_AllowActions_) SizeVT() (n int) { _ = "STUB: not implemented"; return 0 }

func (m *RuleTable_RoleParentRoles_ParentRoles) SizeVT() (n int) {
	_ = "STUB: not implemented"
	return 0
}

func (m *RuleTable_RoleParentRoles) SizeVT() (n int) { _ = "STUB: not implemented"; return 0 }

func (m *RuleTable_PolicyDerivedRoles) SizeVT() (n int) { _ = "STUB: not implemented"; return 0 }

func (m *RuleTable_JSONSchema) SizeVT() (n int) { _ = "STUB: not implemented"; return 0 }

func (m *RuleTable_Manifest) SizeVT() (n int) { _ = "STUB: not implemented"; return 0 }

func (m *RuleTable) SizeVT() (n int) { _ = "STUB: not implemented"; return 0 }

func (m *RuleTableMetadata) SizeVT() (n int) { _ = "STUB: not implemented"; return 0 }

func (m *RuleTableMetadata_Resource) SizeVT() (n int) { _ = "STUB: not implemented"; return 0 }

func (m *RuleTableMetadata_Role) SizeVT() (n int) { _ = "STUB: not implemented"; return 0 }

func (m *RuleTableMetadata_Principal) SizeVT() (n int) { _ = "STUB: not implemented"; return 0 }

func (m *RunnableRolePolicySet_Metadata) SizeVT() (n int) { _ = "STUB: not implemented"; return 0 }

func (m *RunnableRolePolicySet_Rule) SizeVT() (n int) { _ = "STUB: not implemented"; return 0 }

func (m *RunnableRolePolicySet_RuleList) SizeVT() (n int) { _ = "STUB: not implemented"; return 0 }

func (m *RunnableRolePolicySet) SizeVT() (n int) { _ = "STUB: not implemented"; return 0 }

func (m *RunnableResourcePolicySet_Metadata) SizeVT() (n int) { _ = "STUB: not implemented"; return 0 }

func (m *RunnableResourcePolicySet_Policy_Rule) SizeVT() (n int) {
	_ = "STUB: not implemented"
	return 0
}

func (m *RunnableResourcePolicySet_Policy) SizeVT() (n int) { _ = "STUB: not implemented"; return 0 }

func (m *RunnableResourcePolicySet) SizeVT() (n int) { _ = "STUB: not implemented"; return 0 }

func (m *RunnableDerivedRole) SizeVT() (n int) { _ = "STUB: not implemented"; return 0 }

func (m *RunnableDerivedRolesSet_Metadata) SizeVT() (n int) { _ = "STUB: not implemented"; return 0 }

func (m *RunnableDerivedRolesSet) SizeVT() (n int) { _ = "STUB: not implemented"; return 0 }

func (m *RunnableVariablesSet_Metadata) SizeVT() (n int) { _ = "STUB: not implemented"; return 0 }

func (m *RunnableVariablesSet) SizeVT() (n int) { _ = "STUB: not implemented"; return 0 }

func (m *RunnablePrincipalPolicySet_Metadata) SizeVT() (n int) { _ = "STUB: not implemented"; return 0 }

func (m *RunnablePrincipalPolicySet_Policy_ActionRule) SizeVT() (n int) {
	_ = "STUB: not implemented"
	return 0
}

func (m *RunnablePrincipalPolicySet_Policy_ResourceRules) SizeVT() (n int) {
	_ = "STUB: not implemented"
	return 0
}

func (m *RunnablePrincipalPolicySet_Policy) SizeVT() (n int) { _ = "STUB: not implemented"; return 0 }

func (m *RunnablePrincipalPolicySet) SizeVT() (n int) { _ = "STUB: not implemented"; return 0 }

func (m *Expr) SizeVT() (n int) { _ = "STUB: not implemented"; return 0 }

func (m *Output_When) SizeVT() (n int) { _ = "STUB: not implemented"; return 0 }

func (m *Output) SizeVT() (n int) { _ = "STUB: not implemented"; return 0 }

func (m *Variable) SizeVT() (n int) { _ = "STUB: not implemented"; return 0 }

func (m *Condition_ExprList) SizeVT() (n int) { _ = "STUB: not implemented"; return 0 }

func (m *Condition) SizeVT() (n int) { _ = "STUB: not implemented"; return 0 }

func (m *Condition_All) SizeVT() (n int) { _ = "STUB: not implemented"; return 0 }

func (m *Condition_Any) SizeVT() (n int) { _ = "STUB: not implemented"; return 0 }

func (m *Condition_None) SizeVT() (n int) { _ = "STUB: not implemented"; return 0 }

func (m *Condition_Expr) SizeVT() (n int) { _ = "STUB: not implemented"; return 0 }

func (m *CompileErrors_Err) SizeVT() (n int) { _ = "STUB: not implemented"; return 0 }

func (m *CompileErrors) SizeVT() (n int) { _ = "STUB: not implemented"; return 0 }

func (m *IndexBuildErrors_DuplicateDef) SizeVT() (n int) { _ = "STUB: not implemented"; return 0 }

func (m *IndexBuildErrors_MissingImport) SizeVT() (n int) { _ = "STUB: not implemented"; return 0 }

func (m *IndexBuildErrors_MissingScope) SizeVT() (n int) { _ = "STUB: not implemented"; return 0 }

func (m *IndexBuildErrors_ScopePermissionsConflicts) SizeVT() (n int) {
	_ = "STUB: not implemented"
	return 0
}

func (m *IndexBuildErrors_LoadFailure) SizeVT() (n int) { _ = "STUB: not implemented"; return 0 }

func (m *IndexBuildErrors_Disabled) SizeVT() (n int) { _ = "STUB: not implemented"; return 0 }

func (m *IndexBuildErrors) SizeVT() (n int) { _ = "STUB: not implemented"; return 0 }

func (m *Errors) SizeVT() (n int) { _ = "STUB: not implemented"; return 0 }

func (m *Errors_IndexBuildErrors) SizeVT() (n int) { _ = "STUB: not implemented"; return 0 }

func (m *Errors_CompileErrors) SizeVT() (n int) { _ = "STUB: not implemented"; return 0 }

func (m *BitmapIndex_Entry) SizeVT() (n int) { _ = "STUB: not implemented"; return 0 }

func (m *BitmapIndex_GlobDimension) SizeVT() (n int) { _ = "STUB: not implemented"; return 0 }

func (m *BitmapIndex_AllowActions) SizeVT() (n int) { _ = "STUB: not implemented"; return 0 }

func (m *BitmapIndex_Binding) SizeVT() (n int) { _ = "STUB: not implemented"; return 0 }

func (m *BitmapIndex_Binding_Action) SizeVT() (n int) { _ = "STUB: not implemented"; return 0 }

func (m *BitmapIndex_Binding_AllowActions) SizeVT() (n int) { _ = "STUB: not implemented"; return 0 }

func (m *BitmapIndex_FunctionalCore) SizeVT() (n int) { _ = "STUB: not implemented"; return 0 }

func (m *BitmapIndex_Parents) SizeVT() (n int) { _ = "STUB: not implemented"; return 0 }

func (m *BitmapIndex_RoleParents) SizeVT() (n int) { _ = "STUB: not implemented"; return 0 }

func (m *BitmapIndex) SizeVT() (n int) { _ = "STUB: not implemented"; return 0 }

func (m *RunnablePolicySet) UnmarshalVT(dAtA []byte) error { _ = "STUB: not implemented"; return nil }

func (m *RuleTable_RuleRow_AllowActions) UnmarshalVT(dAtA []byte) error {
	_ = "STUB: not implemented"
	return nil
}

func (m *RuleTable_RuleRow_Params) UnmarshalVT(dAtA []byte) error {
	_ = "STUB: not implemented"
	return nil
}

func (m *RuleTable_RuleRow) UnmarshalVT(dAtA []byte) error { _ = "STUB: not implemented"; return nil }

func (m *RuleTable_RoleParentRoles_ParentRoles) UnmarshalVT(dAtA []byte) error {
	_ = "STUB: not implemented"
	return nil
}

func (m *RuleTable_RoleParentRoles) UnmarshalVT(dAtA []byte) error {
	_ = "STUB: not implemented"
	return nil
}

func (m *RuleTable_PolicyDerivedRoles) UnmarshalVT(dAtA []byte) error {
	_ = "STUB: not implemented"
	return nil
}

func (m *RuleTable_JSONSchema) UnmarshalVT(dAtA []byte) error {
	_ = "STUB: not implemented"
	return nil
}

func (m *RuleTable_Manifest) UnmarshalVT(dAtA []byte) error { _ = "STUB: not implemented"; return nil }

func (m *RuleTable) UnmarshalVT(dAtA []byte) error { _ = "STUB: not implemented"; return nil }

func (m *RuleTableMetadata) UnmarshalVT(dAtA []byte) error { _ = "STUB: not implemented"; return nil }

func (m *RunnableRolePolicySet_Metadata) UnmarshalVT(dAtA []byte) error {
	_ = "STUB: not implemented"
	return nil
}

func (m *RunnableRolePolicySet_Rule) UnmarshalVT(dAtA []byte) error {
	_ = "STUB: not implemented"
	return nil
}

func (m *RunnableRolePolicySet_RuleList) UnmarshalVT(dAtA []byte) error {
	_ = "STUB: not implemented"
	return nil
}

func (m *RunnableRolePolicySet) UnmarshalVT(dAtA []byte) error {
	_ = "STUB: not implemented"
	return nil
}

func (m *RunnableResourcePolicySet_Metadata) UnmarshalVT(dAtA []byte) error {
	_ = "STUB: not implemented"
	return nil
}

func (m *RunnableResourcePolicySet_Policy_Rule) UnmarshalVT(dAtA []byte) error {
	_ = "STUB: not implemented"
	return nil
}

func (m *RunnableResourcePolicySet_Policy) UnmarshalVT(dAtA []byte) error {
	_ = "STUB: not implemented"
	return nil
}

func (m *RunnableResourcePolicySet) UnmarshalVT(dAtA []byte) error {
	_ = "STUB: not implemented"
	return nil
}

func (m *RunnableDerivedRole) UnmarshalVT(dAtA []byte) error { _ = "STUB: not implemented"; return nil }

func (m *RunnableDerivedRolesSet_Metadata) UnmarshalVT(dAtA []byte) error {
	_ = "STUB: not implemented"
	return nil
}

func (m *RunnableDerivedRolesSet) UnmarshalVT(dAtA []byte) error {
	_ = "STUB: not implemented"
	return nil
}

func (m *RunnableVariablesSet_Metadata) UnmarshalVT(dAtA []byte) error {
	_ = "STUB: not implemented"
	return nil
}

func (m *RunnableVariablesSet) UnmarshalVT(dAtA []byte) error {
	_ = "STUB: not implemented"
	return nil
}

func (m *RunnablePrincipalPolicySet_Metadata) UnmarshalVT(dAtA []byte) error {
	_ = "STUB: not implemented"
	return nil
}

func (m *RunnablePrincipalPolicySet_Policy_ActionRule) UnmarshalVT(dAtA []byte) error {
	_ = "STUB: not implemented"
	return nil
}

func (m *RunnablePrincipalPolicySet_Policy_ResourceRules) UnmarshalVT(dAtA []byte) error {
	_ = "STUB: not implemented"
	return nil
}

func (m *RunnablePrincipalPolicySet_Policy) UnmarshalVT(dAtA []byte) error {
	_ = "STUB: not implemented"
	return nil
}

func (m *RunnablePrincipalPolicySet) UnmarshalVT(dAtA []byte) error {
	_ = "STUB: not implemented"
	return nil
}

func (m *Expr) UnmarshalVT(dAtA []byte) error { _ = "STUB: not implemented"; return nil }

func (m *Output_When) UnmarshalVT(dAtA []byte) error { _ = "STUB: not implemented"; return nil }

func (m *Output) UnmarshalVT(dAtA []byte) error { _ = "STUB: not implemented"; return nil }

func (m *Variable) UnmarshalVT(dAtA []byte) error { _ = "STUB: not implemented"; return nil }

func (m *Condition_ExprList) UnmarshalVT(dAtA []byte) error { _ = "STUB: not implemented"; return nil }

func (m *Condition) UnmarshalVT(dAtA []byte) error { _ = "STUB: not implemented"; return nil }

func (m *CompileErrors_Err) UnmarshalVT(dAtA []byte) error { _ = "STUB: not implemented"; return nil }

func (m *CompileErrors) UnmarshalVT(dAtA []byte) error { _ = "STUB: not implemented"; return nil }

func (m *IndexBuildErrors_DuplicateDef) UnmarshalVT(dAtA []byte) error {
	_ = "STUB: not implemented"
	return nil
}

func (m *IndexBuildErrors_MissingImport) UnmarshalVT(dAtA []byte) error {
	_ = "STUB: not implemented"
	return nil
}

func (m *IndexBuildErrors_MissingScope) UnmarshalVT(dAtA []byte) error {
	_ = "STUB: not implemented"
	return nil
}

func (m *IndexBuildErrors_ScopePermissionsConflicts) UnmarshalVT(dAtA []byte) error {
	_ = "STUB: not implemented"
	return nil
}

func (m *IndexBuildErrors_LoadFailure) UnmarshalVT(dAtA []byte) error {
	_ = "STUB: not implemented"
	return nil
}

func (m *IndexBuildErrors_Disabled) UnmarshalVT(dAtA []byte) error {
	_ = "STUB: not implemented"
	return nil
}

func (m *IndexBuildErrors) UnmarshalVT(dAtA []byte) error { _ = "STUB: not implemented"; return nil }

func (m *Errors) UnmarshalVT(dAtA []byte) error { _ = "STUB: not implemented"; return nil }

func (m *BitmapIndex_Entry) UnmarshalVT(dAtA []byte) error { _ = "STUB: not implemented"; return nil }

func (m *BitmapIndex_GlobDimension) UnmarshalVT(dAtA []byte) error {
	_ = "STUB: not implemented"
	return nil
}

func (m *BitmapIndex_AllowActions) UnmarshalVT(dAtA []byte) error {
	_ = "STUB: not implemented"
	return nil
}

func (m *BitmapIndex_Binding) UnmarshalVT(dAtA []byte) error { _ = "STUB: not implemented"; return nil }

func (m *BitmapIndex_FunctionalCore) UnmarshalVT(dAtA []byte) error {
	_ = "STUB: not implemented"
	return nil
}

func (m *BitmapIndex_Parents) UnmarshalVT(dAtA []byte) error { _ = "STUB: not implemented"; return nil }

func (m *BitmapIndex_RoleParents) UnmarshalVT(dAtA []byte) error {
	_ = "STUB: not implemented"
	return nil
}

func (m *BitmapIndex) UnmarshalVT(dAtA []byte) error { _ = "STUB: not implemented"; return nil }
