// Copyright 2021-2026 Zenauth Ltd.
// SPDX-License-Identifier: Apache-2.0

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: cerbos/state/v1/state.proto

package statev1

import (
	sync "sync"

	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type TelemetryState struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Uuid          string                 `protobuf:"bytes,1,opt,name=uuid,proto3" json:"uuid,omitempty"`
	LastTimestamp *timestamppb.Timestamp `protobuf:"bytes,2,opt,name=last_timestamp,json=lastTimestamp,proto3" json:"last_timestamp,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TelemetryState) Reset() { _ = "STUB: not implemented"; return }

func (x *TelemetryState) String() string { _ = "STUB: not implemented"; return "" }

func (*TelemetryState) ProtoMessage() { _ = "STUB: not implemented"; return }

func (x *TelemetryState) ProtoReflect() protoreflect.Message {
	_ = "STUB: not implemented"
	return *new(protoreflect.Message)
}

// Deprecated: Use TelemetryState.ProtoReflect.Descriptor instead.
func (*TelemetryState) Descriptor() ([]byte, []int) { _ = "STUB: not implemented"; return nil, nil }

func (x *TelemetryState) GetUuid() string { _ = "STUB: not implemented"; return "" }

func (x *TelemetryState) GetLastTimestamp() *timestamppb.Timestamp {
	_ = "STUB: not implemented"
	return nil
}

var File_cerbos_state_v1_state_proto protoreflect.FileDescriptor

const file_cerbos_state_v1_state_proto_rawDesc = "" +
	"\n" +
	"\x1bcerbos/state/v1/state.proto\x12\x0fcerbos.state.v1\x1a\x1fgoogle/protobuf/timestamp.proto\"g\n" +
	"\x0eTelemetryState\x12\x12\n" +
	"\x04uuid\x18\x01 \x01(\tR\x04uuid\x12A\n" +
	"\x0elast_timestamp\x18\x02 \x01(\v2\x1a.google.protobuf.TimestampR\rlastTimestampB<Z:github.com/cerbos/cerbos/api/genpb/cerbos/state/v1;statev1b\x06proto3"

var (
	file_cerbos_state_v1_state_proto_rawDescOnce sync.Once
	file_cerbos_state_v1_state_proto_rawDescData []byte
)

func file_cerbos_state_v1_state_proto_rawDescGZIP() []byte { _ = "STUB: not implemented"; return nil }

var file_cerbos_state_v1_state_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_cerbos_state_v1_state_proto_goTypes = []any{
	(*TelemetryState)(nil),        // 0: cerbos.state.v1.TelemetryState
	(*timestamppb.Timestamp)(nil), // 1: google.protobuf.Timestamp
}
var file_cerbos_state_v1_state_proto_depIdxs = []int32{
	1, // 0: cerbos.state.v1.TelemetryState.last_timestamp:type_name -> google.protobuf.Timestamp
	1, // [1:1] is the sub-list for method output_type
	1, // [1:1] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init()                                  { file_cerbos_state_v1_state_proto_init() }
func file_cerbos_state_v1_state_proto_init() { _ = "STUB: not implemented"; return }
